// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/gantt/load-on-demand.jsx
import * as React from 'react';
import { GanttComponent, Inject, Selection, ColumnsDirective, ColumnDirective, VirtualScroll } from '@syncfusion/ej2-react-gantt';
import { DataManager, WebApiAdaptor } from '@syncfusion/ej2-data';
import { SampleBase } from '../common/sample-base';
export class LoadOnDemand extends SampleBase {
    dataSource = new DataManager({
        url: 'http://localhost:62728/api/GanttLoadOnDemand',
        adaptor: new WebApiAdaptor,
        crossDomain: true
    });
    taskFields = {
        id: 'taskId',
        name: 'taskName',
        startDate: 'startDate',
        endDate: 'endDate',
        duration: 'duration',
        progress: 'progress',
        hasChildMapping: 'isParent',
        parentID: 'parentID'
    };
    projectStartDate = new Date('01/02/2000');
    projectEndDate = new Date('12/01/2002');
    render() {
        return (<div className='control-pane'>
        <div className='control-section'>
          <GanttComponent id='LoadOnDemand' dataSource={this.dataSource} treeColumnIndex={1} taskFields={this.taskFields} enableVirtualization={true} loadChildOnDemand={true} height='460px' projectStartDate={this.projectStartDate} projectEndDate={this.projectEndDate}>
              <ColumnsDirective>
              <ColumnDirective field='taskId' width='80' headerText='Task ID'></ColumnDirective>
              <ColumnDirective field='taskName' headerText='Task Name' width='250' allowReordering={false}></ColumnDirective>
              <ColumnDirective field='startDate' headerText='Start Date' allowSorting={false}></ColumnDirective>
              <ColumnDirective field='duration' headerText='Duration' allowEditing={false}></ColumnDirective>
              <ColumnDirective field='progress' headerText='Progress' allowFiltering={false}></ColumnDirective>
              </ColumnsDirective>
            <Inject services={[Selection, VirtualScroll]}/>
          </GanttComponent>
        </div>
      <div id="action-description">
          <p>This sample demonstrates the load on-demand data binding support in Gantt Chart. It allows users to load parent records alone on load time. 
          Child records render on demand during expansion action.</p>
      </div>

      <div id="description">
      <p>
          Load on demand and virtualization support is used to render a large number of tasks in the Gantt Chart with an effective performance.
          And so, in this demo, row virtualization is enabled with remote data binding which has 50,000 records.
        </p>
        <p>
          With the virtualization feature enabled in remote data binding, only the root level records are fetched from the remote server at the initial load time.
          So, need to set the <code>hasChildMapping</code> property of <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/api/gantt#taskfields">taskFields</a> that denotes whichever records have child records and set <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/api/gantt#loadchildondemand">loadChildOnDemand</a> property as false.
        </p>
        <p>
        When expanding the root parent node or scrolling vertically, the corresponding tasks are dynamically fetched from the remote server and then updated in the DOM based on the current viewport position.
        </p>
        </div>
      </div>);
    }
}

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/src/gantt/load-on-demand.vue
<template>
<div>
<div class="col-lg-12 control-section">
    <div class="content-wrapper">
        <ejs-gantt ref='gantt' id="GanttContainer" 
            :dataSource= "dataSource"
            :taskFields= "taskFields"
            :allowSelection= "true"
            :allowResizing= "true"
            :height= "height"
            :treeColumnIndex= "1"
            :highlightWeekends= "true"
            :columns= "columns"
            :enableVirtualization="true"
            :loadChildOnDemand = "true"
            :projectStartDate= "projectStartDate"
            :projectEndDate= "projectEndDate"
            :splitterSettings= "splitterSettings"
            >
        </ejs-gantt>
    </div>
</div>

<div id="action-description">
<p>This sample demonstrates the load on-demand data binding support in Gantt Chart. It allows users to load parent records alone on load time. Child records render on demand during expansion action.</p>
</div>

<div id="description">
    <p>
        Load on demand and virtualization support is used to render a large number of tasks in the Gantt Chart with an effective performance. And so, in this demo, row virtualization is enabled with remote data binding which has 50,000 records.
    </p>
    <p>
        With the virtualization feature enabled in remote data binding, only the root level records are fetched from the remote server at the initial load time. So, need to set the <code>hasChildMapping</code> property of <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/gantt#taskfields">taskFields</a> that denotes whichever records have child records and set <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/gantt#loadchildondemand">loadChildOnDemand</a> property as false.
    </p>
    <p>
        When expanding the root parent node or scrolling vertically, the corresponding tasks are dynamically fetched from the remote server and then updated in the DOM based on the current viewport position.
    </p>
</div>
</div>
</template>
<script>
import { GanttComponent, Selection, VirtualScroll  } from "@syncfusion/ej2-vue-gantt";
import { DataManager, WebApiAdaptor } from '@syncfusion/ej2-data';

export default {
  components: {
    'ejs-gantt': GanttComponent,
  },
  data: function() {
      return{
            dataSource: new DataManager({
        url: 'https://ej2services.syncfusion.com/production/web-services/api/GanttLoadOnDemand',
        adaptor: new WebApiAdaptor,
        crossDomain: true
    }),     
            taskFields: {
            id: 'taskId',
            name: 'taskName',
            startDate: 'startDate',
            endDate: 'endDate',
            duration: 'duration',
            progress: 'progress',
            hasChildMapping: 'isParent',
            parentID: 'parentID'
            },
            height: '460px',
            columns: [
			    { field: 'taskId' },
                { field: 'taskName', headerText: 'Task Name', width: '250', clipMode: 'EllipsisWithTooltip' },
                { field: 'startDate' },
                { field: 'duration' },
                { field: 'progress' }
            ],
            projectStartDate: new Date('01/02/2000'),
            projectEndDate: new Date('12/01/2002'),

            splitterSettings: {
                columnIndex: 3
            }
      };
  },
  provide: {
      gantt: [ Selection, VirtualScroll]
  }
}
</script>
