// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/spreadsheet/freeze-pane.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.FreezePane = void 0;
var React = require("react");
var ej2_react_spreadsheet_1 = require("@syncfusion/ej2-react-spreadsheet");
var ej2_react_spreadsheet_2 = require("@syncfusion/ej2-react-spreadsheet");
var data_1 = require("./data");
var sample_base_1 = require("../common/sample-base");
require("./spreadsheet.css");
/**
 * Freeze pane Spreadsheet sample
 */
var FreezePane = /** @class */ (function (_super) {
    __extends(FreezePane, _super);
    function FreezePane() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.cellStyle = { fontSize: '12pt', fontWeight: 'bold', textAlign: 'center', verticalAlign: 'middle' };
        _this.bold = { fontWeight: 'bold' };
        return _this;
    }
    FreezePane.prototype.onCreated = function () {
        this.spreadsheet.wrap("C2:P2");
        this.spreadsheet.merge('A1:B1');
        this.spreadsheet.merge('C1:P1');
        this.spreadsheet.cellFormat({ backgroundColor: '#4e4ee6', color: '#FFFFF4', fontSize: '12pt', fontWeight: 'bold', textAlign: 'center', verticalAlign: 'middle' }, 'A1:P2');
        this.spreadsheet.cellFormat({ backgroundColor: '#4e4ee6', color: '#FFFFF4' }, 'A3:B26');
        this.spreadsheet.numberFormat('$#,##0.00', 'C2:P26');
        this.spreadsheet.numberFormat('$#,##0.00', 'O27:P27');
    };
    FreezePane.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section spreadsheet-control' },
                React.createElement(ej2_react_spreadsheet_1.SpreadsheetComponent, { openUrl: 'https://ej2services.syncfusion.com/production/web-services/api/spreadsheet/open', saveUrl: 'https://ej2services.syncfusion.com/production/web-services/api/spreadsheet/save', ref: function (ssObj) { _this.spreadsheet = ssObj; }, created: this.onCreated.bind(this) },
                    React.createElement(ej2_react_spreadsheet_1.SheetsDirective, null,
                        React.createElement(ej2_react_spreadsheet_1.SheetDirective, { name: 'Gross Salary', frozenRows: 2, frozenColumns: 2, selectedRange: 'C1' },
                            React.createElement(ej2_react_spreadsheet_1.RangesDirective, null,
                                React.createElement(ej2_react_spreadsheet_1.RangeDirective, { dataSource: data_1.freezePaneData, startCell: 'A2' })),
                            React.createElement(ej2_react_spreadsheet_2.RowsDirective, null,
                                React.createElement(ej2_react_spreadsheet_2.RowDirective, null,
                                    React.createElement(ej2_react_spreadsheet_2.CellsDirective, null,
                                        React.createElement(ej2_react_spreadsheet_2.CellDirective, { index: 1, value: 'Period', style: this.cellStyle }),
                                        React.createElement(ej2_react_spreadsheet_2.CellDirective, { index: 3, value: 'Total Gross Salary', style: this.cellStyle }))),
                                React.createElement(ej2_react_spreadsheet_2.RowDirective, { index: 26 },
                                    React.createElement(ej2_react_spreadsheet_2.CellsDirective, null,
                                        React.createElement(ej2_react_spreadsheet_2.CellDirective, { index: 13, value: "Total Amount:", style: this.bold }),
                                        React.createElement(ej2_react_spreadsheet_2.CellDirective, { formula: '=SUM(O4:O26)', style: this.cellStyle }),
                                        React.createElement(ej2_react_spreadsheet_2.CellDirective, { formula: '=SUM(P4:P26)', style: this.cellStyle })))),
                            React.createElement(ej2_react_spreadsheet_1.ColumnsDirective, null,
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 80 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 80 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 80 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 }),
                                React.createElement(ej2_react_spreadsheet_2.ColumnDirective, { width: 100 })))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null,
                    "This sample demonstrates the ",
                    React.createElement("code", null, "Spreadsheet"),
                    " freeze pane feature by applying frozen rows and columns with the Gross Salary scenario as an example. In this sample, you can see the frozen rows/columns that are visible while scrolling the sheet content vertically/horizontally.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "Freeze Panes helps you to keep particular rows or columns visible when scrolling the sheet content in the spreadsheet. You can specify the number of frozen rows and columns using ",
                    React.createElement("code", null, "frozenRows"),
                    " and ",
                    React.createElement("code", null, "frozenColumns"),
                    " properties inside the `Sheet` property"),
                React.createElement("p", null, "In this sample, the first 2 rows and columns are frozen using the `frozenRows` and `frozenColumns` properties."),
                React.createElement("p", null,
                    "More information about ",
                    React.createElement("code", null, "freeze pane"),
                    " can be found in this",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/spreadsheet/getting-started" }, " documentation"),
                    " section."))));
    };
    return FreezePane;
}(sample_base_1.SampleBase));
exports.FreezePane = FreezePane;

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Angular/source/spreadsheet/freeze-pane.component.ts
import { Component, ViewEncapsulation, Inject, ViewChild } from '@angular/core';
import { freezePaneData } from './data';
import { SpreadsheetComponent, SpreadsheetModule } from '@syncfusion/ej2-angular-spreadsheet';
import { SBDescriptionComponent } from '../common/dp.component';
import { SBActionDescriptionComponent } from '../common/adp.component';
/**
 * Freeze pane Spreadsheet Controller
 */
@Component({
    selector: 'control-content',
    templateUrl: 'freeze-pane.html',
    styleUrls: ['spreadsheet.css'],
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [SBActionDescriptionComponent, SpreadsheetModule, SBDescriptionComponent]
})

export class FreezePaneComponent {
    constructor(@Inject('sourceFiles') private sourceFiles: any) {
        sourceFiles.files = ['spreadsheet.css'];
    }
    @ViewChild('default')
    public spreadsheetObj: SpreadsheetComponent;
    public data: Object[] = freezePaneData();
    public styles = { fontSize: "12pt", fontWeight: "bold", textAlign: "center", verticalAlign: "middle" }
    public openUrl = 'https://ej2services.syncfusion.com/production/web-services/api/spreadsheet/open';
    public saveUrl = 'https://ej2services.syncfusion.com/production/web-services/api/spreadsheet/save';
    public freezePane: number = 2;
    created() {
        this.spreadsheetObj.wrap("C2:P2");
        this.spreadsheetObj.merge('A1:B1');
        this.spreadsheetObj.merge('C1:P1');
        this.spreadsheetObj.cellFormat({ backgroundColor: '#4e4ee6', color: '#FFFFF4', fontSize: '12pt', fontWeight: 'bold', textAlign: 'center', verticalAlign: 'middle' }, 'A1:P2');
        this.spreadsheetObj.cellFormat({ backgroundColor: '#4e4ee6', color: '#FFFFF4' }, 'A3:B26');
        this.spreadsheetObj.numberFormat('$#,##0.00', 'C2:P26');
        this.spreadsheetObj.numberFormat('$#,##0.00', 'O27:P27');
    }
}
