// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/spreadsheet/sorting-and-filtering.tsx
import * as ReactDOM from 'react-dom';
import * as React from 'react';
import { SpreadsheetComponent, SheetsDirective, SheetDirective, ColumnsDirective, RangesDirective, RangeDirective, ColumnDirective } from '@syncfusion/ej2-react-spreadsheet';
import { sortingAndFiltering } from './data';
import { SampleBase } from '../common/sample-base';
import './spreadsheet.css';

/**
 * SortingAndFiltering sample
 */

export class SortingAndFiltering extends SampleBase<{}, {}> {
    public spreadsheet: SpreadsheetComponent;

    public onCreated(): void {
        this.spreadsheet.cellFormat({ fontWeight: 'bold', textAlign:'center' }, 'A1:G1');
        this.spreadsheet.numberFormat('m/d/yyyy', 'E2:E51');
        this.spreadsheet.sort({ sortDescriptors: { field: 'B' } }, 'A2:G51').then(() => {
            this.spreadsheet.applyFilter([{ field: 'D', operator: 'equal', value: 'Services' }], 'A1:G51');
        });
        this.spreadsheet.numberFormat('$#,##0.00', 'F2:F51');
    }

    render() {
        return (
            <div className='control-pane'>
                <div className='control-section spreadsheet-control'>
                    <SpreadsheetComponent ref={(ssObj) => { this.spreadsheet = ssObj }} openUrl='https://ej2services.syncfusion.com/production/web-services/api/spreadsheet/open'
                        saveUrl='https://ej2services.syncfusion.com/production/web-services/api/spreadsheet/save' created={this.onCreated.bind(this)}>
                        <SheetsDirective>
                            <SheetDirective name='Employee Details'>
                                <RangesDirective>
                                    <RangeDirective dataSource={sortingAndFiltering} showFieldAsHeader={true} ></RangeDirective>
                                </RangesDirective>
                                <ColumnsDirective>
                                    <ColumnDirective width={110}></ColumnDirective>
                                    <ColumnDirective width={142}></ColumnDirective>
                                    <ColumnDirective width={80}></ColumnDirective>
                                    <ColumnDirective width={137}></ColumnDirective>
                                    <ColumnDirective width={122}></ColumnDirective>
                                    <ColumnDirective width={92}></ColumnDirective>
                                    <ColumnDirective width={124}></ColumnDirective>
                                </ColumnsDirective>
                            </SheetDirective>
                        </SheetsDirective>
                    </SpreadsheetComponent>
                </div>
                <div id="action-description">
                    <p>
                        This sample demonstrates sorting and filtering feature using employee details.
                    </p>
                </div>
                <div id="description">
                    <p>
                    In this demo, sorting is applied to B(Employee Name) column in ascending order using <code>sort</code> method.
                        The sort order can be specified in <code>order</code> property with following values `Ascending` or `Descending` and its
                        default value is `Ascending`.
 
                  The sorted data is filtered with value 'Services' in `D` column using <code>
                  <a target="_blank" href="https://ej2.syncfusion.com/documentation/api/spreadsheet/#applyfilter">applyFilter</a>
                  </code> method in call back function of <code>
                   <a target="_blank" href="https://ej2.syncfusion.com/documentation/api/spreadsheet/#sort">sort</a>
                 </code> method.
               </p>
                    <p>
                        More information about sorting and filtering feature can be found in this
                    <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/spreadsheet/sort/">
                        documentation</a> section.
                    </p>
                </div>
            </div>
        )
    }
}

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Angular/source/spreadsheet/sorting-and-filtering.component.ts
import { Component, ViewEncapsulation, Inject, ViewChild } from '@angular/core';
import { sortAndFilterData } from './data';
import { SpreadsheetComponent, SpreadsheetModule } from '@syncfusion/ej2-angular-spreadsheet';
import { SBDescriptionComponent } from '../common/dp.component';
import { SBActionDescriptionComponent } from '../common/adp.component';
/**
 * Sorting and Filtering Spreadsheet Component
 */
@Component({
    selector: 'control-content',
    templateUrl: 'sorting-and-filtering.html',
    styleUrls: ['spreadsheet.css'],
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [SBActionDescriptionComponent, SpreadsheetModule, SBDescriptionComponent]
})

export class SortinAndFilteringComponent {
    constructor(@Inject('sourceFiles') private sourceFiles: any) {
        sourceFiles.files = ['spreadsheet.css'];
    }
    @ViewChild('spreadsheet')
    spreadsheetObj: SpreadsheetComponent;
    data: Object[] = sortAndFilterData();
    public openUrl = 'https://ej2services.syncfusion.com/production/web-services/api/spreadsheet/open';
    public saveUrl = 'https://ej2services.syncfusion.com/production/web-services/api/spreadsheet/save';
    created() {
        this.spreadsheetObj.cellFormat({ fontWeight: 'bold', textAlign: 'center' }, 'A1:G1');
        // Sorted B(Employee Name field) column in ascending order
        this.spreadsheetObj.sort({ sortDescriptors: { field: 'B' } }, 'A2:G51').then(() => {
            // Filtered D(Department  field) column with value 'Services'
            this.spreadsheetObj.applyFilter([{ field: 'D', operator: 'equal', value: 'Services' }], 'A1:G51');
        });
        this.spreadsheetObj.numberFormat('m/d/yyyy', 'E2:E51');
        this.spreadsheetObj.numberFormat('$#,##0.00', 'F2:F51');
    }
}
