// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Angular/source/pivot-table/server-side-aggregation.component.ts
import { Component, OnInit, ViewEncapsulation, ViewChild } from '@angular/core';
import { IDataOptions, FieldListService, PivotView,PivotViewModule, GroupingBarService, VirtualScrollService } from '@syncfusion/ej2-angular-pivotview';
import { GridSettings } from '@syncfusion/ej2-pivotview/src/pivotview/model/gridsettings';
import { Browser, enableRipple } from '@syncfusion/ej2-base';
import { SBDescriptionComponent } from '../common/dp.component';
import { SBActionDescriptionComponent } from '../common/adp.component';
enableRipple(false);

/**
 * Pivot Table Server Side Aggregation Sample.
 */
@Component({
    selector: 'ej2-pivotview-container',
    styleUrls: ['server-side-aggregation.css'],
    encapsulation: ViewEncapsulation.None,
    templateUrl: 'server-side-aggregation.html',
    providers: [FieldListService, GroupingBarService, VirtualScrollService],
    standalone: true,
    imports: [PivotViewModule, SBActionDescriptionComponent, SBDescriptionComponent]
})

export class ServerSideAggregationComponent implements OnInit {

    public dataSourceSettings: IDataOptions;
    public gridSettings: GridSettings;

    @ViewChild('pivotview')
    public pivotObj: PivotView;

    onDataBound(): void {
        if (Browser.isDevice && this.pivotObj && this.pivotObj.enableRtl) {
            (document as any).querySelector('.control-section').classList.add('e-rtl');
        }
    }

    ngOnInit(): void {
        this.gridSettings = {
            columnWidth: 120
        } as GridSettings;

        this.dataSourceSettings = {
            url: 'https://ej2services.syncfusion.com/production/web-services/api/pivot/post',
            mode: 'Server',
            expandAll: false,
            enableSorting: true,
            columns: [{ name: 'Year', caption: 'Production Year' }],
            values: [
                { name: 'Sold', caption: 'Units Sold' },
                { name: 'Price', caption: 'Sold Amount' }
            ],
            rows: [{ name: 'ProductID', caption: 'Product ID' }],
            formatSettings: [{ name: 'Price', format: 'C0' }, { name: 'Sold', format: 'N0' }],
            filters: []
        };
    }
}

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/public/source/pivot-table/server-side-aggregation.vue
﻿<template>
<div>
<div class="control-section">
    <div class="content-wrapper">
        <ejs-pivotview id="pivotview" ref="pivotview" :dataSourceSettings="dataSourceSettings" :width="width" :height="height" :showFieldList="showFieldList" :showGroupingBar="showGroupingBar" :enableVirtualization="enableVirtualization" :dataBound="dataBound" :allowDataCompression="allowDataCompression">        
        </ejs-pivotview>
    </div>
</div>
<div id="action-description">
    <p>This sample demonstrates how to use a server-side pivot engine to obtain, process and return the summarized data via a remote service and display it in the pivot table.</p>
</div>
<div id="description">
    <p>
        The Pivot Table's server-side pivot engine (external pivot engine) uses the Syncfusion<sup>®</sup> package <a target="_blank"
            href="https://www.nuget.org/packages/Syncfusion.Pivot.Engine/"> Syncfusion<sup>®</sup>.Pivot.Engine</a> to gather data from the data
        source and perform all pivot operations such as <a target="_blank"
            href="https://ej2.syncfusion.com/vue/documentation/pivotview/aggregation/#aggregation">
            aggregation</a>, <a target="_blank"
                href="https://ej2.syncfusion.com/vue/documentation/pivotview/filtering/#filtering">
            filtering</a>, <a target="_blank"
                href="https://ej2.syncfusion.com/vue/documentation/pivotview/sorting/#sorting">
            sorting</a>, <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/pivotview/grouping">
            grouping</a>, and more on a separate hosted server and only paged
        data is sent to the pivot table viewport via web service.
        The <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/pivotview/dataSourceSettings/#url">
            dataSourceSettings-&gt;url</a> property allows this web service URL to be
        connected to the pivot table.
    </p>
    <p>
        In this demo, the pivot table is shown with the virtualization option enabled through the <a target="_blank"
            href="https://ej2.syncfusion.com/vue/documentation/api/pivotview/#enablevirtualization"> enableVirtualization</a> property
        and an external server engine. This would improve pivot table rendering performance when working with large amounts of data.
    </p>
    <br />
    <p>
        <strong>Injecting Module:</strong>
    </p>
    <p>
        The pivot table features are segregated into individual modules. To use the virtual scrolling option, inject
        <code> VirtualScroll</code> module using the
        <code>provide</code> section.
    </p>
    <br />
    <p>
        More information about server-side aggregation can be found in this <a target="_blank"
            href="https://ej2.syncfusion.com/vue/documentation/pivotview/server-side-pivot-engine">
            documentation section</a>.
    </p>
</div>
</div>
</template>
<script lang="ts">
import { PivotViewComponent, IDataSet, VirtualScroll, FieldList, GroupingBar } from "@syncfusion/ej2-vue-pivotview";
import { extend, enableRipple, Browser } from '@syncfusion/ej2-base';
enableRipple(false);

/* tslint:disable */

export default {
  components: {
    'ejs-pivotview': PivotViewComponent
  },
  methods: {
    dataBound: function(args: any) {
      var pivotObj = ((this as any).$refs.pivotview).ej2Instances;
      if (Browser.isDevice && pivotObj && pivotObj.enableRtl && document.querySelector('.control-section')) {
          (<any>document.querySelector('.control-section')).classList.add('e-rtl');
      }
    },
  },
  data: () => {
    return {
      dataSourceSettings: {
            url: 'https://ej2services.syncfusion.com/production/web-services/api/pivot/post',
            mode: 'Server',
            expandAll: false,
            enableSorting: true,
            columns: [{ name: 'Year', caption: 'Production Year' },
            ],
            values: [
                { name: 'Sold', caption: 'Units Sold' },
                { name: 'Price', caption: 'Sold Amount' }
            ],
            rows: [{ name: 'ProductID', caption: 'Product ID' }],
            formatSettings: [{ name: 'Price', format: 'C0' }, { name: 'Sold', format: 'N0' }],
            filters: []
      },
      showFieldList: true,
      showGroupingBar: true,
      enableVirtualization: true,
      width: "100%",
      allowDataCompression: true,
      height: 450
    };
  },
  provide: {
    pivotview: [VirtualScroll, FieldList, GroupingBar]
  }
}
</script>

<style scoped>
/deep/ #pivotview {
  width: 100%;
}

/deep/ .sb-sample-content-area {
  min-height: 255px !important;
}
/deep/ .control-section {
  min-height: 255px !important;
}
</style>
