// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/source/diagram/remote-data.vue
﻿<template>

<div class="control-section">
  <ejs-diagram style='display:block' id="diagram" :width='width' :height='height' :getNodeDefaults='getNodeDefaults' :getConnectorDefaults='getConnectorDefaults' :snapSettings='snapSettings' :layout='layout' :dataSourceSettings='dataSourceSettings' :tool='tool'></ejs-diagram>
<div id="action-description">
    <p>
        This sample demonstrates binding remote data with the diagram using the Data Manager support.
    </p>
</div>
<div id="description">
    <p>
        This example shows how to generate a diagram from remote data such as REST APIs. The
        <code>dataSourceSettings</code> property can be used to map an external data source with the diagram control. The
        <code>id</code> property of
        <code>dataSourceSettings</code> can be used to define a unique field of an external data. The
        <code>parentId</code> property can be used to define the relationship between objects. The
        <code>dataManager</code> property can be used to fetch data from web services.
    </p>

    <p style="font-weight: 500">Injecting Module</p>
    <p>
        The diagram component’s features are segregated into individual feature-wise modules. To generate diagrams from an external
        data source, inject
        <code>DataBinding</code> module using
        <code>provide: { diagram: [LineSeries] }</code> method. To automatically arrange the objects in a hierarchical structure, inject
        <code>HierarchicalTree</code> module using
        <code>provide: { diagram: [HierarchicalTree] }</code> method.
    </p>
    <br>
</div>
</div>


</template>
<style scoped>
</style>
<script>
import {
  DiagramComponent,
  DataBinding,
  HierarchicalTree,
  DiagramTools
} from "@syncfusion/ej2-vue-diagrams";
import { DataManager } from "@syncfusion/ej2-data";

export default {
  components: {
    'ejs-diagram': DiagramComponent
  },
  data: function() {
    return {
      width: "100%",
      height: 490,
      //Configrues hierarchical tree layout
      layout: {
        type: "HierarchicalTree",
        margin: { left: 0, right: 0, top: 100, bottom: 0 },
        verticalSpacing: 40,
      },
      //Sets the default values of nodes
      getNodeDefaults: (node) => {
        node.width = 80;
        node.height = 40;
        //Initialize shape
        node.shape = { type: "Basic", shape: "Rectangle" };
        node.style = { fill: "#048785", strokeColor: "Transparent" };
      },
      //Sets the default values of connector
      getConnectorDefaults: (connector) => {
        connector.type = "Orthogonal";
        connector.style.strokeColor = "#048785";
        connector.targetDecorator.shape = "None";
      },
      //Configures data source
      dataSourceSettings: {
        id: "Id",
        parentId: "ParentId",
        dataSource: new DataManager(
          {
            url: "https://ej2services.syncfusion.com/production/web-services/api/RemoteData",
            crossDomain: true
          },
        ),
        //binds the external data with node
        doBinding: (nodeModel, data, diagram) => {
          nodeModel.annotations = [
            {
              /* tslint:disable:no-string-literal */
              content: data["Label"],
              style: { color: "white" }
            }
          ];
        }
      },
      //Disables all interactions except zoom/pan
      tool: DiagramTools.ZoomPan,
      snapSettings: { constraints: 0 }
    };
  },
  provide: {
    diagram: [DataBinding, HierarchicalTree]
  }
}

</script>

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Angular/source/diagram/remote-data.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import {
    Diagram, NodeModel, ConnectorModel, SnapConstraints,
    DataBinding, HierarchicalTree, DiagramTools,SnapSettingsModel
} from '@syncfusion/ej2-diagrams';
import { DataManager } from '@syncfusion/ej2-data';
import { SBDescriptionComponent } from '../common/dp.component';
import { DiagramModule } from '@syncfusion/ej2-angular-diagrams';
import { SBActionDescriptionComponent } from '../common/adp.component';
Diagram.Inject(DataBinding, HierarchicalTree);

export interface DataInfo {
    [key: string]: string;
}

/**
 * Remote Data binding sample
 */
@Component({
    selector: 'control-content',
    templateUrl: 'remote-data.html',
    styleUrls: ['diagram-style.css'],
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [SBActionDescriptionComponent, DiagramModule, SBDescriptionComponent]
})
export class RemoteDataDiagramComponent {
    // Default settings for nodes
    public nodeDefaults(node: NodeModel): NodeModel {
        node.width = 80;
        node.height = 40;
        //Initialize shape
        node.shape = { type: 'Basic', shape: 'Rectangle' };
        node.style = { fill: '#048785', strokeColor: 'Transparent' };
        return node;
    };
    // Data source and binding configuration
    public data: Object = {
        id: 'Id', parentId: 'ParentId',
        dataSource: new DataManager(
            { url: 'https://ej2services.syncfusion.com/production/web-services/api/RemoteData', crossDomain: true },
        ),
        //binds the external data with node
        doBinding: (nodeModel: NodeModel, data: DataInfo, diagram: Diagram) => {
            nodeModel.annotations = [{
                /* tslint:disable:no-string-literal */
                content: data['Label'],
                style: { color: 'white' }
            }];
        }
    };
    // Default settings for connectors
    public connDefaults(connector: ConnectorModel): void {
        connector.type = 'Orthogonal';
        connector.style.strokeColor = '#048785';
        connector.targetDecorator.shape = 'None';
    };
    // Enable zoom and pan tools for the diagram
    public tool: DiagramTools = DiagramTools.ZoomPan;
    // Disable all snap constraints by default
    public snapSettings: SnapSettingsModel = { constraints: SnapConstraints.None };
    // Configure the layout settings for the diagram
    public layout: Object = {
        type: 'HierarchicalTree', margin: { left: 0, right: 0, top: 100, bottom: 0 },
        verticalSpacing: 40,
    };
}
