// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/treegrid/loading-animation.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.LoadingAnimation = void 0;
var React = require("react");
var ej2_react_treegrid_1 = require("@syncfusion/ej2-react-treegrid");
var ej2_data_1 = require("@syncfusion/ej2-data");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var sample_base_1 = require("../common/sample-base");
var property_pane_1 = require("../common/property-pane");
var LoadingAnimation = /** @class */ (function (_super) {
    __extends(LoadingAnimation, _super);
    function LoadingAnimation() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.data = new ej2_data_1.DataManager({ url: 'https://ej2services.syncfusion.com/production/web-services/api/SelfReferenceData',
            adaptor: new ej2_data_1.WebApiAdaptor });
        _this.indicatortypes = [
            { id: 'Shimmer', name: 'Shimmer' },
            { id: 'Spinner', name: 'Spinner' }
        ];
        _this.fields = { text: 'name', value: 'id' };
        return _this;
    }
    LoadingAnimation.prototype.indicatorChange = function (e) {
        if (this.indicatorDropDown.value === 'Shimmer') {
            this.treegridInstance.loadingIndicator.indicatorType = 'Shimmer';
        }
        else {
            this.treegridInstance.loadingIndicator.indicatorType = 'Spinner';
        }
        this.treegridInstance.refresh();
    };
    ;
    LoadingAnimation.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section' },
                React.createElement("div", { className: 'col-md-9' },
                    React.createElement(ej2_react_treegrid_1.TreeGridComponent, { id: "TreeGrid", dataSource: this.data, ref: function (treegrid) { return _this.treegridInstance = treegrid; }, hasChildMapping: 'isParent', height: '400', pageSettings: { pageCount: 3 }, treeColumnIndex: 1, allowPaging: true, idMapping: 'TaskID', parentIdMapping: 'parentItem', loadingIndicator: { indicatorType: 'Shimmer' }, allowSorting: true },
                        React.createElement(ej2_react_treegrid_1.ColumnsDirective, null,
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'TaskID', headerText: 'Task ID', width: '120', textAlign: 'Right' }),
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'TaskName', headerText: 'Task Name', width: '240' }),
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'StartDate', headerText: 'Start Date', width: '140', format: 'yMd', textAlign: 'Right' }),
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'Duration', headerText: 'Duration', width: '130', textAlign: 'Right' }),
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'Progress', headerText: 'Progress', width: '130' })),
                        React.createElement(ej2_react_treegrid_1.Inject, { services: [ej2_react_treegrid_1.Page, ej2_react_treegrid_1.Sort] }))),
                React.createElement("div", { className: 'col-md-3 property-section' },
                    React.createElement(property_pane_1.PropertyPane, { title: 'Properties' },
                        React.createElement("table", { id: 'property', title: 'Properties', className: 'property-panel-table', style: { width: '100%' } },
                            React.createElement("tbody", null,
                                React.createElement("tr", { style: { height: '50px' } },
                                    React.createElement("td", null,
                                        React.createElement("div", null, " Indicator Type ")),
                                    React.createElement("td", { style: { width: '70%' } },
                                        React.createElement("div", { id: 'columnddl' },
                                            React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { dataSource: this.indicatortypes, value: "Shimmer", change: this.indicatorChange.bind(this), fields: this.fields, width: "130px", ref: function (indicateDropDown) { _this.indicatorDropDown = indicateDropDown; } }))))))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample shows the loading indicator while tree grid loading and refreshing especially when using remote data. In this sample, you can change the loading indicators from the properties panel.")),
            React.createElement("div", { id: 'description' },
                React.createElement("p", null, "When performing the tree grid actions (like sorting, filtering, and more), the loading indicator is shown in the in-between time the processed data is fetched and bound to the tree grid."),
                React.createElement("p", null, "The Tree Grid supports the following loading indicator types. They are: "),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("code", null, "Spinner")),
                    React.createElement("li", null,
                        React.createElement("code", null, "Shimmer"))),
                React.createElement("p", null,
                    "Use the loading indicator by setting the ",
                    React.createElement("code", null,
                        React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/api/treegrid/#loadingindicator" }, "loadingIndicator.indicatorType")),
                    " property as ",
                    React.createElement("code", null, "Spinner"),
                    " or ",
                    React.createElement("code", null, "Shimmer"),
                    ". The default value of the indicatorType is ",
                    React.createElement("code", null, "Spinner"),
                    ". In this demo, the ",
                    React.createElement("code", null, "Shimmer"),
                    " type is initially enabled."))));
    };
    return LoadingAnimation;
}(sample_base_1.SampleBase));
exports.LoadingAnimation = LoadingAnimation;

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/src/tree-grid/loading-animation.vue
<template>
<div class="control-section">
<div class="col-md-9 control-section">
    <ejs-treegrid ref='treegrid' :dataSource='data' idMapping='TaskID' :height='400' parentIdMapping='parentItem' hasChildMapping='isParent' :treeColumnIndex='1' :allowPaging='true' :allowSorting='true' :pageSettings='pageSettings' :loadingIndicator='loadingIndicator'>
        <e-columns>
            <e-column field='TaskID' headerText='Task ID' width='120' textAlign='Right'></e-column>
            <e-column field='TaskName' headerText='Task Name' width='240'></e-column>
            <e-column field='StartDate' headerText='Start Date' width='140' format="yMd" textAlign='Right'></e-column>
            <e-column field='Duration' headerText='Duration' width='130' textAlign='Right'></e-column>
            <e-column field='Progress' headerText='Progress' width='130'></e-column>
        </e-columns>
    </ejs-treegrid>
</div>

<div class="col-lg-3 property-section">
    <table id="property" title="Properties" style="width: 100%;">
        <colgroup>
             <col span="1" style="width: 40%;">
             <col span="1" style="width: 60%;">
          </colgroup>
          <tbody>
        <tr style="height: 50px">
            <td>
                <div >Indicator Type</div>
            </td>
            <td>
            <div id='dropdownindicator' style="padding-left:10%">
              <ejs-dropdownlist ref='dropdown' id='dropdown' :dataSource='indicatortypes' index=0 :fields='fields' :change="indicatorChange" width="130" ></ejs-dropdownlist>
             </div>                                 
            </td>
        </tr>
        </tbody>
    </table>
</div>  
    
<div id="action-description">
    <p>This sample shows the loading indicator while tree grid loading and refreshing especially when using remote data. In this sample, you can change the loading indicators from the properties panel.
    </p>
</div>

<div id="description">
     <p>
       The Tree Grid has an option to show a loading indicator in-between the time of fetching the data and binding it to the tree grid during initial rendering or refreshing or after performing any tree grid action like sorting, filtering, and more.
    </p>
    <p>The Tree Grid supports the following loading indicator types. They are: </p>
        <ul>
            <li><code>Spinner</code></li>
            <li><code>Shimmer</code></li>
        </ul>
    <p>Use the loading indicator by setting the <code><a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/treegrid/#loadingindicator">
    loadingIndicator.indicatorType</a></code> property as <code>Spinner</code> or <code>Shimmer</code>. The default value of the indicatorType is <code>Spinner</code>. In this demo, the <code>Shimmer</code> type is initially enabled.
    </p>
</div>
</div>  
</template>

<!-- custom code start -->
<style scoped>
    #control-container {
        padding: 0px !important;
    }
</style>
<!-- custom code end -->

<script lang="ts">
import { TreeGridComponent, ColumnDirective, ColumnsDirective, Page, Sort } from "@syncfusion/ej2-vue-treegrid";
import { DataManager, WebApiAdaptor } from "@syncfusion/ej2-data";
import { DropDownListComponent, ChangeEventArgs } from '@syncfusion/ej2-vue-dropdowns';

export default {
  components: {
    'ejs-treegrid': TreeGridComponent,
    'e-column': ColumnDirective,
    'e-columns': ColumnsDirective,
    'ejs-dropdownlist': DropDownListComponent
  },  
  data: () => {
    return {
      data: new DataManager({
        url: "https://ej2services.syncfusion.com/production/web-services/api/SelfReferenceData",
        adaptor: new WebApiAdaptor()
      }),
      pageSettings: { pageCount: 3 },
      loadingIndicator: { indicatorType: 'Shimmer' },
      fields: { text: 'name', value: 'id' },
      indicatortypes: [
          { id: 'Shimmer', name: 'Shimmer' },
	      { id: 'Spinner', name: 'Spinner' }
	  ]
    };
  },
  methods: {
    indicatorChange: function(e: ChangeEventArgs): void {
        if (((this as any).$refs.dropdown).ej2Instances.value === "Shimmer") {
            ((this as any).$refs.treegrid).ej2Instances.loadingIndicator.indicatorType = 'Shimmer';
	    ((this as any).$refs.treegrid).ej2Instances.refresh();
        } else {
            ((this as any).$refs.treegrid).ej2Instances.loadingIndicator.indicatorType = 'Spinner';
	    ((this as any).$refs.treegrid).ej2Instances.refresh();
        }
    }
  },
  provide: {
      treegrid: [Page, Sort]
  }
}
</script>
