// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/pdfviewer/redaction.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Redaction = void 0;
var React = require("react");
var ej2_react_pdfviewer_1 = require("@syncfusion/ej2-react-pdfviewer");
var ej2_react_navigations_1 = require("@syncfusion/ej2-react-navigations");
var sample_base_1 = require("../common/sample-base");
var ej2_react_buttons_1 = require("@syncfusion/ej2-react-buttons");
require("./pdf.component.css");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var ej2_react_popups_1 = require("@syncfusion/ej2-react-popups");
var ej2_react_inputs_1 = require("@syncfusion/ej2-react-inputs");
var viewer;
var Redaction = /** @class */ (function (_super) {
    __extends(Redaction, _super);
    function Redaction(props) {
        var _this_1 = _super.call(this, props) || this;
        _this_1.currentPageNumber = '1';
        _this_1.fileName = 'programmatical-annotations.pdf';
        _this_1.redactionCount = 0;
        _this_1.asyncSettings = {
            saveUrl: 'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Save',
            removeUrl: 'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Remove'
        };
        _this_1.dropAreaRef = document.getElementsByClassName('drop-area-wrap')[0];
        _this_1.allowedExtensions = '.png, .jpg, .jpeg';
        _this_1.url = "https://ej2services.syncfusion.com/production/web-services/api/pdfviewer/Redaction";
        //To update page number when page has been changed
        _this_1.onPageChange = function () {
            _this_1.currentPageNumber = viewer.currentPageNumber.toString();
            document.getElementById('e-pv-redact-sb-currentPage').textContent = _this_1.viewer.currentPageNumber.toString() + ' ';
            _this_1.updatePageNavigation.bind(_this_1);
        };
        //Updating the total number of pages while loading
        _this_1.documentLoaded = function () {
            _this_1.viewer = document.getElementById('container').ej2_instances[0];
            var pageCount = document.getElementById('e-pv-redact-sb-totalPage');
            pageCount.textContent = '/ ' + viewer.pageCount;
            (document.getElementById('e-pv-redact-sb-currentPage')).textContent = _this_1.viewer.currentPageNumber.toString();
            _this_1.updatePageNavigation();
            _this_1.updateRedaction();
        };
        //To update page number when the previous and next button is clicked
        _this_1.updatePageNavigation = function () {
            if (_this_1.viewer.currentPageNumber === 1) {
                _this_1.toolbar.enableItems(document.getElementById('previousPage').parentElement, false);
                _this_1.toolbar.enableItems(document.getElementById('nextPage').parentElement, true);
            }
            else if (viewer.currentPageNumber === viewer.pageCount) {
                _this_1.toolbar.enableItems(document.getElementById('previousPage').parentElement, true);
                _this_1.toolbar.enableItems(document.getElementById('nextPage').parentElement, false);
            }
            else {
                _this_1.toolbar.enableItems(document.getElementById('previousPage').parentElement, true);
                _this_1.toolbar.enableItems(document.getElementById('nextPage').parentElement, true);
            }
        };
        //To update the redaction count
        _this_1.updateRedaction = function () {
            if (_this_1.redactionCount <= 0) {
                _this_1.toolbar.enableItems(document.getElementById('redacticon').parentElement, false);
            }
            else {
                _this_1.toolbar.enableItems(document.getElementById('redacticon').parentElement, true);
            }
        };
        //Updating the number of redaction while the annotation has been added
        _this_1.annotationAdd = function (e) {
            var pdfAnnotationList = new Array();
            pdfAnnotationList = _this_1.viewer.annotationCollection;
            var selectedAnnotationIndex = pdfAnnotationList.findIndex(function (item) { return item.annotationId == e.annotationId; });
            if (selectedAnnotationIndex != -1) {
                _this_1.annotation = pdfAnnotationList[selectedAnnotationIndex];
            }
            if (_this_1.annotation.author == "Redaction" || _this_1.annotation.customStampName == "Image" || _this_1.annotation.author == "Pattern" || _this_1.annotation.author == "Text") {
                _this_1.redactionCount = _this_1.redactionCount + 1;
                _this_1.updateRedaction();
            }
        };
        //Updating the number of redaction while the annotation has been removed
        _this_1.annotationRemove = function () {
            if (_this_1.annotation.author == "Redaction" || _this_1.annotation.customStampName == "Image" || _this_1.annotation.author == "Pattern" || _this_1.annotation.author == "Text") {
                _this_1.redactionCount = _this_1.redactionCount - 1;
                _this_1.updateRedaction();
            }
        };
        _this_1.downloadDocument = function (blobUrl) {
            var Url = URL || webkitURL;
            blobUrl = Url.createObjectURL(blobUrl);
            viewer.fileName = _this_1.fileName;
            var anchorElement = document.createElement('a');
            if (anchorElement.click) {
                anchorElement.href = blobUrl;
                anchorElement.target = '_parent';
                if ('download' in anchorElement) {
                    var downloadFileName = viewer.fileName || 'downloadedFile.pdf';
                    if (downloadFileName) {
                        if (downloadFileName.endsWith('.pdf')) {
                            anchorElement.download = downloadFileName;
                        }
                        else {
                            var splitPdf = downloadFileName.split('.pdf')[0] + '.pdf';
                            anchorElement.download = splitPdf;
                        }
                    }
                    else {
                        anchorElement.download = 'Default.pdf';
                    }
                }
                (document.body || document.documentElement).appendChild(anchorElement);
                anchorElement.click();
            }
            else {
                if (window.top === window &&
                    blobUrl.split('#')[0] === window.location.href.split('#')[0]) {
                    var padCharacter = blobUrl.indexOf('?') === -1 ? '?' : '&';
                    blobUrl = blobUrl.replace(/#|$/, padCharacter + '$&');
                }
                window.open(blobUrl, '_parent');
            }
        };
        //To download the redacted pdf
        _this_1.download = function () {
            var _this = _this_1;
            viewer.saveAsBlob().then(function (value) {
                var reader = new FileReader();
                reader.readAsDataURL(value);
                reader.onload = function (e) {
                    var _a;
                    var base64String = (_a = e.target) === null || _a === void 0 ? void 0 : _a.result;
                    var xhr = new XMLHttpRequest();
                    xhr.open('POST', _this.url, true);
                    xhr.setRequestHeader('Content-type', 'application/json; charset=UTF-8');
                    var requestData = JSON.stringify({ base64String: base64String });
                    xhr.onload = function () {
                        if (xhr.status === 200) {
                            var blobUrl = _this.createBlobUrl(xhr.responseText.split('base64,')[1], 'application/pdf');
                            _this.downloadDocument(blobUrl);
                        }
                        else {
                            console.error('Download failed:', xhr.statusText);
                        }
                    };
                    xhr.onerror = function () {
                        console.error('An error occurred during the download:', xhr.statusText);
                    };
                    xhr.send(requestData);
                };
            }).catch(function (error) {
                console.error('Error saving Blob:', error);
            });
        };
        _this_1.createBlobUrl = function (base64String, contentType) {
            var sliceSize = 512;
            var byteCharacters = atob(base64String);
            var byteArrays = [];
            for (var offset = 0; offset < byteCharacters.length; offset += sliceSize) {
                var slice = byteCharacters.slice(offset, offset + sliceSize);
                var byteNumbers = new Array(slice.length);
                for (var i = 0; i < slice.length; i++) {
                    byteNumbers[parseInt(i.toString(), 10)] = slice.charCodeAt(i);
                }
                var byteArray = new Uint8Array(byteNumbers);
                byteArrays.push(byteArray);
            }
            var blob = new Blob(byteArrays, { type: contentType });
            return blob;
        };
        _this_1.uploadObj = React.createRef();
        return _this_1;
    }
    Redaction.prototype.componentDidMount = function () {
        viewer = document.getElementById('container').ej2_instances[0];
    };
    Redaction.prototype.render = function () {
        var _this_1 = this;
        var data = ['10%', '25%', '50%', '75%', '100%', '200%', '400%'];
        function template() {
            return (React.createElement("div", null,
                React.createElement("span", { id: "e-pv-redact-sb-currentPage", title: "Current Page" }, "1 "),
                React.createElement("span", { id: "e-pv-redact-sb-totalPage", title: "Total Page" }, "/ 1")));
        }
        var clickHandler = function (args) {
            switch (args.item.id) {
                case 'pdfviewer_open':
                    {
                        var fileUpload = document.getElementById('fileUpload');
                        fileUpload.click();
                        break;
                    }
                case 'text_annot':
                    {
                        this.viewer.rectangleSettings.fillColor = '#a3a2a0';
                        this.viewer.rectangleSettings.strokeColor = '#a3a2a0';
                        this.viewer.rectangleSettings.author = 'Text';
                        this.viewer.annotation.setAnnotationMode('Rectangle');
                        break;
                    }
                case 'image_annot':
                    {
                        this.dialogInstance.show();
                        break;
                    }
                case 'pattern_annot':
                    {
                        this.viewer.rectangleSettings.fillColor = '#dedfe0';
                        this.viewer.rectangleSettings.strokeColor = '#dedfe0';
                        this.viewer.rectangleSettings.author = 'Pattern';
                        this.viewer.annotation.setAnnotationMode('Rectangle');
                        break;
                    }
                case 'black_annot':
                    {
                        this.viewer.rectangleSettings.fillColor = '#000000';
                        this.viewer.rectangleSettings.strokeColor = '#000000';
                        this.viewer.rectangleSettings.author = 'Redaction';
                        this.viewer.annotation.setAnnotationMode('Rectangle');
                        break;
                    }
                case 'white_annot':
                    {
                        this.viewer.rectangleSettings.fillColor = '#ffffff';
                        this.viewer.rectangleSettings.strokeColor = '#ffffff';
                        this.viewer.rectangleSettings.author = 'Redaction';
                        this.viewer.annotation.setAnnotationMode('Rectangle');
                        break;
                    }
                case 'previousPage':
                    {
                        viewer.navigation.goToPreviousPage();
                        break;
                    }
                case 'nextPage':
                    {
                        viewer.navigation.goToNextPage();
                        break;
                    }
                case 'redacticon':
                    {
                        if (this.redactionCount > 0) {
                            var _this_2 = this;
                            viewer.saveAsBlob().then(function (value) {
                                var data = value;
                                var reader = new FileReader();
                                reader.readAsDataURL(data);
                                reader.onload = function (e) {
                                    var _a;
                                    var base64String = (_a = e.target) === null || _a === void 0 ? void 0 : _a.result;
                                    var xhr = new XMLHttpRequest();
                                    xhr.open('POST', _this_2.url, true);
                                    xhr.setRequestHeader('Content-type', 'application/json; charset=UTF-8');
                                    var requestData = JSON.stringify({ base64String: base64String });
                                    xhr.onload = function () {
                                        if (xhr.status === 200) {
                                            viewer.load(xhr.responseText, null);
                                        }
                                        else {
                                            console.error('Redaction failed:', xhr.statusText);
                                        }
                                    };
                                    xhr.onerror = function () {
                                        console.error('An error occurred during the redaction:', xhr.statusText);
                                    };
                                    xhr.send(requestData);
                                };
                            });
                            this.redactionCount = 0;
                            this.updateRedaction();
                        }
                        break;
                    }
            }
        };
        //To get the header in upload image dialog box
        var header = function () {
            return (React.createElement("div", null,
                React.createElement("div", { id: "dlg-template", title: "Upload image", className: "e-icon-settings" }, "Upload Image")));
        };
        //When the cancel button is clicked
        var CloseDialog = function () {
            this.dialogInstance.hide();
        };
        //To get the footer content in upload image dialog box
        var footerTemplate = function () {
            return (React.createElement("div", null,
                React.createElement("button", { id: "cancelButton", className: "e-control e-btn e-primary", "data-ripple": "true", onClick: CloseDialog.bind(_this_1) }, "Cancel")));
        };
        //To get the content of dialog box
        var contentTemplate = function () {
            return (React.createElement("div", { id: 'dialog' },
                React.createElement("div", { id: 'e-pv-redact-sb-defaultfileupload' },
                    React.createElement("div", { className: "drop-area-wrap", id: 'e-pv-redact-sb-drop-area-wrap' },
                        React.createElement("div", null,
                            React.createElement(ej2_react_inputs_1.UploaderComponent, { id: 'fileupload', type: 'file', ref: function (scope) { _this_1.uploadObj.current = scope; }, asyncSettings: _this_1.asyncSettings, change: onFileChange.bind(_this_1), dropArea: _this_1.dropAreaRef, allowedExtensions: _this_1.allowedExtensions })),
                        React.createElement("div", null, "(Only JPG and PNG images will be accepted)")),
                    React.createElement("div", { className: "e-pv-redact-sb-image-list" },
                        React.createElement("div", { id: 'imageContainer', className: "e-pv-redact-sb-image-container" },
                            React.createElement("img", { id: 'imageView', className: "e-pv-redact-sb-image-source", style: { 'display': 'none' } }))))));
        };
        //When the zoom dropdown is changed
        var zoomValueChange = function (args) {
            var zoom = (args).value;
            var previousZoom = (args).previousItemData.value;
            if (zoom !== null || previousZoom !== null) {
                var zoomchange = parseInt(zoom.replace("%", ""), 10);
                viewer.magnificationModule.zoomTo(zoomchange);
            }
        };
        //To display the zoom percentage dropdown
        var dropDown = function () {
            return (React.createElement("div", null,
                React.createElement(ej2_react_dropdowns_1.ComboBoxComponent, { width: 88, popupWidth: 80, value: '100%', dataSource: data, showClearButton: false, change: zoomValueChange.bind(this) })));
        };
        var imageSrc;
        var customStampSource;
        var onFileChange = function (args) {
            var file = args.file[0].rawFile;
            var imageElement = document.getElementById('imageView');
            var imageElementContainer = document.getElementById('imageContainer');
            var reader = new FileReader();
            var _this = this;
            reader.onload = function (e) {
                var base64String = e.target ? e.target.result : null;
                imageSrc = base64String;
                customStampSource = imageSrc;
                (imageElement).src = imageSrc;
                imageElementContainer.className =
                    'image-container image-container-selected';
                (imageElement).style.display = 'block';
                // Bind click event to the image element
                imageElement.addEventListener('click', handleImageClick.bind(_this));
            };
            reader.readAsDataURL(file);
        };
        var handleImageClick = function () {
            customStampSource = imageSrc;
            this.dialogInstance.hide();
            addImage();
        };
        //To add the image in pdf
        var addImage = function () {
            viewer.stampSettings.author = "Image";
            viewer.customStampSettings = {
                width: 200,
                author: 'Image',
                height: 125,
                isAddToMenu: false,
                enableCustomStamp: false
            };
            viewer.customStamp = [
                {
                    customStampName: 'Image',
                    customStampImageSource: customStampSource
                },
            ];
        };
        return (React.createElement("div", null,
            React.createElement("div", { className: "control-section", id: 'e-pv-redact-sb-panel' },
                React.createElement("div", { className: "flex-container", id: "e-pv-redact-sb-flexContainer" }),
                React.createElement("div", { className: 'control-container' },
                    React.createElement(ej2_react_navigations_1.AppBarComponent, { colorMode: "Primary" },
                        React.createElement("span", { className: "regular" }, "Redaction"),
                        React.createElement("div", { className: "e-appbar-spacer" }),
                        React.createElement(ej2_react_buttons_1.ButtonComponent, { cssClass: 'e-inherit ', iconCss: 'e-icons e-download e-btn-icon e-icon-left', id: 'download_pdf', onClick: this.download }, "Download"))),
                React.createElement("div", { className: 'primaryToolbar', id: 'toolbar_default' },
                    React.createElement(ej2_react_navigations_1.ToolbarComponent, { ref: function (scope) { _this_1.primaryToolbar = scope; }, clicked: clickHandler.bind(this), id: 'e-pv-redact-sb-toolbar' },
                        React.createElement(ej2_react_navigations_1.ItemsDirective, null,
                            React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: 'e-icon e-folder', tooltipText: 'Open', cssClass: 'e-pv-redact-sb-open-container', id: 'pdfviewer_open', text: 'Open' }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { type: 'Separator' }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: 'e-icon e-text-annotation', tooltipText: 'Text', cssClass: 'e-pv-redact-sb-font-container', text: 'Text', id: 'text_annot' }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: 'e-icons e-image', tooltipText: 'Image', cssClass: 'e-pv-redact-sb-image-container', text: 'Image', id: 'image_annot' }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: 'e-icons e-opacity', tooltipText: 'Pattern', cssClass: 'e-pv-redact-sb-pattern-container', text: 'Pattern', id: 'pattern_annot' }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: 'e-icons black-out', tooltipText: 'Blackout', cssClass: 'e-pv-redact-sb-black-out-container', text: 'Blackout', id: 'black_annot' }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: 'e-icons white-out', tooltipText: 'Whiteout', cssClass: 'e-pv-redact-sb-white-out-container', text: 'Whiteout', id: 'white_annot' }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { type: 'Separator' }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: 'e-icons e-redact', tooltipText: 'Redaction', cssClass: 'e-pv-redact-sb-redaction-container', text: 'Redact', id: 'redacticon', disabled: true })))),
                React.createElement("div", { className: 'e-pv-redact-sb-secondary-toolbar', id: 'toolbar_secondary' },
                    React.createElement(ej2_react_navigations_1.ToolbarComponent, { ref: function (scope) { _this_1.toolbar = scope; }, clicked: clickHandler.bind(this), id: 'e-pv-redact-sb-toolbar-secondary' },
                        React.createElement(ej2_react_navigations_1.ItemsDirective, null,
                            React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: 'e-icons e-chevron-left', cssClass: 'e-pv-redact-sb-previous-container', tooltipText: "Previous Page", id: 'previousPage', disabled: true }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { template: template, tooltipText: "Page Number" }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: 'e-icon e-chevron-right', cssClass: 'e-pv-redact-sb-next-container', tooltipText: "Next Page", id: 'nextPage', disabled: true }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { cssClass: 'percentage', type: "Input", tooltipText: "Zoom", template: dropDown, align: "Left" })))),
                React.createElement("div", { id: "targetDialog", className: "dialog-element" },
                    React.createElement(ej2_react_popups_1.DialogComponent, { header: header, footerTemplate: footerTemplate, content: contentTemplate, showCloseIcon: true, target: "#targetDialog", width: '437px', height: '255px', visible: false, isModal: true, ref: function (scope) { _this_1.dialogInstance = scope; }, id: 'e-pv-redact-sb-dialog' })),
                React.createElement(ej2_react_pdfviewer_1.PdfViewerComponent, { ref: function (scope) { _this_1.viewer = scope; }, id: "container", documentPath: "https://cdn.syncfusion.com/content/pdf/programmatical-annotations.pdf", resourceUrl: "https://cdn.syncfusion.com/ej2/27.1.55/dist/ej2-pdfviewer-lib", style: { 'height': '640px' }, enableToolbar: false, enableNavigationToolbar: false, enableAnnotationToolbar: false, enableCommentPanel: false, documentLoad: this.documentLoaded, pageChange: this.onPageChange, annotationAdd: this.annotationAdd, annotationRemove: this.annotationRemove },
                    React.createElement(ej2_react_pdfviewer_1.Inject, { services: [ej2_react_pdfviewer_1.Toolbar, ej2_react_pdfviewer_1.Magnification, ej2_react_pdfviewer_1.Navigation, ej2_react_pdfviewer_1.LinkAnnotation, ej2_react_pdfviewer_1.BookmarkView, ej2_react_pdfviewer_1.ThumbnailView, ej2_react_pdfviewer_1.Print, ej2_react_pdfviewer_1.TextSelection, ej2_react_pdfviewer_1.TextSearch, ej2_react_pdfviewer_1.Annotation, ej2_react_pdfviewer_1.FormFields, ej2_react_pdfviewer_1.FormDesigner, ej2_react_pdfviewer_1.PageOrganizer] })),
                React.createElement("input", { type: "file", id: "fileUpload", accept: ".pdf", onChange: this.readFile.bind(this), style: { 'display': 'block', 'visibility': 'hidden', 'width': '0', 'height': '0' } })),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null,
                    " The PDF Viewer facilitates the permanent removal of sensitive or confidential data from PDF files. Simplifying the redaction process, Syncfusion\u2019s ",
                    React.createElement("a", { target: '_blank', href: 'https://www.syncfusion.com/document-processing/pdf-framework/net/pdf-library', "aria-label": "Navigate to the Redaction Documendation in PDF library" }, ".NET PDF library"),
                    " includes features for seamless implementation. ")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    " This example showcases the implementation of redaction using rectangle annotation, leveraging the Redaction feature in ",
                    React.createElement("a", { target: '_blank', href: 'https://help.syncfusion.com/file-formats/pdf/working-with-redaction', "aria-label": "Navigate to the Redaction Documendation by pdf viewer Library" }, "File formats"),
                    "."),
                React.createElement("br", null),
                React.createElement("p", null, "Various types of redactions are demonstrated: "),
                React.createElement("br", null),
                React.createElement("ul", null,
                    React.createElement("li", null, "Displaying text over the redacted area"),
                    React.createElement("li", null, "Adding an image to the redacted area"),
                    React.createElement("li", null, "Drawing patterns on the redacted area"),
                    React.createElement("li", null, "Blacking out the redacted area"),
                    React.createElement("li", null, "Whitening out the redacted area")),
                React.createElement("br", null),
                React.createElement("p", null, " Upon selecting areas on a page or across different pages with different redaction options, users can click the `Redact button`. This action redacts the document and reloads it into the PDF Viewer. The redacted document can then be saved or downloaded. "),
                React.createElement("p", null,
                    "More information on adding annotation programmatically can be found in this ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/introduction" }, " documentation section"),
                    "."))));
    };
    //To read the file when loaded
    Redaction.prototype.readFile = function (evt) {
        var proxy = this;
        var uploadedFiles = evt.target.files;
        var uploadedFile = uploadedFiles[0];
        this.fileName = uploadedFile.name;
        var reader = new FileReader();
        reader.readAsDataURL(uploadedFile);
        reader.onload = function (e) {
            var uploadedFileUrl = e.currentTarget.result;
            viewer.documentPath = uploadedFileUrl;
            viewer.fileName = proxy.fileName;
            viewer.downloadFileName = proxy.fileName;
        };
    };
    return Redaction;
}(sample_base_1.SampleBase));
exports.Redaction = Redaction;

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/src/pdfviewer/redaction.vue
﻿<template>
    <div>
        <div class="control-section" id="e-pv-redact-sb-panel">
            <div class="content-wrapper">
                <div class="flex-container" id="e-pv-redact-sb-flexContainer">
                </div>
                <ejs-appbar colorMode="Primary">
                    <span class="regular" style="margin:0 5px">Redaction</span>
                    <div class="e-appbar-spacer"></div>
                    <ejs-button cssClass="e-inherit" iconCss='e-icons e-download e-btn-icon e-icon-left' @click="downloadClicked">Download</ejs-button>
                </ejs-appbar>

                <div id="toolbar_default">
                    <ejs-toolbar id="e-pv-redact-sb-toolbar" ref='primaryToolbar'>
                        <e-items>
                            <e-item prefixIcon="e-icon e-folder" :click='openClicked' tooltipText="Open" id="pdfviewer_open" cssClass='e-pv-redact-sb-open-container' text="Open"></e-item>
                            <e-item type="Separator" tooltipText="separator" id="separator1"></e-item>
                            <e-item prefixIcon="e-icon e-text-annotation" :click='addText' tooltipText="Text" cssClass='e-pv-redact-sb-font-container' text="Text"></e-item>
                            <e-item prefixIcon="e-icons e-image" v-if="ShowBtn" :click="imgClick" tooltipText="Image" id="targetButton" cssClass='e-pv-redact-sb-image-btn' text="Image"></e-item>
                            <e-item prefixIcon="e-icons e-opacity" :click='addPattern' tooltipText="Pattern" cssClass='e-pv-redact-sb-pattern-container' text="Pattern"></e-item>
                            <e-item prefixIcon="e-icons black-out" :click='addBlackout' tooltipText="Black out" cssClass='e-pv-redact-sb-black-out-container' text="Blackout"></e-item>
                            <e-item prefixIcon="e-icons white-out" :click='addWhiteout' tooltipText="White Out" cssClass='e-pv-redact-sb-white-out-container' text="Whiteout"></e-item>
                            <e-item type="Separator"></e-item>
                            <e-item prefixIcon="e-icons e-redact" :click='redaction' id="redacticon" tooltipText="Redaction" cssClass='e-pv-redact-sb-redaction-container' text="Redact" disabled=true></e-item>
                        </e-items>
                    </ejs-toolbar>
                    <input type="file" id="documentUpload" accept=".pdf" style="display:block;visibility:hidden;width:0;height:0;"></input>
                </div>
            </div>
            <div class="e-pv-redact-sb-secondary-toolbar" id="toolbar_secondary">
                <ejs-toolbar id="secondary-toolbar" ref='secondaryToolbar'>
                    <e-items>
                        <e-item prefixIcon="e-icon e-chevron-left" :click='previousClicked' id="previousPage" tooltipText="Previous Page" cssClass='e-pv-redact-sb-previous-container' disabled=true></e-item>
                        <e-item :template="'currentPageTemplate'" cssClass="page-count"></e-item>
                        <template v-slot:currentPageTemplate>
                            <div><span id="current-page" title="Current Page">1 </span><span id="total-page" title="Total Page">/ 1</span></div>
                        </template>
                        <e-item prefixIcon="e-icon e-chevron-right" :click='nextClicked' tooltipText="Next Page" id="nextPage" cssClass='e-pv-redact-sb-next-container' disabled=true></e-item>
                        <e-item type="Separator"></e-item>
                        <e-item :template="'ComboTemplate'" cssClass="percentage" tooltipText="Zoom"></e-item>
                        <template v-slot:ComboTemplate>
                            <ejs-combobox width="90px" popupWidth="85px" value="100%" :showClearButton=false :dataSource="zoomList" :change='zoomValueChange'></ejs-combobox>
                        </template>
                    </e-items>
                </ejs-toolbar>
            </div>
            <ejs-pdfviewer id="pdfViewer" ref="pdfviewer" :resourceUrl="resourceUrl" :documentLoad="documentLoad" :documentPath="documentPath" :enableToolbar="enableToolbar" :enableAnnotationToolbar="enableAnnotationToolbar" :enableCommentPanel="enableCommentPanel"
            :enableNavigationToolbar="enableNavigationToolbar" :pageChange="pageChange" :annotationAdd="annotationAdd" :annotationRemove="annotationRemove">
            </ejs-pdfviewer>
            <div id='dialog'>
                <ejs-dialog :header="'headerTemplate'" id="e-pv-redact-sb-dialog" ref="dialogObj" :buttons='dlgButtons' :content="'contentTemplate'" :animationSettings='animationSettings' showCloseIcon='true' :target='target' width='477px' :open="dialogOpen" :visible="dialogVisible"
                isModal='true' minHeight='485px'>
                    <template v-slot:headerTemplate>
                        <span id="container">
                  <div id="dlg-template" title="UploadImage" class="e-icon-settings"> Upload Image </div>
              </span>
                    </template>
                    <template v-slot:contentTemplate>
                        <div id='e-pv-redact-sb-defaultfileupload'>
                            <div class="drop-area-wrap" id='e-pv-redact-sb-drop-area-wrap'>
                                <div>
                                    <ejs-uploader ref="uploadObj" :asyncSettings="path" :allowedExtensions="extentions" :change="onFileChange" :multiple=false></ejs-uploader>
                                </div>
                                <div>
                                    (Only JPG and PNG images will be accepted)
                                </div>
                            </div>
                            <div class="e-pv-redact-sb-image-list">
                                <div id='imageContainer' ref='imgContainer' class="e-pv-redact-sb-image-container" style="display:none">
                                    <img id='imageView' ref='imgTag' class="e-pv-redact-sb-image-source">
                                </div>
                            </div>
                        </div>
                    </template>
                </ejs-dialog>
            </div>
        </div>


        <div id="action-description">
            <p> The PDF Viewer facilitates the permanent removal of sensitive or confidential data from PDF files. Simplifying the redaction process, Syncfusion’s <a target='_blank' href='https://www.syncfusion.com/document-processing/pdf-framework/net/pdf-library'
                aria-label="Navigate to the Redaction Documendation in PDF library">.NET PDF library</a> includes features for seamless implementation. </p>
        </div>

        <div id="description">
            <p> This example showcases the implementation of redaction using rectangle annotation, leveraging the Redaction feature in <a target='_blank' href='https://help.syncfusion.com/file-formats/pdf/working-with-redaction' aria-label="Navigate to the Redaction Documendation by pdf viewer Library">File formats</a>.</p>
            <p>Various types of redactions are demonstrated: </p>
            <ul>
                <li>Displaying text over the redacted area</li>
                <li>Adding an image to the redacted area</li>
                <li>Drawing patterns on the redacted area</li>
                <li>Blacking out the redacted area</li>
                <li>Whitening out the redacted area</li>

            </ul>
            <p> Upon selecting areas on a page or across different pages with different redaction options, users can click the `Redact button`. This action redacts the document and reloads it into the PDF Viewer. The redacted document can then be saved or
                downloaded. </p>
            <p>
                More information on adding annotation programmatically can be found in this
                <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/pdfviewer/getting-started">
            documentation section</a>.
            </p>
        </div>
    </div>
</template>

<script>
  import { PdfViewerComponent, Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, 
           ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormDesigner, FormFields, PageOrganizer } from '@syncfusion/ej2-vue-pdfviewer';
  import { AppBarComponent, ToolbarComponent, ItemDirective, ItemsDirective } from "@syncfusion/ej2-vue-navigations";
  import { ButtonComponent } from "@syncfusion/ej2-vue-buttons";
  import { ComboBoxComponent } from "@syncfusion/ej2-vue-dropdowns";
  import { DialogComponent } from '@syncfusion/ej2-vue-popups';
  import { UploaderComponent } from '@syncfusion/ej2-vue-inputs';
  import { getUniqueID } from '@syncfusion/ej2-base';

  var fileName = "programmatical-annotations.pdf";
  var viewer;
  var toolbar;
  var imageElement;
  var primaryToolbarObj;
  var imageElementContainer;
  var currentPageBox;
  var annotation;
  var redactionCount = 0;
  const url = "https://ej2services.syncfusion.com/production/web-services/api/pdfviewer/Redaction";


  function updatePageNavigation() {
      if (viewer.currentPageNumber === 1) {
          toolbar.items[0].disabled = true;
          toolbar.items[2].disabled = false;
      }
      else if (viewer.currentPageNumber === viewer.pageCount) {
          toolbar.items[0].disabled = false;
          toolbar.items[2].disabled = true;
      }
      else {
          toolbar.items[0].disabled = false;
          toolbar.items[2].disabled = false;
      }
  };

  function updateRedaction() {
        if (redactionCount <= 0) {
            primaryToolbarObj.items[8].disabled = true;
        }
        else {
            primaryToolbarObj.items[8].disabled = false;
        }

  };
  function createBlobUrl(base64String, contentType)
  {
    const sliceSize = 512;
    const byteCharacters = atob(base64String);
    const byteArrays = [];
    for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
        const slice = byteCharacters.slice(offset, offset + sliceSize);
        const byteNumbers = new Array(slice.length);
        for (let i = 0; i < slice.length; i++) {
            byteNumbers[parseInt(i.toString(), 10)] = slice.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);
        byteArrays.push(byteArray);
    }
    const blob = new Blob(byteArrays, { type: contentType });
    return blob;
  };

  function downloadDocument(blobUrl)
  {
    const Url = URL || webkitURL;
    blobUrl = Url.createObjectURL(blobUrl);
    viewer.fileName = fileName;
    const anchorElement = document.createElement('a');
    if (anchorElement.click) {
        (anchorElement).href = blobUrl;
        (anchorElement).target = '_parent';
        if ('download' in anchorElement) {
            const downloadFileName = viewer.fileName || 'downloadedFile.pdf';
            if (downloadFileName) {
                if (downloadFileName.endsWith('.pdf')) {
                    (anchorElement).download = downloadFileName;
                }
                else {
                    const splitPdf = downloadFileName.split('.pdf')[0] + '.pdf';
                    (anchorElement).download = splitPdf;
                }
            }
            else {
                (anchorElement).download = 'Default.pdf';
            }
        }
        (document.body || document.documentElement).appendChild(anchorElement);
        anchorElement.click();
    }
    else {
        if (window.top === window &&
            blobUrl.split('#')[0] === window.location.href.split('#')[0]) {
                const padCharacter = blobUrl.indexOf('?') === -1 ? '?' : '&';
                blobUrl = blobUrl.replace(/#|$/, padCharacter + '$&');
        }
        window.open(blobUrl, '_parent');
    }
  };

  function readFile(args) {
        // tslint:disable-next-line
        let upoadedFiles = args.target.files;
        if (args.target.files[0] !== null) {
            let uploadedFile = upoadedFiles[0];
            fileName = uploadedFile.name;
            if (uploadedFile) {
                let reader = new FileReader();
                reader.readAsDataURL(uploadedFile);
                // tslint:disable-next-line
                reader.onload = function (e) {
                    let uploadedFileUrl = e.currentTarget.result;
                    viewer.load(uploadedFileUrl, null);
                    viewer.fileName = fileName;
                    viewer.downloadFileName = fileName;
                };
            }
        }
    };

  export default {
    name: 'App',

    components: {
      "ejs-pdfviewer": PdfViewerComponent,
      "ejs-appbar": AppBarComponent,
      "ejs-button": ButtonComponent,
      'ejs-toolbar': ToolbarComponent,
      'e-item': ItemDirective,
      'e-items': ItemsDirective,
      'ejs-combobox': ComboBoxComponent,
      "ejs-dialog": DialogComponent,
      "ejs-uploader": UploaderComponent
    },

    data() {
      return {
        resourceUrl: "https://cdn.syncfusion.com/ej2/27.1.55/dist/ej2-pdfviewer-lib",
        documentPath: "https://cdn.syncfusion.com/content/pdf/programmatical-annotations.pdf",
        zoomList: ['10%', '25%', '50%', '75%', '100%', '200%', '400%'],
        enableToolbar: false,
        enableNavigationToolbar: false,
        enableAnnotationToolbar:false,
        enableCommentPanel:false,
        proxy: this,
        animationSettings:  { effect: 'None' },
        ShowBtn: true,
        dialogVisible: false,
        autoUpload: false,
        target: '#e-pv-redact-sb-panel',
        path: {
            saveUrl:
                'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Save',
            removeUrl:
                'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Remove',
        },
        extentions: '.png, .jpg, .jpeg',
        imageSrc: "",
        customStampSource: null,
        dlgButtons: [{ click: this.dialogObjClose, buttonModel: { isPrimary:'true', content: 'Cancel' } }]
      };
    },
    provide: {
      PdfViewer: [ Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView,
                   Print, TextSelection, TextSearch, Annotation, FormDesigner, FormFields, PageOrganizer ]
    },
    methods: {
        documentLoad: function (args) {
          viewer = this.$refs.pdfviewer.ej2Instances;
          toolbar = this.$refs.secondaryToolbar.ej2Instances;
          primaryToolbarObj = this.$refs.primaryToolbar.ej2Instances;
          document.getElementById('documentUpload').addEventListener('change', readFile, false);
          currentPageBox = document.getElementById('current-page');
          currentPageBox.textContent = '1 ';
          document.getElementById('total-page').innerHTML = `/ ${viewer.pageCount}`;
          updatePageNavigation();
          updateRedaction();
        },
        downloadClicked: function (args) {
            viewer.saveAsBlob().then(function (value) {
            let reader = new FileReader();
            reader.readAsDataURL(value);
            reader.onload = function (e) {
                const base64String = e.target?.result.toString();
                const xhr = new XMLHttpRequest();
                xhr.open('POST', url, true);
                xhr.setRequestHeader('Content-type', 'application/json; charset=UTF-8');
                const requestData = JSON.stringify({ base64String: base64String });
                xhr.onload = function () {
                    if (xhr.status === 200) {
                        const blobUrl = createBlobUrl(xhr.responseText.split('base64,')[1], 'application/pdf');
                        downloadDocument(blobUrl);
                    }
                    else {
                        console.error('Download failed:', xhr.statusText);
                    }
                };
                xhr.onerror = function () {
                    console.error('An error occurred during the download:', xhr.statusText);
                };
                xhr.send(requestData);
            };
        }).catch(function (error) {
            console.error('Error saving Blob:', error);
        });
        },
        redaction: function (args) {
            if (redactionCount > 0) {
            viewer.saveAsBlob().then(function (value) {
                const data = value;
                const reader = new FileReader();
                reader.readAsDataURL(data);
                reader.onload = function (e) {
                    const base64String = e.target?.result.toString();
                    const xhr = new XMLHttpRequest();
                    xhr.open('POST', url, true);
                    xhr.setRequestHeader('Content-type', 'application/json; charset=UTF-8');
                    const requestData = JSON.stringify({ base64String });
                    xhr.onload = function () {
                        if (xhr.status === 200) {
                            viewer.load(xhr.responseText, null);
                        }
                        else {
                            console.error('Redaction failed:', xhr.statusText);
                        }
                    };
                    xhr.onerror = function () {
                        console.error('An error occurred during the redaction:', xhr.statusText);
                    };
                    xhr.send(requestData);
                };
            });
            redactionCount = 0;
            updateRedaction();
        }
        },
        openClicked: function (args) {
            document.getElementById('documentUpload').click();
        },
        annotationAdd: function (args) {
            var pdfAnnotationList;
            pdfAnnotationList = viewer.annotationCollection;
            var selectedAnnotationIndex = pdfAnnotationList.findIndex(item => item.annotationId == args.annotationId);
            if (selectedAnnotationIndex != -1) {
                annotation = pdfAnnotationList[selectedAnnotationIndex];
            }
            if (annotation.author == "Redaction" || annotation.customStampName == "Image" || annotation.author == "Pattern" || annotation.author == "Text") {
                redactionCount = redactionCount + 1;
                updateRedaction();
            }
        },
        annotationRemove: function (args) {
            if (annotation.author == "Redaction" || annotation.customStampName == "Image" || annotation.author == "Pattern" || annotation.author == "Text") {
                redactionCount = redactionCount - 1;
                updateRedaction();
            }
        },
        addText: function (args) {
            viewer.rectangleSettings = {
                fillColor: '#a3a2a0',
                strokeColor: '#a3a2a0',
                author: 'Text'
            }
            viewer.annotation.setAnnotationMode('Rectangle');
        },
        addPattern: function (args) {
            viewer.rectangleSettings = {
                fillColor: '#dedfe0',
                strokeColor: '#dedfe0',
                author: 'Pattern'
            }
            viewer.annotation.setAnnotationMode('Rectangle');
        },
        addBlackout: function (args) {
            viewer.rectangleSettings = {
                fillColor: '#000000',
                strokeColor: '#000000',
                author: 'Redaction'
            }
            viewer.annotation.setAnnotationMode('Rectangle');
        },
        addWhiteout: function (args) {
            viewer.rectangleSettings = {
                fillColor: '#ffffff',
                strokeColor: '#ffffff',
                author: 'Redaction'
            }
            viewer.annotation.setAnnotationMode('Rectangle');
        },
        zoomValueChange: function (args) {
            let zoom = args.value;
            let previousZoom = args.previousItemData.value;
            if (zoom !== null || previousZoom !== null) {
                let zoomchange = parseInt(zoom.replace("%", ""), 10);
                viewer.magnificationModule.zoomTo(zoomchange);
            }
        },
        pageChange: function (args) {
            currentPageBox = document.getElementById('current-page');
            currentPageBox.textContent = viewer.currentPageNumber.toString() + ' ';
            updatePageNavigation();
        },
        nextClicked: function (args) {
            viewer.navigation.goToNextPage();
        },
        previousClicked: function (args) {
            viewer.navigation.goToPreviousPage();
        },
        dialogObjClose: function() {
          this.$refs.dialogObj.hide();
        },    
        imgClick: function() {
          this.dialogVisible = true;
          this.$refs.dialogObj.show();
        },
        openDocumentClicked: function(args) {
          const textSearchToolbarElement = document.getElementById('textSearchToolbar');
          if (textSearchToolbarElement !== null && textSearchToolbarElement.style.display === 'block') {
              textSearchToolbarElement.style.display = 'none';
          }
          document.getElementById('fileUpload').click();
        },
        handleImageClick() {
          this.customStampSource = this.imageSrc;
          this.dialogVisible = false;
          this.addImage();
        },
        onFileChange(event) {
          const file = event.file[0].rawFile;
          imageElement = this.$refs.imgTag;
          imageElementContainer = this.$refs.imgContainer;
          const reader = new FileReader();
          reader.onload = (e) => {
            const base64String = e.target.result;
            this.imageSrc = base64String;
            this.customStampSource = this.imageSrc;
            imageElement.src = this.imageSrc;
            imageElementContainer.className = 'image-container e-pv-redact-sb-image-container-selected';
            imageElementContainer.style.display = 'block';
            imageElement.addEventListener('click', this.handleImageClick);
          };
          reader.readAsDataURL(file);
        },
        addImage() {
          viewer = this.$refs.pdfviewer.ej2Instances;
          viewer.stampSettings.author = "Image";
          viewer.customStampSettings = {
            width: 200,
            author: 'Image',
            height: 125,
            isAddToMenu: false,
            enableCustomStamp: false,
          };
          viewer.customStamp = [
            {
              customStampName: 'Image',
              customStampImageSource: this.customStampSource,
            },
          ];
        },
    },
  }

</script>

<style>
#e-pv-redact-sb-flexContainer {
    display: flex;
    justify-content: flex-end;
}

#e-pv-redact-sb-panel.control-section .e-dlg-overlay
{
    background: none;
    backdrop-filter: blur(2px) !important;
}

/*new*/
#e-pv-redact-sb-panel.control-section .e-appbar {
    height: 36px;
    font-size: 14px !important;
}
#e-pv-redact-sb-toolbar.e-toolbar .e-toolbar-item .e-tbar-btn.e-tbtn-txt .e-icons.e-btn-icon
{
    padding: 4px !important;
}
#e-pv-redact-sb-toolbar.e-toolbar .e-toolbar-item .e-tbar-btn {
    flex-direction: column;
}  
#e-pv-redact-sb-toolbar.e-toolbar .e-toolbar-item .e-tbar-btn .e-icons.e-btn-icon 
{
    font-size: 18px;
}
#e-pv-redact-sb-toolbar
{
    height: 72px !important;
}
#e-pv-redact-sb-toolbar .e-toolbar-items
{
    gap: 5px;
}

.e-pv-redact-sb-secondary-toolbar .e-toolbar-item.page-count.e-template {
    min-width: 0px !important;
}

#e-pv-redact-sb-toolbar .e-toolbar-item.e-separator
{
    height: 48px !important;
}
#e-pv-redact-sb-toolbar , #e-pv-redact-sb-toolbar .e-toolbar , .e-pv-redact-sb-secondary-toolbar .e-toolbar
{
    border-left-width: 1px !important;
    border-right-width: 1px !important;
}

#e-pv-redact-sb-toolbar .e-toolbar , .e-pv-redact-sb-secondary-toolbar .e-toolbar
{
    border-top-width: 1px !important;
}

#e-pv-redact-sb-panel.control-section .e-input-group
{
    border:none !important;
} 
.e-pv-redact-sb-black-out-container .black-out {
    background-color: black;
    width: 18px !important;
    height: 18px !important;
    border: 1px solid white;
    border-radius: 3px;
    margin:4px !important;
}
.e-pv-redact-sb-white-out-container .white-out {
    background-color: white;
    width: 18px !important;
    height: 18px !important;
    border: 1px solid black;
    border-radius: 3px;
    margin:4px !important;
}
.e-bigger .e-pv-redact-sb-black-out-container .black-out,
    .e-bigger .e-pv-redact-sb-white-out-container .white-out {
        position: relative;
        top: -4px;
}
.e-bigger #e-pv-redact-sb-toolbar.e-toolbar .e-toolbar-item.e-pv-redact-sb-black-out-container .e-tbar-btn.e-btn,
    .e-bigger #e-pv-toolbar.e-toolbar .e-toolbar-item.e-pv-redact-sb-white-out-container .e-tbar-btn.e-btn {
        padding-top : 5px !important;
}
.e-bigger .e-pv-redact-sb-black-out-container .e-tbar-btn .e-tbar-btn-text,
     .e-bigger .e-pv-redact-sb-white-out-container .e-tbar-btn .e-tbar-btn-text{
         padding: 2px 4px 7px 4px !important;
}
/*upload image*/
#e-pv-redact-sb-dialog.e-dialog #e-pv-redact-sb-defaultfileupload #e-pv-redact-sb-defaultfileupload .e-upload-files {
        border: none !important;
}
#e-pv-redact-sb-panel.control-section #file-uploader
{
    display: flex;
    border: 1px dashed #c8c6c4;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 12px;
    padding: 16px;
    border-radius: 6px;
}
#e-pv-redact-sb-dialog.e-dialog .e-dlg-header-content
{
    border-bottom:1px solid #C4C7C5 !important;
    padding: 15px !important;
}

#e-pv-redact-sb-dialog.e-dialog .e-footer-content
{
    border-top:1px solid #C4C7C5 !important;
    padding: 10px !important;
}

#e-pv-redact-sb-dialog.e-dialog .e-dlg-header-content+.e-dlg-content
{
    padding: 20px !important;
}

#e-pv-redact-sb-panel.control-section .e-file-select-wrap
{
    display: flex;
    flex-direction: column;
    align-items: center;
}

#e-pv-redact-sb-dialog.e-dialog .e-footer-content .e-btn
{
    background: rgba(0, 0, 0, 0);
    border-color: rgba(0, 0, 0, 0);
    box-shadow: none;
    color: #242424;
}

#e-pv-redact-sb-defaultfileupload .e-upload-file-list {
    display: none;
}
#e-pv-redact-sb-defaultfileupload .e-upload-files {
    border: none !important;
}
.e-pv-redact-sb-image-source {
    width: 70px;
    height: 70px;
}
.e-pv-redact-sb-image-container {
    box-shadow: 0px 10px 15px -3px rgba(0, 0, 0, 0.1), 0px 10px 15px -3px rgba(0, 0, 0, 0.1);
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 4px;
    gap: 5px;
    border-radius: 4px;
}
.e-pv-redact-sb-image-list {
    display: flex;
    justify-content: center;
    padding: 24px 15px;
    gap: 35px;
}
.e-pv-redact-sb-image-container-selected {
    border: 1px solid #757575 !important;
}
.e-pv-redact-sb-image-container:hover {
    border: 1px solid #757575;
}
#e-pv-redact-sb-drop-area-wrap {
    display: flex;
    border: 1px dashed #c8c6c4;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 12px;
    padding: 16px;
    border-radius: 6px;
}
#e-pv-redact-sb-panel.control-section #uploadicon {    
    cursor: pointer;
    top: 5px;
    left: 20px;
    position: relative;
}
#e-pv-redact-sb-defaultfileupload .e-upload {
    border: none;
    margin-top: 10px;
    width: 100%;
    height:100%;
}
#e-pv-redact-sb-dialog
{
    max-height: 600px !important;
}
</style>
