// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/source/gantt/remote-data.vue
<template>
<div>
<div class="control-section">
    <div class="content-wrapper">
        <ejs-gantt ref='gantt' id="GanttContainer" 
            :dataSource= "dataSource"
            :height= "height"
            :taskFields= "taskFields"
            :columns= "columns"
            :treeColumnIndex= "1"
            :allowSelection= "true"
            :gridLines= "gridLines"
            :highlightWeekends= "true"
            :timelineSettings= "timelineSettings"
            :labelSettings= "labelSettings"
            :includeWeekend= "true"
            :projectStartDate= "projectStartDate"
            :projectEndDate= "projectEndDate"
        >
        </ejs-gantt>
        <div style="float: right; margin: 10px;">Source:
            <a href="https://en.wikipedia.org/wiki/Cereal_growth_staging_scales"
                target='_blank'>https://en.wikipedia.org/</a>
        </div>
    </div>

</div>

<div id="action-description">
    <p>This sample demonstrates the way of binding data to Gantt chart with remote service. The Gantt chart data source
        is bound to remote data using DataManager. This sample data helps to visualize the various phases of Barley
        harvesting.</p>
</div>

<div id="description">
    <p>
        The <code>dataSource</code> property in Gantt chart can be assigned with the instance of
        <code>DataManager</code> to bind remote data.
        The DataManager, which will act as an interface between the service endpoint and the Gantt chart, will require
        the below minimal information to interact with service endpoint properly.
        <ul>
        <li><code>DataManager->url</code> - Defines the service endpoint to fetch data</li>
        <li><code>DataManager->adaptor</code> - Defines the adaptor option. By default, ODataAdaptor is used for remote
            binding.</li>
        </ul>
        Adaptor is responsible for processing response and request from/to the service endpoint.
        <code>@syncfusion/ej2-data</code>
        package provides some predefined adaptors which are designed to interact with particular service endpoints. They
        are,
        <ul>
        <li><code>UrlAdaptor</code> - Use this to interact any remote services. This is the base adaptor for all remote
            based adaptors.</li>
        <li><code>ODataAdaptor</code> - Use this to interact with OData endpoints.</li>
        <li><code>ODataV4Adaptor</code> - Use this to interact with OData V4 endpoints.</li>
        <li><code>WebApiAdaptor</code> - Use this to interact with Web API created under OData standards.</li>
        <li><code>WebMethodAdaptor</code> - Use this to interact with web methods.</li>
        </ul>
        In this demo, remote data is bound by assigning service data as an instance of <code>DataManager</code> to the
        <code>dataSource</code>
        property.
        More information on the data binding can be found in this documentation section.
    </p>
    <p>
        Gantt component features are segregated into individual feature-wise modules. To use a selection support, inject the
        <code>Selection</code> module.
    </p>
</div>
</div>
</template>
<script>
import { GanttComponent,Selection, DayMarkers } from "@syncfusion/ej2-vue-gantt";
import { DataManager, WebApiAdaptor } from '@syncfusion/ej2-data';

export default {
  components: {
    'ejs-gantt': GanttComponent
  },
  data: function() {
      return{
            dataSource: new DataManager({
        url: 'https://ej2services.syncfusion.com/production/web-services/api/GanttData',
        adaptor: new WebApiAdaptor,
        crossDomain: true
    }),
            height: '450px',
            taskFields: {
                id: 'TaskId',
                name: 'TaskName',
                startDate: 'StartDate',
                progress: 'Progress',
                duration: 'Duration',
                dependency: 'Predecessor',
                child: 'SubTasks'
            },
            columns: [
			    { field: 'TaskId', visible: false },
                { field: 'TaskName', headerText: 'Task Name', width: '250', clipMode: 'EllipsisWithTooltip' },
                { field: 'StartDate' },
                { field: 'Duration' },
            ],
            gridLines: 'Both',
            timelineSettings: {
                timelineUnitSize: 50,
                topTier: {
                    unit: 'Month',
                    format: 'MMM dd, y',
                },
                bottomTier: {
                    unit: 'Day',
                    formatter: (date) => {
                        let month = date.getMonth();
                        if (month === 1) {
                            return '';
                        } else {
                            let presentDate = new Date(date.getFullYear(), date.getMonth(), date.getDate());
                            let start = new Date(presentDate.getFullYear(), 0, 0);
                            let diff = Number(presentDate) - Number(start);
                            let oneDay = 1000 * 60 * 60 * 24;
                            let day = Math.floor(diff / oneDay);
                            return 'day ' + (day - 59);
                        }
                    },
                },
            },
            labelSettings: {
                leftLabel: 'TaskName',
            },
            projectStartDate: new Date('02/24/2021'),
            projectEndDate: new Date('06/10/2021')
        };
  },
  provide: {
      gantt: [Selection, DayMarkers]
  }
}
</script>

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/gantt/remote-data.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.RemoteData = void 0;
var React = require("react");
var ej2_react_gantt_1 = require("@syncfusion/ej2-react-gantt");
var ej2_data_1 = require("@syncfusion/ej2-data");
var sample_base_1 = require("../common/sample-base");
var RemoteData = /** @class */ (function (_super) {
    __extends(RemoteData, _super);
    function RemoteData() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.taskFields = {
            id: 'TaskId',
            name: 'TaskName',
            startDate: 'StartDate',
            duration: 'Duration',
            dependency: 'Predecessor',
            child: 'SubTasks'
        };
        _this.projectStartDate = new Date('02/24/2021');
        _this.projectEndDate = new Date('06/10/2021');
        _this.gridLines = 'Both';
        _this.timelineSettings = {
            timelineUnitSize: 50,
            topTier: {
                unit: 'Month',
                format: 'MMM dd, y',
            },
            bottomTier: {
                unit: 'Day',
                formatter: function (date) {
                    var month = date.getMonth();
                    if (month === 1) {
                        return '';
                    }
                    else {
                        var presentDate = new Date(date.getFullYear(), date.getMonth(), date.getDate());
                        var start = new Date(presentDate.getFullYear(), 0, 0);
                        var diff = Number(presentDate) - Number(start);
                        var oneDay = 1000 * 60 * 60 * 24;
                        var day = Math.floor(diff / oneDay);
                        return 'day ' + (day - 59);
                    }
                },
            },
        };
        _this.dataSource = new ej2_data_1.DataManager({
            url: 'https://ej2services.syncfusion.com/production/web-services/api/GanttData',
            adaptor: new ej2_data_1.WebApiAdaptor,
            crossDomain: true
        });
        _this.labelSettings = {
            leftLabel: 'TaskName'
        };
        return _this;
    }
    RemoteData.prototype.render = function () {
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section' },
                React.createElement(ej2_react_gantt_1.GanttComponent, { id: 'RemoteData', dataSource: this.dataSource, allowSorting: true, dateFormat: 'MMM dd, y', treeColumnIndex: 1, allowSelection: true, highlightWeekends: false, includeWeekend: true, allowUnscheduledTasks: true, projectStartDate: this.projectStartDate, projectEndDate: this.projectEndDate, taskFields: this.taskFields, gridLines: this.gridLines, timelineSettings: this.timelineSettings, labelSettings: this.labelSettings, height: '410px' },
                    React.createElement(ej2_react_gantt_1.ColumnsDirective, null,
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'TaskId', visible: false }),
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'TaskName', headerText: 'Task Name', width: '250', clipMode: 'EllipsisWithTooltip' }),
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'StartDate' }),
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'Duration' })),
                    React.createElement(ej2_react_gantt_1.Inject, { services: [ej2_react_gantt_1.Selection] })),
                React.createElement("div", { style: { float: 'right', margin: '10px' } },
                    "Source:",
                    React.createElement("a", { href: "https://en.wikipedia.org/wiki/Cereal_growth_staging_scales", target: '_blank' }, "https://en.wikipedia.org/"))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample demonstrates the way of binding data to Gantt chart with remote service. The Gantt chart data source is bound to remote data using DataManager. This sample data helps to visualize the various phases of Barley harvesting.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "The ",
                    React.createElement("code", null, "dataSource"),
                    " property in Gantt chart can be assigned with the instance of",
                    React.createElement("code", null, "DataManager"),
                    " to bind remote data. The DataManager, which will act as an interface between the service endpoint and the Gantt chart, will require the below minimal information to interact with service endpoint properly.",
                    React.createElement("li", null,
                        React.createElement("code", null, "DataManager->url"),
                        " - Defines the service endpoint to fetch data"),
                    React.createElement("li", null,
                        React.createElement("code", null, "DataManager->adaptor"),
                        " - Defines the adaptor option. By default, ODataAdaptor is used for remote binding."),
                    "Adaptor is responsible for processing response and request from/to the service endpoint.",
                    React.createElement("code", null, "@syncfusion/ej2-data"),
                    "package provides some predefined adaptors which are designed to interact with particular service endpoints. They are,",
                    React.createElement("li", null,
                        React.createElement("code", null, "UrlAdaptor"),
                        " - Use this to interact any remote services. This is the base adaptor for all remote based adaptors."),
                    React.createElement("li", null,
                        React.createElement("code", null, "ODataAdaptor"),
                        " - Use this to interact with OData endpoints."),
                    React.createElement("li", null,
                        React.createElement("code", null, "ODataV4Adaptor"),
                        " - Use this to interact with OData V4 endpoints."),
                    React.createElement("li", null,
                        React.createElement("code", null, "WebApiAdaptor"),
                        " - Use this to interact with Web API created under OData standards."),
                    React.createElement("li", null,
                        React.createElement("code", null, "WebMethodAdaptor"),
                        " - Use this to interact with web methods."),
                    "In this demo, remote data is bound by assigning service data as an instance of ",
                    React.createElement("code", null, "DataManager"),
                    " to the",
                    React.createElement("code", null, "dataSource"),
                    "property. More information on the data binding can be found in this documentation section."),
                React.createElement("p", null,
                    "Gantt component features are segregated into individual feature-wise modules. To use a selection feature, inject the",
                    React.createElement("code", null, "Selection"),
                    " module."))));
    };
    return RemoteData;
}(sample_base_1.SampleBase));
exports.RemoteData = RemoteData;
