// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/uploader/file-validation.jsx
import * as React from 'react';
import { SampleBase } from '../common/sample-base';
import { UploaderComponent } from '@syncfusion/ej2-react-inputs';
import './uploader.css';
export class Validation extends SampleBase {
    // Uploader component
    uploadObj;
    asyncSettings;
    allowedExtensions;
    minFileSize;
    autoUpload;
    dropContainerRef;
    dropContainerEle;
    constructor(props) {
        super(props);
        this.dropContainerEle = null;
        this.dropContainerRef = element => {
            this.dropContainerEle = element;
        };
        this.asyncSettings = {
            saveUrl: 'http://localhost:62728/api/FileUploader/Save',
            removeUrl: 'http://localhost:62728/api/FileUploader/Remove'
        };
        this.minFileSize = 10000;
        this.autoUpload = false;
        this.allowedExtensions = '.doc, .docx, .xls, .xlsx';
    }
    rendereComplete() {
        this.uploadObj.dropArea = this.dropContainerEle;
        this.uploadObj.element.setAttribute('name', 'UploadFiles');
        this.uploadObj.dataBind();
    }
    onFileSelected(args) {
        args.filesData.splice(5);
        let filesData = this.uploadObj.getFilesData();
        let allFiles = filesData.concat(args.filesData);
        if (allFiles.length > 5) {
            for (let i = 0; i < allFiles.length; i++) {
                if (allFiles.length > 5) {
                    allFiles.shift();
                }
            }
            args.filesData = allFiles;
            args.modifiedFilesData = args.filesData;
        }
        args.isModified = true;
    }
    onRemoveFile(args) {
        args.postRawFile = false;
    }
    render() {
        return (<div className='control-pane' ref={this.dropContainerRef}>
			<div className='control-section col-lg-12 uploadpreview'>
				<div className='upload_wrapper'>
					<UploaderComponent id='validation' type='file' ref={(scope) => { this.uploadObj = scope; }} asyncSettings={this.asyncSettings} selected={this.onFileSelected.bind(this)} minFileSize={this.minFileSize} autoUpload={this.autoUpload} removing={this.onRemoveFile.bind(this)} allowedExtensions={this.allowedExtensions}></UploaderComponent>
				</div>
			</div>

			<div id="action-description">
				<p>This <a href="https://www.syncfusion.com/react-ui-components/react-file-upload" target="_blank">&nbsp;React File Upload</a> example demonstrates how to validate the files before uploading it to server. Only document files (DOC, DOCX, XLS, XLSX),
					and the files should contain minimum 10 KB and maximum 28 MB sizes to upload it into server.This sample limits maximum files count as 5 to upload.</p>
			</div>
			<div id="description">
				<p>The Uploader component allows to validate the file’s type, and limit the file size using allowedExtensions, minFileSize, and maxFileSize properties.
				You can also achieve limit the files count before uploading it using select event. </p>
				 
				<p>For more information, you can refer to the Validation section from this <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/uploader/validation/">documentation section</a>.</p>
			</div>
      </div>);
    }
}

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/src/uploader/file-validation.vue
﻿<template>
  <div>
    <div class="col-lg-12 control-section uploader-preload validation">
        <div class="control_wrapper">
            <ejs-uploader id='validation' name="UploadFiles" :autoUpload= "autoUpload" :asyncSettings= "path" ref="uploadObj" :allowedExtensions = "extensions" :dropArea= "dropElement"  minFileSize=10000 maxFileSize=4000000
            :selected= "onFileSelect" :removing= "onFileRemove"> 
            </ejs-uploader>
        </div>
    </div>
    <div id="action-description">
      <p>This <a href="https://www.syncfusion.com/vue-ui-components/vue-file-upload"
            target="_blank">&nbsp;Vue File Upload</a> example demonstrates how to validate the files before uploading it to server. Only document files (DOC, DOCX, XLS, XLSX), and the files should contain minimum 10 KB and maximum 28 MB sizes to upload it into server.This sample limits maximum files count as 5 to upload.</p>
    </div>

    <div id="description">
        <p>The Uploader component allows to validate the file’s type, and limit the file size using
            <a href='https://ej2.syncfusion.com/vue/documentation/api/uploader/#allowedextensions' target="_blank"> allowedExtensions </a>,
            <a href='https://ej2.syncfusion.com/vue/documentation/api/uploader/#minfilesize' target="_blank"> minFileSize </a> , and
            <a href= 'https://ej2.syncfusion.com/vue/documentation/api/uploader/#maxfilesize' target="_blank"> maxFileSize </a>
            properties. You can also achieve limit the files count before uploading it using 
            <a href='https://ej2.syncfusion.com/vue/documentation/api/uploader/#selected' target="_blank">select</a>
            event.
        </p>
        <p>For more information, you can refer to the <a href='https://ej2.syncfusion.com/vue/documentation/uploader/validation/' target="_blank">
         Validation </a> section from the documentation.</p>
    </div>
</div>
</template>

<style scoped>
.validation .control_wrapper {
    max-width: 450px;
    min-width: 245px;
    margin: auto;
}
#validation .e-upload.e-control {
    position: relative;
    margin: 15px 0;
}

.control-section .uploader-preload.col-lg-8 {
    padding: 20px;
}

</style>
<script>
import { UploaderComponent } from '@syncfusion/ej2-vue-inputs';

export default {
    data: function(){
        return {
          path:  {
            saveUrl: 'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Save',
            removeUrl: 'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Remove'
          },
          dropElement: '.control-fluid',
          extensions: '.doc, .docx, .xls, .xlsx',
          autoUpload: false
        }
    },
    components: { 'ejs-uploader': UploaderComponent },
    methods: {
        onFileSelect: function(args) {
            args.filesData.splice(5);
            let filesData = this.$refs.uploadObj.getFilesData();
            let allFiles = filesData.concat(args.filesData);
            if (allFiles.length > 5) {
                for (let i = 0; i < allFiles.length; i++) {
                    if (allFiles.length > 5) {
                        allFiles.shift();
                    }
                }
                args.filesData = allFiles;
                args.modifiedFilesData = args.filesData;
            }
            args.isModified = true;
        },

        onFileRemove: function (args) {
            args.postRawFile = false;
        }
    }
};
</script>
