// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/mention/multiple-list.tsx
/**
 * Mention Multiple List Sample
 */
import * as ReactDOM from 'react-dom';
import * as React from 'react';
import { MentionComponent } from '@syncfusion/ej2-react-dropdowns';
import { DataManager, Query, WebApiAdaptor } from '@syncfusion/ej2-data';
import { SampleBase } from '../common/sample-base';
import './multiple-list.css';
import * as data from './dataSource.json';

export class MultipleList extends SampleBase<{}, {}> {

  private projectTemp:string = 'projects';
  private useCostTemp:string = 'useCosts';
  private statusTemp:string = 'status';
  private data: DataManager = new DataManager({
        url: 'https://ej2services.syncfusion.com/production/web-services/api/Employees',
        adaptor: new WebApiAdaptor,
        crossDomain: true
  });
  private query: Query = new Query().select(['FirstName', 'EmployeeID']).requiresCount();
  private projects: { [key: string]: Object }[] = data[this.projectTemp];
  private useCosts: { [key: string]: Object }[] = data[this.useCostTemp];
  private status: { [key: string]: Object }[] = data[this.statusTemp];
  private commonTarget: string = '#multipleList';
  private dataFields: Object = { text: 'FirstName', value: 'EmployeeID' };
  public localFields: Object = { text: 'Value' };

  private projectsDisplayTemplate(data: any): JSX.Element {
    return (
      <React.Fragment>
          <span className="e-success">{data.Value}</span>
      </React.Fragment>
      );
  }
  private costDisplayTemplate(data: any): JSX.Element {
    return (
      <React.Fragment>
          <span className="e-error">{data.Value}</span>
      </React.Fragment>
      );
  }

  private statusDisplayTemplate(data: any): JSX.Element {
    return (
      <React.Fragment>
          <span className="e-warning">{data.Value}</span>
      </React.Fragment>
      );
  }

  render() {
    return (
      <div className='control-pane'>
        <div className='control-section'>
            <div className="content-wrapper">
              <div id='mention_multiplelist'>
                <table>
                  <tbody>
                    <tr>
                      <td>
                          <label id="label" className="multiple">Start typing <code>@</code>, <code>#</code>, <code>$</code> or <code>%</code> to select the respective values</label>
                          <div id="multipleList" placeholder="Type here..!"></div>
                      </td>
                    </tr>
                  </tbody>
                </table>

                <MentionComponent dataSource={this.data} target={this.commonTarget} fields={this.dataFields} suggestionCount={15} query={this.query} popupWidth={250} popupHeight={250} allowSpaces={true}></MentionComponent>

              <MentionComponent dataSource={this.projects} requireLeadingSpace={false} mentionChar={'#'} target={this.commonTarget} displayTemplate={this.projectsDisplayTemplate} fields={this.localFields}></MentionComponent>

                <MentionComponent dataSource={this.useCosts} mentionChar={'$'} target={this.commonTarget} displayTemplate={this.costDisplayTemplate} fields={this.localFields}></MentionComponent>

                <MentionComponent dataSource={this.status} mentionChar={'%'} target={this.commonTarget} displayTemplate={this.statusDisplayTemplate} fields={this.localFields}></MentionComponent>
              </div>
            </div>
        </div>
        <div id="action-description">
          <p>This sample demonstrates the different mentioned characters that are used to render the suggestion list. Type the <code>@</code> or <code>#</code> or <code>$</code> or <code>%</code> characters to select or tag the name from respective suggestion lists.</p>
        </div>
            
        <div id="description">
          <p>
            The <code>requireLeadingSpace</code> property in Mention controls whether a space is needed before triggering the
            Mention suggestion popup.
            When set to <code>false</code>, it activates without a space; when set to <code>true</code>, a space is required
            before the Mention character. To see this feature in action, start typing with <code>#</code>.
          </p>
          <p>In the above sample, the following are configured for the contenteditable div element with @mention integrated.</p>
          <ul>
              <li><code>@</code> - Typing <code>@</code> lists out the suggestions of the employee names.</li>
              <li><code>#</code> - Typing <code>#</code> lists the project names.</li>
              <li><code>$</code> - Typing <code>$</code> lists out the cost of the project.</li>
              <li><code>%</code> - Typing <code>%</code> lists the status of the project.</li>
          </ul>
        </div>
      </div>
    );
  }
}

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Angular/source/mention/multiple-list.component.ts
/**
 * Mention multiple-list Sample
 */
import { Component } from '@angular/core';
import { Query, DataManager, WebApiAdaptor } from '@syncfusion/ej2-data';
import { SBDescriptionComponent } from '../common/dp.component';
import { MentionModule } from '@syncfusion/ej2-angular-dropdowns';
import { SBActionDescriptionComponent } from '../common/adp.component';

@Component({
    selector: 'control-content',
    templateUrl: 'multiple-list.html',
    styleUrls: ['mention.css'],
    standalone: true,
    imports: [SBActionDescriptionComponent, MentionModule, SBDescriptionComponent]
})
export class MultipleListMentionComponent {
    // define the JSON of data
    public projects: Object[] = [
        { Id: 'Project1', Value: 'ERP' }, 
        { Id: 'Project2', Value: 'Help desk' },
        { Id: 'Project3', Value: 'Banking' }, 
        { Id: 'Project4', Value: 'Chat Box' },
        { Id: 'Project5', Value: 'Accounts' }
    ];

    public useCosts: Object[] = [
        { Id: 'Cost1', Value: '$1000' }, 
        { Id: 'Cost2', Value: '$1500' },
        { Id: 'Cost3', Value: '$3000' }, 
        { Id: 'Cost4', Value: '$3250' },
        { Id: 'Cost5', Value: '$5000' }
    ];

    public status: Object[] = [
        { Id: 'status1', Value: 'Open' }, 
        { Id: 'status2', Value: 'In-progress' },
        { Id: 'status3', Value: 'Hold' }, 
        { Id: 'status4', Value: 'Closed' }
    ];

    public commonTarget: string = '#multipleList';
    public localFields: Object = { text: 'Value' };
    public dataFields: Object = { text: 'FirstName', value: 'EmployeeID' };
    public count: number = 15;
    public popupWidth: string = "250px";
    public popupHeight: string = "250px";

    public data: DataManager = new DataManager({
        url: 'https://ej2services.syncfusion.com/production/web-services/api/Employees',
        adaptor: new WebApiAdaptor,
        crossDomain: true
    });
    public query: Query = new Query().select(['FirstName', 'EmployeeID']).requiresCount();
}
