// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/multi-select/virtual-scroll.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Default = void 0;
var React = require("react");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var ej2_data_1 = require("@syncfusion/ej2-data");
var ej2_react_buttons_1 = require("@syncfusion/ej2-react-buttons");
var sample_base_1 = require("../common/sample-base");
var property_pane_1 = require("../common/property-pane");
require("./virtual-scroll.css");
var Default = /** @class */ (function (_super) {
    __extends(Default, _super);
    function Default(props) {
        var _this = _super.call(this, props) || this;
        // define the array of string
        _this.records = [];
        // bind the DataManager instance to dataSource property
        _this.customerData = new ej2_data_1.DataManager({
            url: 'https://ej2services.syncfusion.com/production/web-services/api/VirtualDropdownData',
            adaptor: new ej2_data_1.UrlAdaptor,
            crossDomain: true
        });
        // maps the appropriate column to fields property
        _this.fields = { text: 'text', value: 'id' };
        _this.customerField = { text: 'OrderID', value: 'OrderID' };
        _this.groupField = { groupBy: 'group', text: 'text', value: 'id' };
        _this.value = ['id10', 'id50', 'id100', "custom"];
        for (var i = 1; i <= 150; i++) {
            var item = {};
            item.id = 'id' + i;
            item.text = "Item ".concat(i);
            // Generate a random number between 1 and 4 to determine the group
            var randomGroup = Math.floor(Math.random() * 4) + 1;
            switch (randomGroup) {
                case 1:
                    item.group = 'Group A';
                    break;
                case 2:
                    item.group = 'Group B';
                    break;
                case 3:
                    item.group = 'Group C';
                    break;
                case 4:
                    item.group = 'Group D';
                    break;
                default:
                    break;
            }
            _this.records.push(item);
        }
        return _this;
    }
    Default.prototype.headerTemplate = function (data) {
        return (React.createElement("div", { className: "header" },
            React.createElement("span", { style: { marginLeft: '17px' } }, "Items Info")));
    };
    //set the value to item template
    Default.prototype.itemTemplate = function (data) {
        return (React.createElement("div", { className: "ename", style: { height: '40px' } },
            " ",
            data.text,
            " "));
    };
    //set the value to value template
    Default.prototype.valueTemplate = function (data) {
        return (React.createElement("div", { className: "name" },
            " ",
            data.text,
            " "));
    };
    Default.prototype.onChange = function (args) {
        // enable or disable the SelectAll in multiselect on CheckBox checked state
        this.localObj.allowFiltering = args.checked;
        this.remoteObj.allowFiltering = args.checked;
        this.databindObj.allowFiltering = args.checked;
        this.groupObj.allowFiltering = args.checked;
        this.templateObj.allowFiltering = args.checked;
    };
    Default.prototype.onChangeHide = function (args) {
        // enable or disable the SelectAll in multiselect on CheckBox checked state
        this.localObj.hideSelectedItem = args.checked;
        this.remoteObj.hideSelectedItem = args.checked;
        this.databindObj.hideSelectedItem = args.checked;
        this.groupObj.hideSelectedItem = args.checked;
        this.templateObj.hideSelectedItem = args.checked;
    };
    Default.prototype.onChangeClose = function (args) {
        // enable or disable the SelectAll in multiselect on CheckBox checked state
        this.localObj.closePopupOnSelect = args.checked;
        this.remoteObj.closePopupOnSelect = args.checked;
        this.databindObj.closePopupOnSelect = args.checked;
        this.groupObj.closePopupOnSelect = args.checked;
        this.templateObj.closePopupOnSelect = args.checked;
    };
    Default.prototype.onChangeCustom = function (args) {
        // enable or disable the SelectAll in multiselect on CheckBox checked state
        this.localObj.allowCustomValue = args.checked;
        this.remoteObj.allowCustomValue = args.checked;
        this.databindObj.allowCustomValue = args.checked;
        this.templateObj.allowCustomValue = args.checked;
    };
    // call the change event's function after initialized the component.
    Default.prototype.rendereComplete = function () {
    };
    Default.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", null,
            React.createElement("div", { className: "control-section col-lg-8" },
                React.createElement("div", { className: "multi-control-wrapper" },
                    React.createElement("h4", null, "Local Data"),
                    React.createElement(ej2_react_dropdowns_1.MultiSelectComponent, { id: "local", ref: function (scope) { _this.localObj = scope; }, dataSource: this.records, placeholder: "e.g. Item 1", mode: "Box", allowFiltering: true, enableVirtualization: true, allowCustomValue: true, showDropDownIcon: true, hideSelectedItem: true, closePopupOnSelect: true, fields: this.fields, popupHeight: "200px" },
                        React.createElement(ej2_react_dropdowns_1.Inject, { services: [ej2_react_dropdowns_1.VirtualScroll] }))),
                React.createElement("div", { className: "multi-control-wrapper" },
                    React.createElement("h4", null, "Remote Data"),
                    React.createElement(ej2_react_dropdowns_1.MultiSelectComponent, { id: "remote", ref: function (scope) { _this.remoteObj = scope; }, dataSource: this.customerData, placeholder: "e.g. OrderID", mode: "Delimiter", allowFiltering: true, enableVirtualization: true, allowCustomValue: true, showDropDownIcon: true, hideSelectedItem: true, closePopupOnSelect: true, fields: this.customerField, popupHeight: "200px" },
                        React.createElement(ej2_react_dropdowns_1.Inject, { services: [ej2_react_dropdowns_1.VirtualScroll] }))),
                React.createElement("div", { className: "multi-control-wrapper" },
                    React.createElement("h4", null, "Default Values"),
                    React.createElement(ej2_react_dropdowns_1.MultiSelectComponent, { id: "databind", ref: function (scope) { _this.databindObj = scope; }, dataSource: this.records, placeholder: "e.g. Item 1", value: this.value, mode: "Default", allowFiltering: true, enableVirtualization: true, allowCustomValue: true, showDropDownIcon: true, hideSelectedItem: true, closePopupOnSelect: true, fields: this.fields, popupHeight: "200px" },
                        React.createElement(ej2_react_dropdowns_1.Inject, { services: [ej2_react_dropdowns_1.VirtualScroll] }))),
                React.createElement("div", { className: "multi-control-wrapper" },
                    React.createElement("h4", null, "Grouping"),
                    React.createElement(ej2_react_dropdowns_1.MultiSelectComponent, { id: "group", ref: function (scope) { _this.groupObj = scope; }, dataSource: this.records, placeholder: "e.g. Item 1", mode: "CheckBox", allowFiltering: true, enableVirtualization: true, enableSelectionOrder: false, allowCustomValue: true, showDropDownIcon: true, hideSelectedItem: true, closePopupOnSelect: true, fields: this.groupField, popupHeight: "200px" },
                        React.createElement(ej2_react_dropdowns_1.Inject, { services: [ej2_react_dropdowns_1.VirtualScroll, ej2_react_dropdowns_1.CheckBoxSelection] }))),
                React.createElement("div", { className: "multi-control-wrapper" },
                    React.createElement("h4", null, "Template"),
                    React.createElement(ej2_react_dropdowns_1.MultiSelectComponent, { id: "Template", ref: function (scope) { _this.templateObj = scope; }, dataSource: this.records, placeholder: "e.g. Item 1", mode: "Default", allowFiltering: true, enableVirtualization: true, allowCustomValue: true, showDropDownIcon: true, hideSelectedItem: true, closePopupOnSelect: true, fields: this.fields, popupHeight: "200px", itemTemplate: this.itemTemplate, valueTemplate: this.valueTemplate, headerTemplate: this.headerTemplate },
                        React.createElement(ej2_react_dropdowns_1.Inject, { services: [ej2_react_dropdowns_1.VirtualScroll] })))),
            React.createElement("div", { className: 'col-lg-4 property-section', style: { left: '0px', width: '250px' } },
                React.createElement(property_pane_1.PropertyPane, { title: 'Properties' },
                    React.createElement("table", { id: "property", title: "Properties", className: 'property-panel-table', style: { width: '100%' } },
                        React.createElement("tr", null,
                            React.createElement("td", null,
                                React.createElement("div", null,
                                    React.createElement(ej2_react_buttons_1.CheckBoxComponent, { checked: true, label: 'AllowFiltering', ref: function (scope) { _this.checkboxObj = scope; }, change: this.onChange.bind(this) })))),
                        React.createElement("tr", null,
                            React.createElement("td", null,
                                React.createElement("div", null,
                                    React.createElement(ej2_react_buttons_1.CheckBoxComponent, { checked: true, label: 'AllowCustomValue', ref: function (scope) { _this.checkboxObj = scope; }, change: this.onChangeCustom.bind(this) })))),
                        React.createElement("tr", null,
                            React.createElement("td", null,
                                React.createElement("div", null,
                                    React.createElement(ej2_react_buttons_1.CheckBoxComponent, { checked: true, label: 'HideSelectedItem', ref: function (scope) { _this.checkboxObj = scope; }, change: this.onChangeHide.bind(this) })))),
                        React.createElement("tr", null,
                            React.createElement("td", null,
                                React.createElement("div", null,
                                    React.createElement(ej2_react_buttons_1.CheckBoxComponent, { checked: true, label: 'ClosePopupOnSelect', ref: function (scope) { _this.checkboxObj = scope; }, change: this.onChangeClose.bind(this) }))))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This example demonstrates the virtualization support of the MultiSelect. The component has 150 items bound to it; however, when you open the suggestion list, only few items are loaded based on the popup height, and the remaining items are loaded while scrolling.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "The ",
                    React.createElement("code", null, "MultiSelect"),
                    " component supports virtualization, which improves UI performance for large amounts of data. To enable virtualization, set the ",
                    React.createElement("code", null, "enableVirtualization"),
                    " property to true. When virtualization is enabled, MultiSelect doesn't render the entire suggestion data source on initial component rendering. It loads the N number of items in the popup on initial rendering and the remaining set number of items will load while scrolling. Virtualization works with both local and remote data."),
                React.createElement("p", null,
                    "To perform the virtualization feature in the MultiSelect, the ",
                    React.createElement("code", null, "VirtualScroll"),
                    " module has to be injected at the application level."))));
    };
    return Default;
}(sample_base_1.SampleBase));
exports.Default = Default;

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/src/multi-select/virtual-scroll.vue
<template>
<div>
    <div class="control-section col-lg-9">
    <div class="control-wrapper">
        <label class="h4">Local Data</label>
        <ejs-multiselect id='local' ref='localObj' :dataSource='itemData' :mode='boxMode' placeholder='e.g Item 1' :fields='fields' :allowFiltering='allowFiltering' :allowCustomValue='allowCustomValue' :hideSelectedItem='hideSelectedItem' :closePopupOnSelect='closePopupOnSelect' :enableVirtualization='true' popupHeight="200px"></ejs-multiselect>
    </div>
    <div class="control-wrapper">
        <label class="h4">Remote Data</label>
        <ejs-multiselect id='remote' ref='remoteObj' :dataSource='data' :mode='delimiterMode' placeholder='e.g OrderID' :fields='customerfields' :allowFiltering='allowFiltering' :allowCustomValue='allowCustomValue' :hideSelectedItem='hideSelectedItem' :closePopupOnSelect='closePopupOnSelect' :enableVirtualization='true' popupHeight="200px"></ejs-multiselect>
    </div>
    <div class="control-wrapper">
        <label class="h4">Default Values</label>
        <ejs-multiselect id='default' ref='defaultObj' :dataSource='itemData' :value='chipValue' :mode='defaultMode' placeholder='e.g Item 1' :fields='fields' :allowFiltering='allowFiltering' :allowCustomValue='allowCustomValue' :hideSelectedItem='hideSelectedItem' :closePopupOnSelect='closePopupOnSelect' :enableVirtualization='true' popupHeight="200px"></ejs-multiselect>
    </div>
    <div class="control-wrapper">
        <label class="h4">Grouping</label>
        <ejs-multiselect id='group' ref='groupObj' :dataSource='itemData' :mode='multiMode' placeholder='e.g Item 1' :enableSelectionOrder='enableSelectionOrder' :fields='groupfields' :allowFiltering='allowFiltering' :allowCustomValue='allowCustomValue' :enableVirtualization='true' popupHeight="200px"></ejs-multiselect>
    </div>
    <div class="control-wrapper">
        <label class="h4">Template</label>
        <ejs-multiselect id='template' ref='templateObj' :dataSource='itemData' :mode='defaultMode' placeholder='e.g Item 1' :fields='fields' :allowFiltering='allowFiltering' :allowCustomValue='allowCustomValue' :hideSelectedItem='hideSelectedItem' :closePopupOnSelect='closePopupOnSelect' :enableVirtualization='true' popupHeight="200px" :headerTemplate="'hTemplate'" :itemTemplate="'iTemplate'" :valueTemplate="'vTemplate'">
            <template v-slot:hTemplate="{data}">
                <div class="header"><span style="margin-left:17px">Items Info</span></div>
              </template>
              <template v-slot:iTemplate="{data}">
                <div class="ename" style="height: 40px"> {{data.text}}  </div>
              </template>
              <template v-slot:vTemplate="{data}">
                <div class="name"> {{data.text}} </div>
              </template>
        </ejs-multiselect>
    </div>
</div>
<div class="col-lg-3 property-section">
    <div id="property" title="Properties">
        <table id="property" title="Properties">
            <tbody>
                <tr>
                    <td style="width: 50%;">
                        <div>
                            <ejs-checkbox ref="checkboxInstance1" label="AllowFiltering" :checked="true" :change="onChange"></ejs-checkbox>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td style="width: 50%;">
                        <div>
                            <ejs-checkbox ref="checkboxInstance2" label="AllowCustomValue" :checked="true" :change="onChangeCustom"></ejs-checkbox>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td style="width: 50%;">
                        <div>
                            <ejs-checkbox ref="checkboxInstance3" label="HideSelectedItem" :checked="true" :change="onChangeHide"></ejs-checkbox>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td style="width: 50%;">
                        <div>
                            <ejs-checkbox ref="checkboxInstance4" label="ClosePopupOnSelect" :checked="true" :change="onChangeClose"></ejs-checkbox>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
    <div id="action-description">
        <p>This example demonstrates the virtualization support of the MultiSelect. The component has 150 items bound to it; however, when you open the suggestion list, only few items are loaded based on the popup height, and the remaining items are loaded while scrolling.</p>
    </div>

    <div id="description">
        <p>The <code>MultiSelect</code> component supports virtualization, which improves UI performance for large amounts of data. To enable virtualization, set the <code>enableVirtualization</code> property to true. When virtualization is enabled, ComboBox doesn't render the entire suggestion data source on initial component rendering. It loads the N number of items in the popup on initial rendering and the remaining set number of items will load while scrolling.
            Virtualization works with both local and remote data.</p>
        <p>To perform the virtualization feature in DropDownList, the <code>VirtualSCroll</code> module
            have to be injected in the application end.</p>
    </div>
</div>
</template>
<style scoped>
    .control-section .control-wrapper {
        width: 80%;
        margin: 0 auto;
        width: 250px;
        padding-top: 15px;
        height: 90px !important;
    } 

    .control-wrapper .h4 {
      font-size: 16px;
      margin: 0 0 10px;
      font-weight: bold;
  }

    .header {
        font-weight: 600;
        color: rgba(0, 0, 0, .54);
        height: 48px;
        padding: 15px 0 0 16px;
        font-size: 16px;
        background-color: #f5f5f5;
    }

    /* custom code start*/
    .fabric .header {
        background-color: #fff;
        border-bottom: 1px solid #ccc;
        color: #0078d7;
        font-weight: 400;
    }

    .fluent-dark .header,
    .fluent2-dark .header,
    .fluent2-highcontrast .header {
        background: #252423;
        color: #2899F5;
    }

    .bootstrap5-dark .header {
        background: #343A40;
        color: #7B848D;
    }

    .fluent .header{
         color: #2899F5;
    }

    .tailwind-dark .header,
    .tailwind3-dark .header {
        background: #374151;
        color: rgb(255, 255, 255);
    }

    .material3-dark .header,
    .material-dark .header {
        background: rgb(66, 66, 66);
        color: rgb(255, 255, 255);
    }

    .fabric-dark .header {
        background: rgb(40, 39, 39);
        color: rgb(255, 255, 255);
    }

    .bootstrap-dark .header {
        background: rgb(49, 49, 49);
        color: rgb(255, 255, 255);
    }

    .bootstrap .header {
        background-color: #f5f5f5;
        border-bottom: 1px solid #ccc;
        color: #777;
        font-family: "Helvetica Neue", "Helvetica", "Arial", "sans-serif";
        font-weight: 600;
        font-size: 15px;
        height: 48px;
        padding: 15px 0 0 16px;
    }

    .highcontrast .header {
        color: #fff;
        background-color: #000;
    }
    
    .bootstrap4 .header {
        color: #6c757d;
    }
    
    .e-bigger.bootstrap .header {
        height: 44px;
        font-size: 13px;
    }
</style>
<script>
import { DropDownListComponent, VirtualScroll, MultiSelectComponent, CheckBoxSelection } from "@syncfusion/ej2-vue-dropdowns";
import { CheckBoxComponent } from "@syncfusion/ej2-vue-buttons";
import { Query, DataManager, UrlAdaptor } from '@syncfusion/ej2-data';
let records = [];
function dataSource() {
    for (var i = 1; i <= 150; i++) {
        var item = {};
        item.id = 'id' + i;
        item.text = "Item ".concat(i);
        var randomGroup = Math.floor(Math.random() * 4) + 1;
        switch (randomGroup) {
            case 1:
                item.group = 'Group A';
                break;
            case 2:
                item.group = 'Group B';
                break;
            case 3:
                item.group = 'Group C';
                break;
            case 4:
                item.group = 'Group D';
                break;
            default:
                break;
        }
        records.push(item);
    }
}
dataSource();
var remoteData = new DataManager({
    url: 'https://ej2services.syncfusion.com/production/web-services/api/VirtualDropdownData',
    adaptor: new UrlAdaptor,
    crossDomain: true
});

//Component registeration
export default {
    name: 'App',
    components: {
        'ejs-multiselect': MultiSelectComponent,
        'ejs-checkbox': CheckBoxComponent,
        "ejs-dropdownlist": DropDownListComponent,
    },
    data (){
        return {
            itemData: records,
            data: remoteData,
            defaultMode: 'Default',
            boxMode: 'Box',
            delimiterMode: 'Delimiter',
            multiMode: 'CheckBox',
            allowFiltering: true,
            allowCustomValue: true,
            hideSelectedItem: true,
            closePopupOnSelect: true,
            enableSelectionOrder: false,
            chipValue: ['id10', 'id50', 'id100', "custom"],
            fields: { value: 'id', text: 'text' },
            customerfields: { text: 'OrderID', value: 'OrderID' },
            groupfields: { groupBy: 'group', text: 'text', value: 'id' },
        }
    },
    methods: {
        onChange: function() {
            var checkboxObj = this.$refs.checkboxInstance1.ej2Instances;
            this.$refs.localObj.ej2Instances.allowFiltering = checkboxObj.checked;
            this.$refs.remoteObj.ej2Instances.allowFiltering = checkboxObj.checked;
            this.$refs.defaultObj.ej2Instances.allowFiltering = checkboxObj.checked;
            this.$refs.groupObj.ej2Instances.allowFiltering = checkboxObj.checked;
            this.$refs.templateObj.ej2Instances.allowFiltering = checkboxObj.checked;
        },
       onChangeCustom: function() {
            var checkboxObj = this.$refs.checkboxInstance2.ej2Instances;
            this.$refs.localObj.ej2Instances.allowCustomValue = checkboxObj.checked;
            this.$refs.remoteObj.ej2Instances.allowCustomValue = checkboxObj.checked;
            this.$refs.defaultObj.ej2Instances.allowCustomValue = checkboxObj.checked;
            this.$refs.groupObj.ej2Instances.allowCustomValue = checkboxObj.checked;
            this.$refs.templateObj.ej2Instances.allowCustomValue = checkboxObj.checked;
        },
        onChangeHide: function() {
            var checkboxObj = this.$refs.checkboxInstance3.ej2Instances;
            this.$refs.localObj.ej2Instances.hideSelectedItem = checkboxObj.checked;
            this.$refs.remoteObj.ej2Instances.hideSelectedItem = checkboxObj.checked;
            this.$refs.defaultObj.ej2Instances.hideSelectedItem = checkboxObj.checked;
            this.$refs.templateObj.ej2Instances.hideSelectedItem = checkboxObj.checked;
        },
        onChangeClose: function() {
            var checkboxObj = this.$refs.checkboxInstance4.ej2Instances;
            this.$refs.localObj.ej2Instances.closePopupOnSelect = checkboxObj.checked;
            this.$refs.remoteObj.ej2Instances.closePopupOnSelect = checkboxObj.checked;
            this.$refs.defaultObj.ej2Instances.closePopupOnSelect = checkboxObj.checked;
            this.$refs.templateObj.ej2Instances.closePopupOnSelect = checkboxObj.checked;
        },
    },
    provide: {
        multiselect: [CheckBoxSelection, VirtualScroll]
    }
    
}
</script>
