// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/src/pdfviewer/esigning-pdf-forms.vue
<template>
    <div>
        <div class="e-pv-e-sign control-section">
            <div class="e-pv-e-sign-property-sec">
                <div class="e-pv-e-sign-property-sec">
                    <ejs-toolbar id="e-pv-e-sign-toolbar-user-viewer">
                        <e-items>
                            <e-item template="template">
                                <template v-slot:template>
                                    <div id='e-pv-e-sign-user-field' style="width: 200px; height: 37px; left: 0px">
                                        <div class='e-pv-e-sign-user-dropdown'>
                                            <ejs-dropdownlist ref="userMenu" :dataSource="userDetails" :fields="fields"
                                                :index=0 :itemTemplate="'iTemplate'" :valueTemplate="'vTemplate'"
                                                popupHeight="450px" popupWidth="200px" :select="userChange">
                                                <template v-slot:iTemplate="{ data }">
                                                    <div style="display: flex;">
                                                        <img class="e-pv-e-sign-user-profile"
                                                            :src="`src/pdfviewer/images/employees/${data.Eimg}.png`"
                                                            :style="{ height: '33px', marginTop: '7px', marginLeft: '3px', borderRadius: '50%', border: `1px solid ${data.Mail === 'andrew@mycompany.com' ? 'red' : 'green'}`, }" />
                                                        <div>
                                                            <div class="e-pv-e-sign-user-name"
                                                                style="font-size: 14px; height: 18px;">{{ data.Name }}
                                                            </div>
                                                            <div class="e-pv-e-sign-user-mail" style="font-size: 12px;">
                                                                {{ data.Mail }}</div>
                                                        </div>
                                                    </div>
                                                </template>
                                                <template v-slot:vTemplate="{ data }">
                                                    <div class="e-pv-e-sign-value-template" style="display: flex;">
                                                        <img class="e-pv-e-sign-user-profile"
                                                            :src="`src/pdfviewer/images/employees/${data.Eimg}.png`"
                                                            :style="{ height: '30px', borderRadius: '50%',marginLeft: '3px', border: `1px solid ${data.Mail === 'andrew@mycompany.com' ? 'red' : 'green'}` }" />
                                                        <div>
                                                            <div class="e-pv-e-sign-user-name"
                                                                style="font-size: 12px; margin-left: 12px;">{{ data.Name
                                                                }}</div>
                                                            <div class="e-pv-e-sign-user-mail"
                                                                style="font-size: 10px; margin-left: 11px;">{{ data.Mail
                                                                }}</div>
                                                        </div>
                                                    </div>
                                                </template>
                                            </ejs-dropdownlist>
                                        </div>
                                    </div>
                                </template>
                            </e-item>
                            <e-item align="Right" template="buttonComponent">
                                <template v-slot:buttonComponent>
                                    <ejs-button ref="btnElement" id="e-pv-e-sign-finishbtn" cssClass="e-outline"
                                        :onClick="finishSigning" :disabled="true">Finish Signing</ejs-button>
                                </template>
                            </e-item>
                        </e-items>
                    </ejs-toolbar>
                </div>
            </div>
            <ejs-pdfviewer ref="viewer" id="container" :documentPath="documentPath" :zoomMode="zoomMode" :resourceUrl="resourceUrl"
                :enableNavigationToolbar="false" :enableAnnotationToolbar = "false"
                :enableToolbar="false" :enableFormDesignerToolbar="false" :documentLoad="documentLoad"
                :formFieldPropertiesChange="fieldChange" :downloadEnd="downloadEnd" style="height: 640px;">
            </ejs-pdfviewer>
            <div id="e-pv-e-sign-dialog-target">
                <ejs-dialog ref="dialogInstance" :minHeight="'50px'" :isModal="true" :width="'350px'" :buttons="buttons"
                    :visible="status" :target="'#e-pv-e-sign-dialog-target'"></ejs-dialog>
            </div>
        </div>
        <div id="action-description">
            <p>
                This sample enables two different users to sign the document. The first
                user must fill out and sign their designated fields, which are visible
                only to them. Once the first user has completed their section, the
                second user can be selected to fill out and sign their own fields. After
                both users have signed, the document can be finalized.
            </p>
        </div>
        <div id="description">
            <p>
                More information on the PDF Viewer instantiation can be found in this
                <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/pdfviewer/getting-started">
                    documentation section
                </a>
            </p>
        </div>
    </div>
</template>

<script>
import { PdfViewerComponent, Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormFields, FormDesigner, PageOrganizer, } from '@syncfusion/ej2-vue-pdfviewer';
import { ButtonComponent } from '@syncfusion/ej2-vue-buttons';
import { DropDownListComponent } from '@syncfusion/ej2-vue-dropdowns';
import { ToolbarComponent, ItemDirective, ItemsDirective } from '@syncfusion/ej2-vue-navigations';
import { DialogComponent } from '@syncfusion/ej2-vue-popups';
var viewer;
var fileName = 'eSign_filling.pdf';
export default {
    components: {
        "ejs-pdfviewer": PdfViewerComponent,
        "ejs-button": ButtonComponent,
        "ejs-dropdownlist": DropDownListComponent,
        "ejs-dialog": DialogComponent,
        "ejs-toolbar": ToolbarComponent,
        "e-items": ItemsDirective,
        "e-item": ItemDirective
    },
    data() {
        return {
            documentPath: 'https://cdn.syncfusion.com/content/pdf/eSign_filling.pdf',
            resourceUrl: 'https://cdn.syncfusion.com/ej2/27.2.2/dist/ej2-pdfviewer-lib',
            zoomMode: 'FitToPage',
            status: false,
            preventChange: false,
            currentUser: 'andrew@mycompany.com',
            borderColor: '2px solid red',
            finishedBackground: '#daeaf7ff',
            anneBackground: '#eff7ef',
            andrewBackground: '#ffefef',
            buttons: [
                {
                    click: this.dlgButtonClick,
                    buttonModel: {
                        content: 'OK',
                        isPrimary: true,
                    },
                },
            ],
            userDetails: [
                { Name: 'Andrew Fuller', Eimg: 'profile1', Mail: 'andrew@mycompany.com', fieldIds: [] },
                { Name: 'Anne Dodsworth', Eimg: 'profile2', Mail: 'anne@mycompany.com', fieldIds: [] },
            ],
            fields: { text: 'Mail', value: 'Eimg', fieldIds: 'fieldIds' },
        };
    },
    provide: {
        PdfViewer: [Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormFields, FormDesigner, PageOrganizer]
    },
    methods: {

        finishSigning() {
            viewer = this.$refs.viewer.ej2Instances;
            var url = "https://ej2services.syncfusion.com/production/web-services/api/pdfviewer/FlattenDownload";
            for (const formField of viewer.formFieldCollections) {
                viewer.formDesignerModule.updateFormField(formField, { backgroundColor: this.finishedBackground });
            }
            viewer.saveAsBlob().then(function (value) {
            let reader = new FileReader();
            reader.readAsDataURL(value);
            reader.onload = function (e) {
                const base64String = e.target?.result.toString();
                const xhr = new XMLHttpRequest();
                xhr.open('POST', url, true);
                xhr.setRequestHeader('Content-type', 'application/json; charset=UTF-8');
                const requestData = JSON.stringify({ base64String: base64String });
                xhr.onload = function () {
                    if (xhr.status === 200) {
                        const blobUrl = createBlobUrl(xhr.responseText.split('base64,')[1], 'application/pdf');
                        downloadDocument(blobUrl);
                        viewer.load(xhr.responseText, null);
                    }
                    else {
                        console.error('Download failed:', xhr.statusText);
                    }
                };
                xhr.onerror = function () {
                    console.error('An error occurred during the download:', xhr.statusText);
                };
                xhr.send(requestData);
            };
        }).catch(function (error) {
            console.error('Error saving Blob:', error);
        });
         this.$refs.btnElement.ej2Instances.disabled = true;
         this.$refs.userMenu.ej2Instances.enabled = false;
    },
        updateUserFormField() {
            var viewer = this.$refs.viewer.ej2Instances;
            const otherFormFieldDetails = viewer.formFieldCollections.filter(formField => formField.customData.author === 'anne');
            const currentFormFieldDetails = viewer.formFieldCollections.filter(formField => formField.customData.author === 'andrew');
            if (this.currentUser === 'andrew@mycompany.com') {
                otherFormFieldDetails.forEach(field => {
                    if (field.value !== '') {
                        const mainFieldUpdateData = {
                            backgroundColor: this.finishedBackground,
                            isReadOnly: true,
                        };
                        viewer.formDesigner.updateFormField(field, mainFieldUpdateData);
                        currentFormFieldDetails.forEach(currentField => {
                            const currentFieldUpdateData = {
                                backgroundColor: this.andrewBackground,
                                isReadOnly: true,
                            };
                            viewer.formDesigner.updateFormField(currentField, currentFieldUpdateData);
                        });
                    } else {
                        currentFormFieldDetails.forEach(currentField => {
                            const currentFieldUpdateData = {
                                backgroundColor: this.andrewBackground,
                            };
                            viewer.formDesigner.updateFormField(currentField, currentFieldUpdateData);
                        });
                    }
                    const otherUserField = document.getElementById(field.id + '_content_html_element');
                    if (otherUserField) {
                        const currentFormField = viewer.formFieldCollections.find(formField => formField.id === field.id);
                        if (currentFormField.type !== 'DropDown' && otherUserField) {
                            if (!currentFormField.value) {
                                viewer.formDesignerModule.updateFormField(currentFormField, { visibility: 'hidden' });
                            }
                        } else {
                            if (currentFormField.value.length !== 0 && otherUserField) {
                                viewer.formDesignerModule.updateFormField(currentFormField, { visibility: 'hidden' });
                            }
                        }
                    }
                });
            } else {
                this.validation(currentFormFieldDetails);
                if (!this.status) {
                    currentFormFieldDetails.forEach(field => {
                        const currentFieldUpdateData = {
                            backgroundColor: this.finishedBackground,
                            isReadOnly: true,
                        };
                        viewer.formDesigner.updateFormField(field, currentFieldUpdateData);
                        otherFormFieldDetails.forEach(otherField => {
                            const otherFieldUpdateData = {
                                backgroundColor: this.anneBackground,
                                isReadOnly: false,
                            };
                            viewer.formDesigner.updateFormField(otherField, otherFieldUpdateData);
                        });
                    });
                    otherFormFieldDetails.forEach(field => {
                        viewer.formDesignerModule.updateFormField(field, { visibility: 'visible' });
                    });
                }
            }
        },
        dlgButtonClick() {
            this.status = false;
            this.$refs.dialogInstance.hide();
        },
        validation(args) {
            let errorMessage = 'Required Field(s): ';
            const forms = args;
            let flag = false;
            let isAllFieldFilled = true;
            let radioGroupName = '';

            for (let i = 0; i < forms.length; i++) {
                let text = "";

                if (forms[i].isRequired) {
                    switch (forms[i].type.toString()) {
                        case "Checkbox":
                            if (!forms[i].isChecked) {
                                text = forms[i].name;
                            }
                            break;

                        case "RadioButton":
                            if (!flag) {
                                radioGroupName = forms[i].name;
                                if (forms[i].isSelected) {
                                    flag = true;
                                }
                            }
                            break;

                        case "DropdownList":
                            if (forms[i].value.length === 0) {
                                text = forms[i].name;
                            }
                            break;

                        default:
                            if (!forms[i].value || (typeof forms[i].newValue === 'string' && forms[i].newValue === "")) {
                                text = forms[i].name;
                            }
                            break;
                    }

                    if (text) {
                        errorMessage = errorMessage === "Required Field(s): " ? errorMessage + text : errorMessage + ", " + text;
                    }
                }
            }
            if (!flag && radioGroupName !== '') {
                if (errorMessage === 'Required Field(s): ') errorMessage += radioGroupName;
                else errorMessage += ', ' + radioGroupName;
                isAllFieldFilled = false;
            }
            if (errorMessage !== 'Required Field(s): ') {
                this.status = true;
                this.$refs.dialogInstance.ej2Instances.content = errorMessage;
                this.$refs.dialogInstance.ej2Instances.show();
                this.preventChange = true;
            } else {
                this.status = false;
                this.preventChange = false;
            }
        },
        fieldChange(args) {
            let errorMessage = 'Required Field(s): ';
            const forms = this.$refs.viewer.ej2Instances.formFieldCollections;
            let flag = false;
            let isAllFieldFilled = true;
            let radioGroupName = '';
            forms.forEach(form => {
                let text = "";

                if (form.isRequired) {
                    if (form.type.toString() === "Checkbox" && !form.isChecked) {
                        text = form.name;
                        isAllFieldFilled = false;
                    } else if (form.type === "RadioButton" && !flag) {
                        radioGroupName = form.name;
                        if (form.isSelected) {
                            flag = true;
                        }
                    } else if (form.type.toString() !== "Checkbox" && form.type !== "RadioButton" && (!form.value || (typeof args.newValue === 'string' && args.newValue === ""))) {
                        text = form.name;
                        isAllFieldFilled = false;
                    } else if (form.type.toString() === "DropdownList" && form.value.length === 0) {
                        text = form.name;
                        isAllFieldFilled = false;
                    }

                    if (text) {
                        errorMessage = errorMessage === "Required Field(s): " ? errorMessage + text : errorMessage + ", " + text;
                    }
                }
            });
            if (!flag && radioGroupName !== '') {
                if (errorMessage === 'Required Field(s): ') errorMessage += radioGroupName;
                else errorMessage += ', ' + radioGroupName;
                isAllFieldFilled = false;
            }
            if (isAllFieldFilled) {
                this.$refs.btnElement.ej2Instances.disabled = false;
            } else {
                this.$refs.btnElement.ej2Instances.disabled = true;
            }
        },
        userChange(args) {
            this.currentUser = args.itemData.Mail;
            if (args.itemData.Mail === 'andrew@mycompany.com') {
                this.borderColor = '1px solid red';
            } else {
                this.borderColor = '1px solid green';
            }
            this.updateUserFormField();
            if (this.preventChange) {
                args.cancel = true;
            }
        },
        documentLoad() {
            var viewer = this.$refs.viewer.ej2Instances;
            viewer.designerMode = false;
            this.updateUserFormField();
        },
    }  
};

function createBlobUrl(base64String, contentType)
  {
    const sliceSize = 512;
    const byteCharacters = atob(base64String);
    const byteArrays = [];
    for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
        const slice = byteCharacters.slice(offset, offset + sliceSize);
        const byteNumbers = new Array(slice.length);
        for (let i = 0; i < slice.length; i++) {
            byteNumbers[parseInt(i.toString(), 10)] = slice.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);
        byteArrays.push(byteArray);
    }
    const blob = new Blob(byteArrays, { type: contentType });
    return blob;
  };
  
  function downloadDocument(blobUrl)
  {
    const Url = URL || webkitURL;
    blobUrl = Url.createObjectURL(blobUrl);
    viewer.fileName = fileName;
    const anchorElement = document.createElement('a');
    if (anchorElement.click) {
        (anchorElement).href = blobUrl;
        (anchorElement).target = '_parent';
        if ('download' in anchorElement) {
            const downloadFileName = viewer.fileName || 'downloadedFile.pdf';
            if (downloadFileName) {
                if (downloadFileName.endsWith('.pdf')) {
                    (anchorElement).download = downloadFileName;
                }
                else {
                    const splitPdf = downloadFileName.split('.pdf')[0] + '.pdf';
                    (anchorElement).download = splitPdf;
                }
            }
            else {
                (anchorElement).download = 'Default.pdf';
            }
        }
        (document.body || document.documentElement).appendChild(anchorElement);
        anchorElement.click();
    }
    else {
        if (window.top === window &&
            blobUrl.split('#')[0] === window.location.href.split('#')[0]) {
                const padCharacter = blobUrl.indexOf('?') === -1 ? '?' : '&';
                blobUrl = blobUrl.replace(/#|$/, padCharacter + '$&');
        }
        window.open(blobUrl, '_parent');
    }
  };
</script>

<style>
#e-pv-e-sign-toolbar_user_viewer {
    z-index: 1001;
    width: 100% !important;
    height: 48px !important;
    box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.30);
}

#e-pv-e-sign-finishbtn {
    width: 115px !important;
    height: 28px;
    padding: 0;
    font-size: 12px;
    flex-shrink: 0;
    border-radius: 16px;
}
.e-pv-e-sign-user-dropdown> :first-child {
    border: none !important;
}
</style>

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/pdfviewer/esigning-pdf-forms.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ESigningPdfForms = void 0;
var React = require("react");
var ej2_react_pdfviewer_1 = require("@syncfusion/ej2-react-pdfviewer");
var sample_base_1 = require("../common/sample-base");
require("./pdf.component.css");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var ej2_react_navigations_1 = require("@syncfusion/ej2-react-navigations");
var ej2_react_popups_1 = require("@syncfusion/ej2-react-popups");
var ej2_react_buttons_1 = require("@syncfusion/ej2-react-buttons");
var ESigningPdfForms = /** @class */ (function (_super) {
    __extends(ESigningPdfForms, _super);
    function ESigningPdfForms() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.currentUser = 'andrew@mycompany.com';
        _this.status = false;
        _this.preventChange = false;
        _this.borderColor = '1px solid red';
        _this.finishedBackground = '#daeaf7ff';
        _this.opacityValue = '0.5';
        _this.andrewBackground = '#eff7ef';
        _this.anneBackground = '#ffefef';
        _this.buttons = [
            {
                buttonModel: {
                    content: 'OK',
                    isPrimary: true,
                },
                'click': function () {
                    _this.status = false;
                    _this.dialogInstance.hide();
                }
            }
        ];
        _this.userDetails = [
            { Name: 'Andrew Fuller', Eimg: 'profile1', Mail: 'andrew@mycompany.com', fieldIds: [] },
            { Name: 'Anne Dodsworth', Eimg: 'profile2', Mail: 'anne@mycompany.com', fieldIds: [] },
        ];
        _this.fields = { text: 'Mail', value: 'Eimg', fieldIds: 'fieldIds' };
        _this.dropdownComponent = function () {
            return (React.createElement("div", { id: 'e-pv-e-sign-user-field', style: { width: '245px', height: '37px', left: '0px' } },
                React.createElement("div", { className: 'e-pv-e-sign-user-dropdown' },
                    React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { ref: function (scope) { _this.userMenu = scope; }, id: 'this.userMenu', select: _this.userChange, index: 0, popupWidth: '215px', dataSource: _this.userDetails, width: '200px', fields: _this.fields, itemTemplate: _this.itemTemplate, valueTemplate: _this.valueTemplate }))));
        };
        _this.itemTemplate = function (data) {
            return (React.createElement("div", { style: { display: 'flex' } },
                React.createElement("img", { className: "e-pv-e-sign-empImage", style: { maxHeight: '35px', marginTop: '7px', marginLeft: '4px', borderRadius: '50%', border: "1px solid ".concat(data.Mail === 'andrew@mycompany.com' ? 'red' : 'green') }, src: 'src/pdfviewer/images/employees/' + data['Eimg'] + '.png' }),
                React.createElement("div", null,
                    React.createElement("div", { className: "e-pv-e-sign-ename", style: { height: '18px', fontSize: '14px' } },
                        " ",
                        data.Name,
                        " "),
                    React.createElement("div", { className: "e-pv-e-sign-job", style: { fontSize: '12px' } },
                        " ",
                        data.Mail,
                        " "))));
        };
        _this.valueTemplate = function (data) {
            return (React.createElement("div", { className: "e-pv-e-sign valueTemplate", style: { display: 'flex' } },
                React.createElement("img", { className: "e-pv-e-sign-value", style: { borderRadius: '20px', marginLeft: '3px', border: _this.borderColor }, src: 'src/pdfviewer/images/employees/' + data['Eimg'] + '.png', height: "30px", width: "30px", alt: "employee" }),
                React.createElement("div", null,
                    React.createElement("div", { className: "e-pv-e-sign-name", style: { fontSize: '12px', marginLeft: '12px', alignContent: 'center' } },
                        " ",
                        data.Name,
                        " "),
                    React.createElement("div", { className: "e-pv-e-sign-job", style: { fontSize: '10px', marginLeft: '11px', alignContent: 'center' } },
                        " ",
                        data.Mail,
                        " "))));
        };
        _this.buttonComponent = function () {
            return (React.createElement(ej2_react_buttons_1.ButtonComponent, { ref: function (scope) { _this.btnElement = scope; }, id: 'e-pv-e-sign-finishbtn', cssClass: "e-outline", onClick: _this.finishSigning, created: _this.btnCreated }, "Finish Signing"));
        };
        _this.btnCreated = function () {
            _this.btnElement.disabled = true;
        };
        _this.finishSigning = function (args) {
            var _a;
            for (var _i = 0, _b = _this.viewer.formFieldCollections; _i < _b.length; _i++) {
                var formField = _b[_i];
                (_a = _this.viewer) === null || _a === void 0 ? void 0 : _a.formDesignerModule.updateFormField(formField, { backgroundColor: _this.finishedBackground });
            }
            var url = "https://ej2services.syncfusion.com/production/web-services/api/pdfviewer/FlattenDownload";
            _this.viewer.saveAsBlob().then(function (blob) {
                return _this.convertBlobToBase64(blob);
            }).then(function (base64String) {
                var xhr = new XMLHttpRequest();
                xhr.open('POST', url, true);
                xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');
                var requestData = JSON.stringify({ base64String: base64String });
                xhr.onload = function () {
                    if (xhr.status === 200) {
                        var responseBase64 = xhr.responseText.split('base64,')[1];
                        if (responseBase64) {
                            var blob = _this.createBlobFromBase64(responseBase64, 'application/pdf');
                            var blobUrl = URL.createObjectURL(blob);
                            _this.downloadDocument(blobUrl);
                            _this.viewer.load(xhr.responseText, null);
                            _this.btnElement.disabled = true;
                            _this.userMenu.enabled = false;
                        }
                        else {
                            console.error('Invalid base64 response.');
                        }
                    }
                    else {
                        console.error('Download failed:', xhr.statusText);
                    }
                };
                xhr.onerror = function () {
                    console.error('An error occurred during the download:', xhr.statusText);
                };
                xhr.send(requestData);
            }).catch(function (error) {
                console.error('Error saving Blob:', error);
            });
        };
        _this.convertBlobToBase64 = function (blob) {
            return new Promise(function (resolve, reject) {
                var reader = new FileReader();
                reader.readAsDataURL(blob);
                reader.onloadend = function () {
                    if (typeof reader.result === 'string') {
                        resolve(reader.result);
                    }
                    else {
                        reject(new Error('Failed to convert Blob to Base64'));
                    }
                };
                reader.onerror = function (error) { return reject(error); };
            });
        };
        _this.createBlobFromBase64 = function (base64String, contentType) {
            var sliceSize = 512;
            var byteCharacters = atob(base64String);
            var byteArrays = [];
            for (var offset = 0; offset < byteCharacters.length; offset += sliceSize) {
                var slice = byteCharacters.slice(offset, offset + sliceSize);
                var byteNumbers = new Array(slice.length);
                for (var i = 0; i < slice.length; i++) {
                    byteNumbers[i] = slice.charCodeAt(i);
                }
                var byteArray = new Uint8Array(byteNumbers);
                byteArrays.push(byteArray);
            }
            return new Blob(byteArrays, { type: contentType });
        };
        _this.downloadDocument = function (blobUrl) {
            var anchorElement = document.createElement('a');
            anchorElement.href = blobUrl;
            anchorElement.target = '_parent';
            var downloadFileName = _this.viewer.fileName || 'default.pdf';
            anchorElement.download = downloadFileName.endsWith('.pdf')
                ? downloadFileName
                : "".concat(downloadFileName.split('.pdf')[0], ".pdf");
            document.body.appendChild(anchorElement);
            anchorElement.click();
            document.body.removeChild(anchorElement);
            URL.revokeObjectURL(blobUrl);
        };
        _this.updateUserFormField = function () {
            var otherFormFieldDetails = _this.viewer.formFieldCollections.filter(function (formField) { return formField.customData.author === "anne"; });
            var currentFormFieldDetails = _this.viewer.formFieldCollections.filter(function (formField) { return formField.customData.author === "andrew"; });
            if (_this.currentUser === 'andrew@mycompany.com') {
                otherFormFieldDetails.forEach(function (field) {
                    if (field.value !== '') {
                        var mainFieldUpdateData = {
                            backgroundColor: _this.finishedBackground,
                            isReadOnly: true
                        };
                        _this.viewer.formDesigner.updateFormField(field, mainFieldUpdateData);
                        currentFormFieldDetails.forEach(function (currentField) {
                            var currentFieldUpdateData = {
                                backgroundColor: _this.andrewBackground,
                                isReadOnly: true
                            };
                            _this.viewer.formDesigner.updateFormField(currentField, currentFieldUpdateData);
                        });
                    }
                    else {
                        currentFormFieldDetails.forEach(function (currentField) {
                            var currentFieldUpdateData = {
                                backgroundColor: _this.andrewBackground,
                            };
                            _this.viewer.formDesigner.updateFormField(currentField, currentFieldUpdateData);
                        });
                    }
                    var otherUserField = document.getElementById(field.id + '_content_html_element');
                    if (otherUserField) {
                        var currentFormField = _this.viewer.formFieldCollections.find(function (formField) { return formField.id === field.id; });
                        if (currentFormField.type !== 'DropDown' && otherUserField) {
                            if (!currentFormField.value) {
                                _this.viewer.formDesignerModule.updateFormField(currentFormField, { visibility: 'hidden' });
                            }
                        }
                        else {
                            if (currentFormField.value.length !== 0 && otherUserField) {
                                _this.viewer.formDesignerModule.updateFormField(currentFormField, { visibility: 'hidden' });
                            }
                        }
                    }
                });
            }
            else {
                _this.validation(currentFormFieldDetails);
                if (!_this.status) {
                    currentFormFieldDetails.forEach(function (field) {
                        var currentFieldUpdateData = {
                            backgroundColor: _this.finishedBackground,
                            isReadOnly: true
                        };
                        _this.viewer.formDesigner.updateFormField(field, currentFieldUpdateData);
                        otherFormFieldDetails.forEach(function (otherField) {
                            var otherFieldUpdateData = {
                                backgroundColor: _this.anneBackground,
                                isReadOnly: false
                            };
                            _this.viewer.formDesigner.updateFormField(otherField, otherFieldUpdateData);
                        });
                    });
                    otherFormFieldDetails.forEach(function (field) {
                        _this.viewer.formDesignerModule.updateFormField(field, { visibility: 'visible' });
                    });
                }
            }
        };
        _this.validation = function (args) {
            var errorMessage = "Required Field(s): ";
            var forms = args;
            var flag = false;
            var radioGroupName = "";
            for (var i = 0; i < forms.length; i++) {
                var text = "";
                if (forms[i].isRequired) {
                    switch (forms[i].type.toString()) {
                        case "Checkbox":
                            if (!forms[i].isChecked) {
                                text = forms[i].name;
                            }
                            break;
                        case "RadioButton":
                            if (!flag) {
                                radioGroupName = forms[i].name;
                                if (forms[i].isSelected) {
                                    flag = true;
                                }
                            }
                            break;
                        case "DropdownList":
                            if (forms[i].value.length === 0) {
                                text = forms[i].name;
                            }
                            break;
                        default:
                            if (!forms[i].value || (typeof forms[i].newValue === 'string' && forms[i].newValue === "")) {
                                text = forms[i].name;
                            }
                            break;
                    }
                    if (text) {
                        errorMessage = errorMessage === "Required Field(s): " ? errorMessage + text : errorMessage + ", " + text;
                    }
                }
            }
            if (!flag && radioGroupName != "") {
                if (errorMessage == "Required Field(s): ")
                    errorMessage += radioGroupName;
            }
            if (errorMessage != "Required Field(s): ") {
                _this.status = true;
                _this.dialogInstance.content = errorMessage;
                _this.dialogInstance.show();
                _this.preventChange = true;
            }
            else {
                _this.status = false;
                _this.preventChange = false;
            }
        };
        _this.fieldChange = function (args) {
            var errorMessage = "Required Field(s): ";
            var forms = _this.viewer.formFieldCollections;
            var flag = false;
            var isAllFieldFilled = true;
            var radioGroupName = "";
            forms.forEach(function (form) {
                var text = "";
                if (form.isRequired) {
                    if (form.type.toString() === "Checkbox" && !form.isChecked) {
                        text = form.name;
                        isAllFieldFilled = false;
                    }
                    else if (form.type === "RadioButton" && !flag) {
                        radioGroupName = form.name;
                        if (form.isSelected) {
                            flag = true;
                        }
                    }
                    else if (form.type.toString() !== "Checkbox" && form.type !== "RadioButton" && (!form.value || (typeof args.newValue === 'string' && args.newValue === ""))) {
                        text = form.name;
                        isAllFieldFilled = false;
                    }
                    else if (form.type.toString() === "DropdownList" && form.value.length === 0) {
                        text = form.name;
                        isAllFieldFilled = false;
                    }
                    if (text) {
                        errorMessage = errorMessage === "Required Field(s): " ? errorMessage + text : errorMessage + ", " + text;
                    }
                }
            });
            if (!flag && radioGroupName != "") {
                if (errorMessage == "Required Field(s): ")
                    errorMessage += radioGroupName;
                else
                    errorMessage += ", " + radioGroupName;
                isAllFieldFilled = false;
            }
            if (isAllFieldFilled) {
                _this.btnElement.disabled = false;
            }
            else {
                _this.btnElement.disabled = true;
            }
        };
        _this.userChange = function (args) {
            _this.currentUser = args.itemData.Mail;
            if (args.itemData.Mail == "andrew@mycompany.com") {
                _this.borderColor = '1px solid red';
            }
            else {
                _this.borderColor = '1px solid green';
            }
            _this.updateUserFormField();
            if (_this.preventChange) {
                args.cancel = true;
            }
        };
        _this.documentLoad = function () {
            _this.viewer.designerMode = false;
            _this.updateUserFormField();
        };
        return _this;
    }
    ESigningPdfForms.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", null,
            React.createElement("div", null,
                React.createElement("div", { className: 'e-pv-e-sign control-section' },
                    React.createElement(ej2_react_navigations_1.ToolbarComponent, { id: "e-pv-e-sign-toolbar-user-viewer" },
                        React.createElement(ej2_react_navigations_1.ItemsDirective, null,
                            React.createElement(ej2_react_navigations_1.ItemDirective, { template: this.dropdownComponent }),
                            React.createElement(ej2_react_navigations_1.ItemDirective, { align: 'Right', template: this.buttonComponent }))),
                    React.createElement(ej2_react_pdfviewer_1.PdfViewerComponent, { ref: function (scope) { _this.viewer = scope; }, id: "container", enableNavigationToolbar: false, enableAnnotationToolbar: false, enableToolbar: false, enableFormDesignerToolbar: false, documentPath: "https://cdn.syncfusion.com/content/pdf/eSign_filling.pdf", resourceUrl: "https://cdn.syncfusion.com/ej2/27.2.2/dist/ej2-pdfviewer-lib", zoomMode: "FitToPage", downloadFileName: 'eSign_filling.pdf', documentLoad: this.documentLoad, formFieldPropertiesChange: this.fieldChange, style: { 'height': '640px' } },
                        React.createElement(ej2_react_pdfviewer_1.Inject, { services: [ej2_react_pdfviewer_1.Toolbar, ej2_react_pdfviewer_1.Magnification, ej2_react_pdfviewer_1.Navigation, ej2_react_pdfviewer_1.LinkAnnotation, ej2_react_pdfviewer_1.BookmarkView, ej2_react_pdfviewer_1.ThumbnailView, ej2_react_pdfviewer_1.Print, ej2_react_pdfviewer_1.TextSelection, ej2_react_pdfviewer_1.TextSearch, ej2_react_pdfviewer_1.Annotation, ej2_react_pdfviewer_1.FormFields, ej2_react_pdfviewer_1.FormDesigner, ej2_react_pdfviewer_1.PageOrganizer] })),
                    React.createElement("div", { id: 'e-pv-e-sign-dialog-target' },
                        React.createElement(ej2_react_popups_1.DialogComponent, { ref: function (scope) { _this.dialogInstance = scope; }, minHeight: '50px', isModal: true, width: '350px', buttons: this.buttons, visible: this.status, target: '#e-pv-e-sign-dialog-target' })))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample enables two different users to sign the document. The first user must fill out and sign their designated fields, which are visible only to them. Once the first user has completed their section, the second user can be selected to fill out and sign their own fields. After both users have signed, the document can be finalized.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "More information on the PDF this.viewer instantiation can be found in this ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/pdfviewer/getting-started" }, "documentation section"),
                    "."))));
    };
    return ESigningPdfForms;
}(sample_base_1.SampleBase));
exports.ESigningPdfForms = ESigningPdfForms;
;
