// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Angular/source/pdfviewer/redaction.component.ts
import { Component, ViewEncapsulation, OnInit, ViewChild } from '@angular/core';
import { PdfViewerComponent, LinkAnnotationService, BookmarkViewService, MagnificationService, ToolbarService, NavigationService, TextSelectionService, PrintService, PageChangeEventArgs, LoadEventArgs, AnnotationService, FormDesignerService, PageOrganizerService, TextSearchService, PdfViewerModule, AnnotationAddEventArgs, AnnotationRemoveEventArgs, CreateArgs } from '@syncfusion/ej2-angular-pdfviewer';
import { ToolbarComponent, ToolbarModule, MenuModule, AppBarModule, ChangeEventArgs } from '@syncfusion/ej2-angular-navigations';
import { DialogComponent, DialogModule } from '@syncfusion/ej2-angular-popups';
import { ClickEventArgs } from '@syncfusion/ej2-buttons';
import { ButtonComponent, ButtonModule, SwitchModule } from '@syncfusion/ej2-angular-buttons';
import { SBDescriptionComponent } from '../common/dp.component';
import { SBActionDescriptionComponent } from '../common/adp.component';
import { ComboBoxModule } from '@syncfusion/ej2-angular-dropdowns';
import { UploaderComponent, UploaderModule } from '@syncfusion/ej2-angular-inputs';
/**
 * Default PdfViewer Controller
 */
@Component({
    selector: 'control-content',
    templateUrl: 'redaction.html',
    encapsulation: ViewEncapsulation.None,
    providers: [LinkAnnotationService, BookmarkViewService, TextSearchService, TextSelectionService, MagnificationService, ToolbarService, NavigationService, TextSelectionService, PrintService, AnnotationService, FormDesignerService, PageOrganizerService],
    styleUrls: ['pdfviewer.component.css'],
    standalone: true,
    imports: [
        SwitchModule,
        AppBarModule,
        ToolbarModule,
        MenuModule,
        PdfViewerModule,
        SBActionDescriptionComponent,
        SBDescriptionComponent,
        ButtonModule,
        DialogModule,
        UploaderModule,
        ComboBoxModule
    ],
})

export class RedactionComponent implements OnInit {

    @ViewChild('pdfviewer')
    public pdfviewerControl: PdfViewerComponent;

    @ViewChild('primaryToolbar')
    public primaryToolbar: ToolbarComponent;

    @ViewChild('secondaryToolbar')
    public secondaryToolbar: ToolbarComponent;

    @ViewChild('defaultButtonDownload') downloadBtn: ButtonComponent;

    @ViewChild('dialogComponent')
    public dialog: DialogComponent;

    @ViewChild('cancelButton')
    public cancelButton: ButtonComponent;
    public showCloseIcon: Boolean = true;
    public height = '482px';
    public target = '#e-pv-redact-sb-panel';
    public width = '477px';
    public visible: Boolean = false;
    public isModal: Boolean = true;

    @ViewChild('defaultupload')
    public uploadObj: UploaderComponent;
    public path: Object = {
        saveUrl: 'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Save',
        removeUrl: 'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Remove'
    };
    public dropElement: HTMLElement = document.getElementsByClassName('drop-area-wrap')[0] as HTMLElement;
    public allowedExtensions = '.png, .jpg, .jpeg';
    public imageSrc: any;

    public onFileChange(args: any): void {
        var file = args.file[0].rawFile;
        let imageElement = document.getElementById('imageView');
        let imageElementContainer = document.getElementById('imageContainer');
        let base64String: any;
        var reader = new FileReader();
        reader.onload = (e) => {
            base64String = e.target?.result as string;
            this.imageSrc = base64String;
            this.customStampSource = this.imageSrc;
            (imageElement as any).src = this.imageSrc;
            imageElementContainer.className =
                'image-container e-pv-redact-sb-image-container-selected';
            (imageElement as any).style.display = 'block';
            // Bind click event to the image element
            imageElement.addEventListener('click', this.handleImageClick.bind(this));
        };
        reader.readAsDataURL(file);
    }

    public handleImageClick() {
        this.customStampSource = this.imageSrc;
        this.dialog.hide();
        this.addImage();
    }

    public ngAfterViewInit(): void {
        this.downloadBtn.element.setAttribute("aria-label", "menu");
    }

    public document: string = "https://cdn.syncfusion.com/content/pdf/programmatical-annotations.pdf";
    public resource: string = "https://cdn.syncfusion.com/ej2/27.2.2/dist/ej2-pdfviewer-lib"; 
    public url: string = "https://ej2services.syncfusion.com/production/web-services/api/pdfviewer/Redaction";

    //zoom value
    public data: string[] = ['10%', '25%', '50%', '75%', '100%', '200%', '400%'];
    ngOnInit(): void {
        document.getElementById('fileUpload').addEventListener('change', this.readFile.bind(this));
    }

    public annotation: any;
    public redactionCount: number = 0;
    public fileName: string = "programmatical-annotations.pdf";
    //Updating the number of redaction while the annotation has been added
    annotationAdd = (e: AnnotationAddEventArgs): void => {
        var pdfAnnotationList = new Array();
        pdfAnnotationList = this.pdfviewerControl.annotationCollection;
        var selectedAnnotationIndex = pdfAnnotationList.findIndex(item => item.annotationId == e.annotationId);
        if (selectedAnnotationIndex != -1) {
            this.annotation = pdfAnnotationList[selectedAnnotationIndex];
        }
        if (this.annotation.author == "Redaction" || this.annotation.customStampName == "Image" || this.annotation.author == "Pattern" || this.annotation.author == "Text") {
            this.redactionCount = this.redactionCount + 1;
            this.updateRedaction();
        }

    }
    //Updating the number of redaction while the annotation has been removed
    annotationRemove = (e: AnnotationRemoveEventArgs): void => {
        if (this.annotation.author == "Redaction" || this.annotation.customStampName == "Image" || this.annotation.author == "Pattern" || this.annotation.author == "Text") {
            this.redactionCount = this.redactionCount - 1;
            this.updateRedaction();
        }
    }

    //To enable the redaction button based on count
    public updateRedaction(): void {
        if (this.redactionCount <= 0) {
            this.primaryToolbar.items[8].disabled = true;
        }
        else {
            this.primaryToolbar.items[8].disabled = false;
        }
    }

    //to read the file
    // tslint:disable-next-line
    private readFile(args: any): void {
        // tslint:disable-next-line
        let upoadedFiles: any = args.target.files;
        if (args.target.files[0] !== null) {
            let uploadedFile: File = upoadedFiles[0];
            this.fileName = upoadedFiles[0].name;
            if (uploadedFile) {
                let reader: FileReader = new FileReader();
                reader.readAsDataURL(uploadedFile);
                // tslint:disable-next-line
                let proxy: any = this;
                // tslint:disable-next-line
                reader.onload = (e: any): void => {
                    let uploadedFileUrl: string = e.currentTarget.result;
                    proxy.pdfviewerControl.documentPath = uploadedFileUrl;
                    proxy.pdfviewerControl.fileName = proxy.fileName;
                    proxy.pdfviewerControl.downloadFileName = proxy.fileName;
                };
            }
        }
    }

    //To open a file from viewer
    public openDocumentClicked(e: ClickEventArgs): void {
        document.getElementById('fileUpload').click();
    }

    //when the image button is clicked
    public imageDialog = (): void => {
        this.dialog.show();
    }

    //when cancel button clicked
    public closeDialog(e: ClickEventArgs): void {
        this.dialog.hide();
    }

    //Method to create rectangle annotation when "Text" button is clicked
    public addText(e: ClickEventArgs): void {
        this.pdfviewerControl.rectangleSettings = {
            fillColor: '#a3a2a0',
            strokeColor: '#a3a2a0',
            author: 'Text'
        }
        this.pdfviewerControl.annotation.setAnnotationMode('Rectangle');
    }

    public customStampSource: any = "";
    //Adding the image to the pdf
    public addImage(): void {
        this.pdfviewerControl.stampSettings.author = "Image";
        this.pdfviewerControl.customStampSettings = {
            width: 200,
            author: 'Image',
            height: 125,
            isAddToMenu: false,
            enableCustomStamp: false

        };
        this.pdfviewerControl.customStamp = [
            {
                customStampName: 'Image',
                customStampImageSource: this.customStampSource
            },
        ];
    }

    //Method to create rectangle annotation when the "Pattern" button is clicked
    public addPattern(e: ClickEventArgs): void {
        this.pdfviewerControl.rectangleSettings = {
            fillColor: '#dedfe0',
            strokeColor: '#dedfe0',
            author: 'Pattern'
        }
        this.pdfviewerControl.annotation.setAnnotationMode('Rectangle');
    }

    //Method to create rectangle annotation when the "Blackout" button is clicked
    public addBlackout(e: ClickEventArgs): void {
        this.pdfviewerControl.rectangleSettings = {
            fillColor: '#000000',
            strokeColor: '#000000',
            author: 'Redaction'
        }
        this.pdfviewerControl.annotation.setAnnotationMode('Rectangle');
    }

    //Method to create rectangle annotation when the "Whiteout" button is clicked
    public addWhiteout(e: ClickEventArgs): void {
        this.pdfviewerControl.rectangleSettings = {
            fillColor: '#ffffff',
            strokeColor: '#ffffff',
            author: 'Redaction'
        }
        this.pdfviewerControl.annotation.setAnnotationMode('Rectangle');

    }
    //To download the redacted pdf 
    public download(e: ClickEventArgs): void {
        this.pdfviewerControl.saveAsBlob().then((blob) => {
            const reader = new FileReader();
            reader.readAsDataURL(blob);
            reader.onload = (e: ProgressEvent<FileReader>) => {
              const base64String = e.target?.result;
              const xhr = new XMLHttpRequest();
              xhr.open('POST', this.url, true);
              xhr.setRequestHeader('Content-type', 'application/json; charset=UTF-8');
              const requestData = JSON.stringify({ base64String });
              xhr.onload = () => {
                if (xhr.status === 200) {
                  const responseBase64 = xhr.responseText.split('base64,')[1];
                  if (responseBase64) {
                    const blob = this.createBloburl(responseBase64, 'application/pdf');
                    const blobUrl = URL.createObjectURL(blob);
                    this.downloadDocument(blobUrl);
                  } else {
                    console.error('Invalid base64 response.');
                  }
                } else {
                  console.error('Download failed:', xhr.statusText);
                }
              };
              xhr.onerror = () => {
                console.error('An error occurred during the download:', xhr.statusText);
              };
              xhr.send(requestData);
            };
          }).catch((error) => {
            console.error('Error saving Blob:', error);
          });
    }

    public createBloburl(base64String: string, contentType: string):Blob{
        const sliceSize = 512;
        const byteCharacters = atob(base64String);
        const byteArrays: Uint8Array[] = [];
        for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
            const slice = byteCharacters.slice(offset, offset + sliceSize);
            const byteNumbers = Array.from(slice, char => char.charCodeAt(0));
            byteArrays.push(new Uint8Array(byteNumbers));
        }
        return new Blob(byteArrays, { type: contentType });
    }

    public downloadDocument(blobUrl: string):void{
        const anchorElement = document.createElement('a');
        anchorElement.href = blobUrl;
        anchorElement.target = '_parent';
        this.pdfviewerControl.fileName = this.fileName;
        const downloadFileName = this.pdfviewerControl.fileName || 'downloadedFile.pdf';
        anchorElement.download = downloadFileName.endsWith('.pdf') ? downloadFileName : `${downloadFileName}.pdf`;
        document.body.appendChild(anchorElement);
        anchorElement.click();
        document.body.removeChild(anchorElement);
        URL.revokeObjectURL(blobUrl);
    }

    //Method for moving to previous page
    public previousClicked(e: ClickEventArgs): void {
        this.pdfviewerControl.navigation.goToPreviousPage();
    }

    //Method for moving to next page 
    public nextClicked(e: ClickEventArgs): void {
        this.pdfviewerControl.navigation.goToNextPage();
    }

    //to get current page
    public pageChanged(e: PageChangeEventArgs): void {
        (document.getElementById('e-pv-redact-sb-currentPage') as HTMLSpanElement).textContent = this.pdfviewerControl.currentPageNumber.toString() + ' ';
        this.updatePageNavigation();
    }

    public onLoad(e: CreateArgs)
    {
        (document.getElementById('e-pv-redact-sb-drop-area-wrap') as HTMLDivElement).style.display="flex";
        (document.getElementById('e-pv-redact-sb-appbar') as HTMLDivElement).style.display="block";
    }

    //while loading document
    public documentLoaded(e: LoadEventArgs): void {
        document.getElementById('e-pv-redact-sb-totalPage').textContent = '/ ' + this.pdfviewerControl.pageCount;
        (document.getElementById('e-pv-redact-sb-currentPage') as HTMLSpanElement).textContent = this.pdfviewerControl.currentPageNumber.toString() + ' ';
        this.updatePageNavigation();
        this.updateRedaction();
    }

    //Zoom values changes when the percentage is selected from the dropdown
    public zoom: any;
    public previousZoom: any;
    public zoomValueChange(e: ChangeEventArgs) {
        this.zoom = (e as any).value;
        this.previousZoom = (e as any).previousItemData.value;
        if (this.zoom !== null || this.previousZoom !== null) {
            var zoomchange = parseInt(this.zoom.replace("%", ""), 10);
            this.pdfviewerControl.magnificationModule.zoomTo(zoomchange);
        }
    }

    //Updating the navigation button based on the page number either "enabled" or "disabled"
    private updatePageNavigation(): void {
        if (this.pdfviewerControl.currentPageNumber === 1) {
            this.secondaryToolbar.items[0].disabled=true;
            this.secondaryToolbar.items[2].disabled=false;
        } else if (this.pdfviewerControl.currentPageNumber === this.pdfviewerControl.pageCount) {
            this.secondaryToolbar.items[0].disabled=false;
            this.secondaryToolbar.items[2].disabled=true;
        } else {
            this.secondaryToolbar.items[0].disabled=false;
            this.secondaryToolbar.items[2].disabled=false;
        }
    }

    //To redact the pdf in server side using the button click event
    public redaction(): void {
        if (this.redactionCount > 0) {
            this.pdfviewerControl.saveAsBlob().then((blob) => {
                const reader = new FileReader();
                reader.readAsDataURL(blob);
                reader.onload = (e: ProgressEvent<FileReader>) => {
                    const base64String = e.target?.result;
                    const xhr = new XMLHttpRequest();
                    xhr.open('POST', this.url, true);
                    xhr.setRequestHeader('Content-type', 'application/json; charset=UTF-8');
                    const requestData = JSON.stringify({ base64String });
                    xhr.onload = () => {
                        if (xhr.status === 200) {
                            this.pdfviewerControl.load(xhr.responseText, null);
                        }
                        else {
                            console.error('Redaction failed:', xhr.statusText);
                        }
                    };
                    xhr.onerror = function () {
                        console.error('An error occurred during the redaction:', xhr.statusText);
                    };
                    xhr.send(requestData);
                }
            });
            this.redactionCount = 0;
            this.updateRedaction();
        }
    }

}

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/pdfviewer/redaction.tsx
﻿import * as React from 'react';
import {
    PdfViewerComponent, Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, Annotation, FormFields, FormDesigner,
    ThumbnailView, Print, TextSelection, TextSearch, PageOrganizer, Inject, AnnotationAddEventArgs,AnnotationRemoveEventArgs
} from '@syncfusion/ej2-react-pdfviewer';
import { ToolbarComponent, ItemsDirective, ItemDirective, ClickEventArgs, AppBarComponent } from '@syncfusion/ej2-react-navigations';
import { SampleBase } from '../common/sample-base';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import './pdf.component.css';
import { ComboBoxComponent } from '@syncfusion/ej2-react-dropdowns';
import { DialogComponent } from '@syncfusion/ej2-react-popups';
import { UploaderComponent } from '@syncfusion/ej2-react-inputs';
let viewer: PdfViewerComponent;

export class Redaction extends SampleBase<{}, {}> {
    public viewer: PdfViewerComponent;
    public toolbar: ToolbarComponent;
    public primaryToolbar: ToolbarComponent;
    public dropdown: ComboBoxComponent;
    public currentPageNumber: string = '1';
    public fileName: string = 'programmatical-annotations.pdf';
    public redactionCount: number = 0;
    public annotation: any;
    public dialogInstance: DialogComponent;
    public uploadObj;
    
    public asyncSettings = {
        saveUrl: 'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Save',
        removeUrl: 'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Remove'
    };
    public dropAreaRef = document.getElementsByClassName(
        'drop-area-wrap'
    )[0];
    public allowedExtensions: string = '.png, .jpg, .jpeg';
    public url: string = "https://ej2services.syncfusion.com/production/web-services/api/pdfviewer/Redaction";
    constructor(props: {}) {
        super(props)
        this.uploadObj = React.createRef();
    }

    componentDidMount(): void {
        viewer = (document.getElementById('container') as any).ej2_instances[0];
    }
    //To update page number when page has been changed
    onPageChange = () => {
        this.currentPageNumber = viewer.currentPageNumber.toString();
        (document.getElementById('e-pv-redact-sb-currentPage') as HTMLSpanElement).textContent = this.viewer.currentPageNumber.toString() + ' ';
        this.updatePageNavigation.bind(this);
    }
    
    //Updating the total number of pages while loading
    documentLoaded = () => {
        this.viewer = (document.getElementById('container') as any).ej2_instances[0];
        var pageCount = document.getElementById('e-pv-redact-sb-totalPage');
        pageCount.textContent = '/ ' + viewer.pageCount;
        (document.getElementById('e-pv-redact-sb-currentPage')).textContent = this.viewer.currentPageNumber.toString();
        this.updatePageNavigation();
        this.updateRedaction();
    }

    //To update page number when the previous and next button is clicked
    updatePageNavigation = () => {
        if (this.viewer.currentPageNumber === 1) {
            this.toolbar.enableItems(document.getElementById('previousPage').parentElement, false);
            this.toolbar.enableItems(document.getElementById('nextPage').parentElement, true);
        } else if (viewer.currentPageNumber === viewer.pageCount) {
            this.toolbar.enableItems(document.getElementById('previousPage').parentElement, true);
            this.toolbar.enableItems(document.getElementById('nextPage').parentElement, false);
        } else {
            this.toolbar.enableItems(document.getElementById('previousPage').parentElement, true);
            this.toolbar.enableItems(document.getElementById('nextPage').parentElement, true);
        }
    }

    //To update the redaction count
    updateRedaction = () => {
        if (this.redactionCount <= 0) {
            this.toolbar.enableItems(document.getElementById('redacticon').parentElement, false);
        }
        else {
            this.toolbar.enableItems(document.getElementById('redacticon').parentElement, true);
        }
    }

    //Updating the number of redaction while the annotation has been added
    annotationAdd = (e: AnnotationAddEventArgs) => {
        var pdfAnnotationList = new Array();
        pdfAnnotationList = this.viewer.annotationCollection;
        var selectedAnnotationIndex = pdfAnnotationList.findIndex(item => item.annotationId == e.annotationId);
        if (selectedAnnotationIndex != -1) {
            this.annotation = pdfAnnotationList[selectedAnnotationIndex];
        }
        if (this.annotation.author == "Redaction" || this.annotation.customStampName == "Image" || this.annotation.author == "Pattern" || this.annotation.author == "Text") {
            this.redactionCount = this.redactionCount + 1;
            this.updateRedaction();
        }

    }

    //Updating the number of redaction while the annotation has been removed
    annotationRemove = () => {
        if (this.annotation.author == "Redaction" || this.annotation.customStampName == "Image" || this.annotation.author == "Pattern" || this.annotation.author == "Text") {
            this.redactionCount = this.redactionCount - 1;
            this.updateRedaction();
        }
    }
    downloadDocument = (blobUrl: string) => {
        const Url:any = URL || webkitURL;
        blobUrl = Url.createObjectURL(blobUrl);
        viewer.fileName = this.fileName;
        const anchorElement:HTMLElement = document.createElement('a');
        if (anchorElement.click) {
            (anchorElement as HTMLAnchorElement).href = blobUrl;
            (anchorElement as HTMLAnchorElement).target = '_parent';
            if ('download' in anchorElement) {
                const downloadFileName = viewer.fileName || 'downloadedFile.pdf';
                if (downloadFileName) {
                    if (downloadFileName.endsWith('.pdf')) {
                        (anchorElement as HTMLAnchorElement).download = downloadFileName;
                    }
                    else {
                        const splitPdf:string = downloadFileName.split('.pdf')[0] + '.pdf';
                        (anchorElement as HTMLAnchorElement).download = splitPdf;
                    }
                }
                else {
                    (anchorElement as HTMLAnchorElement).download = 'Default.pdf';
                }
            }
            (document.body || document.documentElement).appendChild(anchorElement);
            anchorElement.click();
        }
        else {
            if (window.top === window &&
                blobUrl.split('#')[0] === window.location.href.split('#')[0]) {
                const padCharacter:string = blobUrl.indexOf('?') === -1 ? '?' : '&';
                blobUrl = blobUrl.replace(/#|$/, padCharacter + '$&');
            }
            window.open(blobUrl, '_parent');
        }
    }
    //To download the redacted pdf
    download = () => {
        let _this = this;
        viewer.saveAsBlob().then(function (value) {
            let reader = new FileReader();
            reader.readAsDataURL(value);
            reader.onload = function (e) {
                const base64String = e.target?.result as string;
                const xhr:XMLHttpRequest = new XMLHttpRequest();
                xhr.open('POST', _this.url, true);
                xhr.setRequestHeader('Content-type', 'application/json; charset=UTF-8');
                const requestData = JSON.stringify({ base64String: base64String });
                xhr.onload = function () {
                    if (xhr.status === 200) {
                        const blobUrl = _this.createBlobUrl(xhr.responseText.split('base64,')[1], 'application/pdf');
                        _this.downloadDocument(blobUrl);
                    }
                    else {
                        console.error('Download failed:', xhr.statusText);
                    }
                };
                xhr.onerror = function () {
                    console.error('An error occurred during the download:', xhr.statusText);
                };
                xhr.send(requestData);
            };
        }).catch(function (error) {
            console.error('Error saving Blob:', error);
        });
    }

    createBlobUrl = (base64String: string, contentType: string) => {
        const sliceSize:number = 512;
        const byteCharacters:string = atob(base64String);
        const byteArrays:any = [];
        for (let offset:number = 0; offset < byteCharacters.length; offset += sliceSize) {
            const slice:string = byteCharacters.slice(offset, offset + sliceSize);
            const byteNumbers:any = new Array(slice.length);
            for (let i:number = 0; i < slice.length; i++) {
                byteNumbers[parseInt(i.toString(), 10)] = slice.charCodeAt(i);
            }
            const byteArray:any = new Uint8Array(byteNumbers);
            byteArrays.push(byteArray);
        }
        const blob:any = new Blob(byteArrays, { type: contentType });
        return blob;
    }
    render() {
        let data: string[] = ['10%', '25%', '50%', '75%', '100%', '200%', '400%'];
        function template() {
            return (
                <div>
                <span id="e-pv-redact-sb-currentPage" title="Current Page">1 </span>
                <span id="e-pv-redact-sb-totalPage" title="Total Page">/ 1</span>
            </div>
            );
        }
        
        const clickHandler = function (args: ClickEventArgs) {
            switch (args.item.id) {
                case 'pdfviewer_open':
                    {
                        let fileUpload = document.getElementById(
                            'fileUpload'
                        ) as HTMLInputElement;
                        fileUpload.click();
                        break;
                    }
                case 'text_annot':
                    {
                        this.viewer.rectangleSettings.fillColor = '#a3a2a0';
                        this.viewer.rectangleSettings.strokeColor = '#a3a2a0';
                        this.viewer.rectangleSettings.author = 'Text';
                        this.viewer.annotation.setAnnotationMode('Rectangle');
                        break;
                    }
                case 'image_annot':
                    {
                        this.dialogInstance.show();
                        break;
                    }

                case 'pattern_annot':
                    {
                        this.viewer.rectangleSettings.fillColor = '#dedfe0';
                        this.viewer.rectangleSettings.strokeColor = '#dedfe0';
                        this.viewer.rectangleSettings.author = 'Pattern';
                        this.viewer.annotation.setAnnotationMode('Rectangle');
                        break;
                    }
                case 'black_annot':
                    {
                        this.viewer.rectangleSettings.fillColor = '#000000';
                        this.viewer.rectangleSettings.strokeColor = '#000000';
                        this.viewer.rectangleSettings.author = 'Redaction';
                        this.viewer.annotation.setAnnotationMode('Rectangle');
                        break;
                    }
                case 'white_annot':
                    {
                        this.viewer.rectangleSettings.fillColor = '#ffffff';
                        this.viewer.rectangleSettings.strokeColor = '#ffffff';
                        this.viewer.rectangleSettings.author = 'Redaction';
                        this.viewer.annotation.setAnnotationMode('Rectangle');
                        break;
                    }
                case 'previousPage':
                    {
                        viewer.navigation.goToPreviousPage();
                        break;
                    }
                case 'nextPage':
                    {
                        viewer.navigation.goToNextPage();
                        break;
                    }

                case 'redacticon':
                    {
                        if (this.redactionCount > 0) {
                            let _this = this;                         
                            viewer.saveAsBlob().then(function (value) {
                                var data = value;
                                var reader = new FileReader();
                                reader.readAsDataURL(data);
                                reader.onload = function (e) {
                                    var base64String = e.target?.result;
                                    var xhr = new XMLHttpRequest();
                                    xhr.open('POST', _this.url, true);
                                    xhr.setRequestHeader('Content-type', 'application/json; charset=UTF-8');
                                    var requestData = JSON.stringify({ base64String: base64String });
                                    xhr.onload = function () {
                                        if (xhr.status === 200) {
                                            viewer.load(xhr.responseText, null);
                                        }
                                        else {
                                            console.error('Redaction failed:', xhr.statusText);
                                        }
                                    };
                                    xhr.onerror = function () {
                                        console.error('An error occurred during the redaction:', xhr.statusText);
                                    };
                                    xhr.send(requestData);
                                };
                            });
                            this.redactionCount = 0;
                            this.updateRedaction();
                        }
                        break;
                    }
            }
        }

        //To get the header in upload image dialog box
        const header = () => {
            return (
                <div>
                    <div id="dlg-template" title="Upload image" className="e-icon-settings">Upload Image</div>
                </div>
            );
        }
        //When the cancel button is clicked
        const CloseDialog = function () {
            this.dialogInstance.hide();
        }

        //To get the footer content in upload image dialog box
        const footerTemplate = () => {
            return (
                <div>
                    <button id="cancelButton" className="e-control e-btn e-primary" data-ripple="true" onClick={CloseDialog.bind(this)}>Cancel</button>
                </div>
            );
        }

        //To get the content of dialog box
        const contentTemplate = () => {
            return (
                <div id='dialog'>
                    <div id='e-pv-redact-sb-defaultfileupload'>
                        <div className="drop-area-wrap" id='e-pv-redact-sb-drop-area-wrap'>
                            <div>
                                <UploaderComponent id='fileupload' type='file' ref={(scope) => { this.uploadObj.current = scope }} asyncSettings={this.asyncSettings} change={onFileChange.bind(this)} dropArea={this.dropAreaRef as any} allowedExtensions={this.allowedExtensions}></UploaderComponent>
                            </div>
                            <div>(Only JPG and PNG images will be accepted)</div>
                        </div>
                        <div className="e-pv-redact-sb-image-list">
                            <div id='imageContainer' className="e-pv-redact-sb-image-container">
                                <img id='imageView' className="e-pv-redact-sb-image-source" style={{ 'display': 'none' }} />
                            </div>
                        </div>
                    </div>
                </div>
            );
        }

        //When the zoom dropdown is changed
        const zoomValueChange = function (args) {
            let zoom = (args).value;
            let previousZoom = (args).previousItemData.value;
            if (zoom !== null || previousZoom !== null) {
                let zoomchange = parseInt(zoom.replace("%", ""), 10);
                viewer.magnificationModule.zoomTo(zoomchange);
            }

        }

        //To display the zoom percentage dropdown
        const dropDown = function () {
            return (
                <div><ComboBoxComponent width={88} popupWidth={80} value='100%' dataSource={data} showClearButton={false} change={zoomValueChange.bind(this)}></ComboBoxComponent></div>
            );
        }

        let imageSrc;
        let customStampSource;
        const onFileChange = function (args) {
            let file = args.file[0].rawFile;
            let imageElement = document.getElementById('imageView') as any;
            let imageElementContainer = document.getElementById('imageContainer');
            let reader = new FileReader();
            let _this = this;
            reader.onload = function (e) {
                let base64String = e.target ? e.target.result : null;
                imageSrc = base64String;
                customStampSource = imageSrc;
                (imageElement).src = imageSrc;
                imageElementContainer.className =
                    'image-container image-container-selected';
                (imageElement).style.display = 'block';
                // Bind click event to the image element
                imageElement.addEventListener('click', handleImageClick.bind(_this));
            };
            reader.readAsDataURL(file);
        }

        const handleImageClick = function () {
            customStampSource = imageSrc;
            this.dialogInstance.hide();
            addImage();
        }

        //To add the image in pdf
        const addImage = function () {
            viewer.stampSettings.author = "Image";
            viewer.customStampSettings = {
                width: 200,
                author: 'Image',
                height: 125,
                isAddToMenu: false,
                enableCustomStamp: false

            };
            viewer.customStamp = [
                {
                    customStampName: 'Image',
                    customStampImageSource: customStampSource
                },
            ];
        }

        return (<div>
            <div className="control-section" id='e-pv-redact-sb-panel'>
                <div className="flex-container" id="e-pv-redact-sb-flexContainer">

                </div>
                {/* Appbar */}
                <div className='control-container'>
                    <AppBarComponent colorMode="Primary">
                        <span className="regular">Redaction</span>
                        <div className="e-appbar-spacer"></div>
                        <ButtonComponent cssClass='e-inherit ' iconCss='e-icons e-download e-btn-icon e-icon-left' id='download_pdf' onClick={this.download}>Download</ButtonComponent>
                    </AppBarComponent>

                </div>
                <div className='primaryToolbar' id='toolbar_default'>
                    <ToolbarComponent ref={(scope) => { this.primaryToolbar = scope; }} clicked={clickHandler.bind(this)} id='e-pv-redact-sb-toolbar'>
                        <ItemsDirective>
                            <ItemDirective prefixIcon='e-icon e-folder' tooltipText='Open' cssClass='e-pv-redact-sb-open-container' id='pdfviewer_open' text='Open'></ItemDirective>
                            <ItemDirective type='Separator'></ItemDirective>
                            <ItemDirective prefixIcon='e-icon e-text-annotation' tooltipText='Text' cssClass='e-pv-redact-sb-font-container' text='Text' id='text_annot'></ItemDirective>
                            <ItemDirective prefixIcon='e-icons e-image' tooltipText='Image' cssClass='e-pv-redact-sb-image-container' text='Image' id='image_annot'></ItemDirective>
                            <ItemDirective prefixIcon='e-icons e-opacity' tooltipText='Pattern' cssClass='e-pv-redact-sb-pattern-container' text='Pattern' id='pattern_annot'></ItemDirective>
                            <ItemDirective prefixIcon='e-icons black-out' tooltipText='Blackout' cssClass='e-pv-redact-sb-black-out-container' text='Blackout' id='black_annot'></ItemDirective>
                            <ItemDirective prefixIcon='e-icons white-out' tooltipText='Whiteout' cssClass='e-pv-redact-sb-white-out-container' text='Whiteout' id='white_annot'></ItemDirective>
                            <ItemDirective type='Separator'></ItemDirective>
                            <ItemDirective prefixIcon='e-icons e-redact' tooltipText='Redaction' cssClass='e-pv-redact-sb-redaction-container' text='Redact' id='redacticon' disabled={true}></ItemDirective>
                        </ItemsDirective>
                    </ToolbarComponent>

                </div>

                <div className='e-pv-redact-sb-secondary-toolbar' id='toolbar_secondary'>
                    <ToolbarComponent ref={(scope) => { this.toolbar = scope; }} clicked={clickHandler.bind(this)} id='e-pv-redact-sb-toolbar-secondary'>
                        <ItemsDirective>
                            <ItemDirective prefixIcon='e-icons e-chevron-left' cssClass='e-pv-redact-sb-previous-container' tooltipText="Previous Page" id='previousPage' disabled={true}></ItemDirective>
                            <ItemDirective template={template} tooltipText="Page Number"></ItemDirective>
                            <ItemDirective prefixIcon='e-icon e-chevron-right' cssClass='e-pv-redact-sb-next-container'  tooltipText="Next Page" id='nextPage' disabled={true}></ItemDirective>
                            <ItemDirective cssClass='percentage' type="Input" tooltipText="Zoom" template={dropDown} align="Left" />
                        </ItemsDirective>
                    </ToolbarComponent>
                </div>

                <div id="targetDialog" className="dialog-element">
                    <DialogComponent header={header as any} footerTemplate={footerTemplate as any} content={contentTemplate as any} showCloseIcon={true} target="#targetDialog" width={'437px'} height={'255px'} visible={false} isModal={true} ref={(scope) => { this.dialogInstance = scope; }} id='e-pv-redact-sb-dialog'></DialogComponent>
                </div>
                {/* Render the PDF Viewer */}
                <PdfViewerComponent ref={(scope) => { this.viewer = scope; }} id="container" documentPath="https://cdn.syncfusion.com/content/pdf/programmatical-annotations.pdf" resourceUrl="https://cdn.syncfusion.com/ej2/27.1.55/dist/ej2-pdfviewer-lib"
                    style={{ 'height': '640px' }}
                    enableToolbar={false} enableNavigationToolbar={false} enableAnnotationToolbar={false} enableCommentPanel={false}
                    documentLoad={this.documentLoaded} pageChange={this.onPageChange} annotationAdd={this.annotationAdd} annotationRemove={this.annotationRemove}>
                    <Inject services={[Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormFields, FormDesigner, PageOrganizer]} />
                </PdfViewerComponent>
                <input type="file" id="fileUpload" accept=".pdf" onChange={this.readFile.bind(this)} style={{ 'display': 'block', 'visibility': 'hidden', 'width': '0', 'height': '0' }} />
            </div>
            <div id="action-description">
                <p> The PDF Viewer facilitates the permanent removal of sensitive or confidential data from PDF files. Simplifying
                    the redaction process, Syncfusion’s <a target='_blank'
                        href='https://www.syncfusion.com/document-processing/pdf-framework/net/pdf-library'
                        aria-label="Navigate to the Redaction Documendation in PDF library">.NET PDF library</a> includes features
                    for seamless implementation. </p>
            </div>
            <div id="description">
                <p> This example showcases the implementation of redaction using rectangle annotation, leveraging the Redaction
                    feature in <a target='_blank' href='https://help.syncfusion.com/file-formats/pdf/working-with-redaction'
                        aria-label="Navigate to the Redaction Documendation by pdf viewer Library">File formats</a>.</p>
                <br />
                <p>Various types of redactions are demonstrated: </p>
                <br />
                <ul>
                    <li>Displaying text over the redacted area</li>
                    <li>Adding an image to the redacted area</li>
                    <li>Drawing patterns on the redacted area</li>
                    <li>Blacking out the redacted area</li>
                    <li>Whitening out the redacted area</li>
                </ul>
                <br />
                <p> Upon selecting areas on a page or across different pages with different redaction options, users can click the
                    `Redact button`. This action redacts the document and reloads it into the PDF Viewer. The redacted document can
                    then be saved or downloaded. </p>

                <p>
                    More information on adding annotation programmatically can be found in this <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/introduction"> documentation section</a>.
                </p>
            </div>
        </div>
        );
    }

    //To read the file when loaded
    public readFile(evt) {
        let proxy = this;
        let uploadedFiles = evt.target.files;
        let uploadedFile = uploadedFiles[0];
        this.fileName = uploadedFile.name;
        let reader = new FileReader();
        reader.readAsDataURL(uploadedFile);
        reader.onload = function (e) {
            let uploadedFileUrl: string = (e.currentTarget as any).result;
            viewer.documentPath = uploadedFileUrl;
            viewer.fileName = proxy.fileName;
            viewer.downloadFileName = proxy.fileName;
        }
    }
}
