// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/uploader/preload-files.jsx
import * as React from 'react';
import './uploader.css';
import { SampleBase } from '../common/sample-base';
import { PropertyPane } from '../common/property-pane';
import { UploaderComponent, FilesDirective, UploadedFilesDirective } from '@syncfusion/ej2-react-inputs';
export class Preloadfiles extends SampleBase {
    // Uploader component
    uploadObj;
    uploadWrapper = document.getElementsByClassName('e-upload')[0];
    dropElement;
    asyncSettings;
    dropContainerRef;
    dropContainerEle;
    constructor(props) {
        super(props);
        this.dropContainerEle = null;
        this.dropContainerRef = element => {
            this.dropContainerEle = element;
        };
        this.asyncSettings = {
            saveUrl: 'http://localhost:62728/api/FileUploader/Save',
            removeUrl: 'http://localhost:62728/api/FileUploader/Remove'
        };
    }
    rendereComplete() {
        this.dropElement = this.dropContainerEle;
        this.uploadObj.dropArea = this.dropElement;
        this.uploadObj.dataBind();
        this.uploadObj.element.setAttribute('name', 'UploadFiles');
    }
    onRemoveFile(args) {
        args.postRawFile = false;
    }
    clearButtonClick() {
        this.uploadObj.clearAll();
    }
    render() {
        return (<div className='control-pane' ref={this.dropContainerRef}>
			<div className='control-section uploadpreview'>
				<div className='col-lg-9'>
					<div className='validation_wrapper'>
						<UploaderComponent id='validation' type='file' ref={(scope) => { this.uploadObj = scope; }} asyncSettings={this.asyncSettings} removing={this.onRemoveFile.bind(this)}>
							<FilesDirective>
								<UploadedFilesDirective name="Nature" size={25000} type=".png"></UploadedFilesDirective>
								<UploadedFilesDirective name="TypeScript succinctly" size={12000} type=".pdf"></UploadedFilesDirective>
								<UploadedFilesDirective name="ASP.NET" size={17000} type=".docx"></UploadedFilesDirective>
							</FilesDirective>
						</UploaderComponent>
					</div>
				</div>
					<div className='property-section preload-panel col-lg-3'>
						<PropertyPane title='Properties'>
							<div className='panel-style'>
								<button className="e-btn e-css" onClick={this.clearButtonClick = this.clearButtonClick.bind(this)} id="clearbtn" title="Clear All">Clear All</button>
							</div>
						</PropertyPane>
					</div>
			</div>
			<div id="action-description">
				<p>This <a href="https://www.syncfusion.com/react-ui-components/react-file-upload" target="_blank">&nbsp;React File Upload</a> example demonstrates how to pre-load the files of the Uploader. The already uploaded files are configured in file list to view and remove them.</p>
			</div>
			<div id="description">
				<p>The Uploader component allows to load initial list of files which are already uploaded in server. The preload files are useful to view and remove from server.
				Also, you can achieve state persistence on page refresh.</p>
				
				<p>For more information, you can refer to the Preload Files section from this <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/uploader/async/#preload-files">documentation section</a>.</p>
				
				<p>To achieve state persistence, you can refer to this How-to section.</p>
			</div>
      </div>);
    }
}

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/source/uploader/preload-files.vue
<template>
  <div>
    <div class="col-lg-8 control-section uploader-preload preloadfiles">
        <div class="control_wrapper">
            <ejs-uploader id='preloadFiles' ref="uploadObj" name="UploadFiles" :asyncSettings= "path"
            :dropArea = "dropElement" :removing= "onFileRemove" >
                 <e-files>
                    <e-uploadedfiles name='Nature' size=11000 type='.png'></e-uploadedfiles>
                    <e-uploadedfiles name='TypeScript Succinctly' size=20000 type='.pdf'></e-uploadedfiles>
                    <e-uploadedfiles name='ASP.NET Webhooks' size=35000 type='.docx'></e-uploadedfiles>
                </e-files>
            </ejs-uploader>
        </div>
    </div>
    <div class="col-lg-4 property-section">
        <div id="property" title="Properties">
            <div style="margin-left: 50px; padding-top:25px;">
                <ejs-button id="clearbtn" style="width:130px">Clear All</ejs-button>
            </div>
        </div>
    </div>
    <div id="action-description">
      <p>This <a href="https://www.syncfusion.com/vue-ui-components/vue-file-upload"
            target="_blank">&nbsp;Vue File Upload</a> example demonstrates how to pre-load the files of the Uploader. The already uploaded files are configured in file list to view and remove them.</p>
    </div>

    <div id="description">
        <p>The Uploader component allows to load initial list of files which are already uploaded in server. The preload files are useful to view and remove from server.
            Also, you can achieve state persistence on page refresh.</p>
        <p>For more information, you can refer to the 
           <a href='https://ej2.syncfusion.com/vue/documentation/uploader/async/#preload-files' target="_blank"> Preload Files
           </a> section from the documentation</p>
    </div>
</div>
</template>

<style scoped>
.preloadfiles .control_wrapper {
    max-width: 450px;
    min-width: 245px;
    margin: auto;
}
#preloadFiles .e-upload.e-control {
    position: relative;
    margin: 15px 0;
}

.control-section.preloadfiles .uploader-preload.col-lg-8 {
    padding: 20px;
}

</style>
<script>
import { UploaderComponent, FilesDirective, UploadedFilesDirective} from '@syncfusion/ej2-vue-inputs';
import {ButtonComponent} from '@syncfusion/ej2-vue-buttons';

export default {
    data: function(){
        return {
          path:  {
            saveUrl: 'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Save',
            removeUrl: 'https://ej2services.syncfusion.com/production/web-services/api/FileUploader/Remove'
          },
          dropElement: '.control-fluid'
        }
    },
    components: { 
        'ejs-uploader': UploaderComponent,
        'ejs-button': ButtonComponent,
        'e-files': FilesDirective,
        'e-uploadedfiles': UploadedFilesDirective
    },
     mounted: function () {
        document.getElementById('clearbtn').onclick = () => {
            this.$refs.uploadObj.clearAll();
        };
    },
    methods:{
        onFileRemove: function (args) {
            args.postRawFile = false;
        }
    }
};
</script>
