// frontend/Syncfusion/29.1.33/JavaScript2/Samples/React/src/pivot-table/remote.jsx
import * as React from 'react';
import { PivotViewComponent } from '@syncfusion/ej2-react-pivotview';
import { SampleBase } from '../common/sample-base';
import { DataManager, WebApiAdaptor } from '@syncfusion/ej2-data';
import { DropDownListComponent } from '@syncfusion/ej2-react-dropdowns';
import './remote.css';
/**
 * PivotView sample for Remote data source.
 */
export class Remote extends SampleBase {
    pivotObj;
    fields = { text: 'text', value: 'value' };
    contentTypes = [
        { 'value': 'JSON', 'text': 'JSON' },
        { 'value': 'CSV', 'text': 'CSV' }
    ];
    remoteData = new DataManager({
        url: 'http://localhost:62728/api/order',
        adaptor: new WebApiAdaptor,
        crossDomain: true
    });
    jsonReport = {
        url: '',
        dataSource: this.remoteData,
        type: 'JSON',
        expandAll: true,
        filters: [],
        columns: [{ name: 'ProductName', caption: 'Product Name' }],
        rows: [{ name: 'ShipCountry', caption: 'Ship Country' }, { name: 'ShipCity', caption: 'Ship City' }],
        formatSettings: [{ name: 'UnitPrice', format: 'C0' }],
        values: [{ name: 'Quantity' }, { name: 'UnitPrice', caption: 'Unit Price' }]
    };
    csvReport = {
        url: 'http://localhost:62728/api/product',
        type: 'CSV',
        expandAll: false,
        enableSorting: true,
        formatSettings: [{ name: 'Total Cost', format: 'C0' }, { name: 'Total Revenue', format: 'C0' }, { name: 'Total Profit', format: 'C0' }],
        drilledMembers: [{ name: 'Item Type', items: ['Baby Food'] }],
        rows: [
            { name: 'Region' },
            { name: 'Country' }
        ],
        columns: [
            { name: 'Item Type' },
            { name: 'Sales Channel' }
        ],
        values: [
            { name: 'Total Cost' },
            { name: 'Total Revenue' },
            { name: 'Total Profit' }
        ],
        filters: []
    };
    ddlOnChange(args) {
        if (args.value === 'JSON') {
            this.pivotObj.dataSourceSettings = this.jsonReport;
        }
        else if (args.value === 'CSV') {
            this.pivotObj.dataSourceSettings = this.csvReport;
        }
    }
    render() {
        return (<div className='control-pane'>
                <div className='control-section component-section'>
                    <div id='dropdown-control' style={{ marginBottom: '5px' }}>
                        <table style={{ maxWidth: '330px' }}>
                            <tbody>
                                <tr style={{ height: '50px' }}>
                                    <td>
                                        <div><b>Content Type:</b>
                                        </div>
                                    </td>
                                    <td>
                                        <div style={{ paddingLeft: '5px' }}>
                                            <div>
                                                <DropDownListComponent placeholder={'Content Type'} fields={this.fields} change={this.ddlOnChange.bind(this)} id="contenttype" index={0} enabled={true} dataSource={this.contentTypes}/>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <PivotViewComponent id='PivotView' ref={(pivotview) => { this.pivotObj = pivotview; }} dataSourceSettings={this.jsonReport} width={'100%'} height={'300'} gridSettings={{ columnWidth: 120 }}>
                    </PivotViewComponent>
                </div>
                <div id="action-description">
                    <p>This sample demonstrates basic rendering of the pivot table bound to JSON or CSV data pulled from a remote server.</p>
                </div>
                <div id="description">
                    <p>The pivot table supports JSON and CSV data source. The
                        <code>dataSourceSettings-&gt;dataSource</code> property can be assigned with the result of DataManager to bind remote data.</p>
                                    The
                    <code>DataManager</code>, which will act as an interface between the service endpoint and the pivot table, will require the below minimal
                                    information to interact with service endpoint properly.
                    <ul>
                        <li>
                            <code>DataManager-&gt;url</code> - Defines the service endpoint to fetch data.</li>
                        <li>
                            <code>DataManager-&gt;adaptor</code> - Defines the adaptor option. Here,
                            <code>WebApiAdaptor</code> is used for remote binding.</li>
                    </ul>
                                    In this demo, remote data is bound by assigning service data as an instance of
                    <code>DataManager</code> to the
                    <code>dataSourceSettings-&gt;dataSource</code> property. But for CSV, the service URL is directly set to <code>url</code> for remote data consumption.
                    <br />
                    <p>
                        More information on the Essential<sup>®</sup> JS2 Pivot Table can be found in these <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/pivotview/data-binding#binding-json-data-via-remote">JSON</a> & <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/pivotview/data-binding#binding-csv-data-via-remote">CSV</a> documentation section.
                    </p>
                </div>
            </div>);
    }
}

// frontend/Syncfusion/29.1.33/JavaScript2/Samples/Vue/source/pivot-table/remote.vue
﻿<template>
  <div>
    <div class="control-section">
      <div id="dropdown-control" style="margin-bottom:5px;">
        <table style="max-width: 330px;">
          <tbody>
            <tr style="height: 50px">
              <td>
                <div>
                  <b>Content Type:</b>
                </div>
              </td>
              <td>
                <div style="padding-left: 5px;">
                  <ejs-dropdownlist
                    id="contenttype"
                    :change="ddlOnChange"
                    :dataSource="contentTypes"
                    index="0"
                    placeholder="Content Types"
                  ></ejs-dropdownlist>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="content-wrapper">
        <ejs-pivotview
          id="pivotview"
          ref="pivotview"
          :dataSourceSettings="jsonReport"
          :gridSettings="gridSettings"
          :width="width"
          :height="height"
        ></ejs-pivotview>
      </div>
    </div>

    <div id="action-description">
      <p>This sample demonstrates basic rendering of the pivot table bound to JSON or CSV data pulled from a remote server.</p>
    </div>
    <div id="description">
      <p>
        The pivot table supports JSON and CSV data source. The
        <code>dataSourceSettings->dataSource</code> property can be assigned with the result of DataManager to bind remote data.
      </p>The
      <code>DataManager</code>, which will act as an interface between the service endpoint and the pivot table, will require the below minimal
      information to interact with service endpoint properly.
      <ul>
        <li>
          <code>DataManager->url</code> - Defines the service endpoint to fetch data.
        </li>
        <li>
          <code>DataManager->adaptor</code> - Defines the adaptor option. Here,
          <code>WebApiAdaptor</code> is used for remote binding.
        </li>
      </ul>In this demo, with respect to JSON remote data, is bound by assigning service data as an instance of
      <code>DataManager</code> to the
      <code>dataSourceSettings->dataSource</code> property. But for CSV, the service URL is directly set to
      <code>url</code> for remote data consumption.<br />
      <p>
          More information on the Essential<sup>®</sup> JS2 Pivot Table can be found in these <a target="_blank"
              href="https://ej2.syncfusion.com/vue/documentation/pivotview/data-binding#binding-json-data-via-remote">JSON</a> & <a target="_blank"
              href="https://ej2.syncfusion.com/vue/documentation/pivotview/data-binding#binding-csv-data-via-remote">CSV</a> documentation section.
      </p>
    </div>
  </div>
</template>
<script lang="ts">
import {
  PivotViewComponent,
  IDataSet,
  IDataOptions
} from "@syncfusion/ej2-vue-pivotview";
import {
  DropDownListComponent,
  ChangeEventArgs
} from "@syncfusion/ej2-vue-dropdowns";
import { extend, enableRipple } from "@syncfusion/ej2-base";
import {
  DataManager,
  Query,
  ReturnOption,
  WebApiAdaptor
} from "@syncfusion/ej2-data";
enableRipple(false);

let remoteData: DataManager = new DataManager({
  url: "https://ej2services.syncfusion.com/production/web-services/api/order",
  adaptor: new WebApiAdaptor(),
  crossDomain: true
});

export default {
  components: {
    'ejs-pivotview': PivotViewComponent,
    'ejs-dropdownlist': DropDownListComponent
  },
  data: () => {
    return {
      jsonReport: {
        url: "",
        dataSource: remoteData,
        type: "JSON",
        expandAll: true,
        filters: [],
        columns: [{ name: "ProductName", caption: "Product Name" }],
        rows: [
          { name: "ShipCountry", caption: "Ship Country" },
          { name: "ShipCity", caption: "Ship City" }
        ],
        formatSettings: [{ name: "UnitPrice", format: "C0" }],
        values: [
          { name: "Quantity" },
          { name: "UnitPrice", caption: "Unit Price" }
        ]
      },
      csvReport: {
        url: "https://ej2services.syncfusion.com/production/web-services/api/product",
        type: "CSV",
        expandAll: false,
        enableSorting: true,
        formatSettings: [
          { name: "Total Cost", format: "C0" },
          { name: "Total Revenue", format: "C0" },
          { name: "Total Profit", format: "C0" }
        ],
        drilledMembers: [{ name: "Item Type", items: ["Baby Food"] }],
        rows: [{ name: "Region" }, { name: "Country" }],
        columns: [{ name: "Item Type" }, { name: "Sales Channel" }],
        values: [
          { name: "Total Cost" },
          { name: "Total Revenue" },
          { name: "Total Profit" }
        ],
        filters: []
      },
      gridSettings: { columnWidth: 120 },
      height: 300,
      width: "100%",
      contentTypes: ["JSON", "CSV"]
    };
  },
  methods: {
    ddlOnChange: function(args: ChangeEventArgs) {
      let pivotObj = ((this as any).$refs.pivotview).ej2Instances;
      if (args.value === "JSON") {
        pivotObj.dataSourceSettings = (this as any).jsonReport;
      } else if (args.value === "CSV") {
        pivotObj.dataSourceSettings = (this as any).csvReport;
      }
    }
  }
}
</script>

<style scoped>
/deep/ #pivotview {
  width: 100%;
}
/deep/ .control-section {
  padding-top: 8px !important;
}
</style>
